### ISSUE TITLE
行情文件的读取

### ISSUE THREAD

**Issue by renzeya** [ricequant/rqalpha#10]
请问如何使用自己的行情作为回测依据呢？比如我有外盘数据，也想用于回测，如何自定义产品？

**Comment by cedricporter** [comment]
如果需要自定义产品，您可以阅读源代码，然后根据您的需要进行修改。

如果需要使用自己的行情，你可以参考 `rqalpha/data/data_accessor.py` 中的 `LocalDataProxy` 实现一个您的数据源。
