### ISSUE TITLE
请问MOD中如何定义函数？

### ISSUE THREAD

**Issue by yehx1** [ricequant/rqalpha#104]
您好！
我看到FuncatAPIMod定义了一些函数，我也仿照这种模式在helloword里定义了函数，代码如下：

```python
# -*- coding: utf-8 -*-
from rqalpha.interface import AbstractMod
class HelloWorldMod(AbstractMod):
    def start_up(self, env, mod_config):
        print(">>> HelloWorldMod.start_up1")
        class rrrr():
            def geta(self, s):
                print s
    def tear_down(self, success, exception=None):
        print(">>> HelloWorldMod.tear_down")
def load_mod():
    return HelloWorldMod()
```
我觉得这样写肯定不对，而且不知道怎么去调用这个函数，直接使用geta（）不工作。
请问该怎么做呢，谢谢！
如果可以，完成之后我来写个文档。
@wh1100717

**Comment by yehx1** [comment]
# -*- coding: utf-8 -*-
from rqalpha.interface import AbstractMod
class HelloWorldMod(AbstractMod):
    def start_up(self, env, mod_config):
        print(">>> HelloWorldMod.start_up1")
        class rrrr():
            def geta(self, s):
                print s
    def tear_down(self, success, exception=None):
        print(">>> HelloWorldMod.tear_down")
def load_mod():
    return HelloWorldMod()

**Comment by wh1100717** [comment]
@yehx1 http://rqalpha.io/zh_CN/latest/development/data_source.html#api
