### ISSUE TITLE
history_bars 问题

### ISSUE THREAD

**Issue by littleicgar** [ricequant/rqalpha#106]
history_bars include_now参数为True或False时按照文档理解的话应该只差一天的数据，即前者包含了当天的不完整bar的信息。但实际上在网站上出来的数据相差了两天。参数为True时，不仅包含了当天不完整bar的信息，还包含了当天完整bar的信息

**Comment by cedricporter** [comment]
线上修复了，您再试试

**Comment by littleicgar** [comment]
确实已经修复
