### ISSUE TITLE
手续费 佣金平台回测的时候有问题！！

### ISSUE THREAD

**Issue by shaoshoutianheyu** [ricequant/rqalpha#11]
设置如下：
context.commission = 0.
context.slippage = 0.
init_cash = 10000000
落单如下：
在2014年1月1日全仓 买入000001 股票
测试结果如下：（20140101的交易情况）
[Trade({'order_book_id': '000001.XSHE', 'order_id': '50da6d406a614b049717effec75f7f77', 'tax': 0, 'commission': 5, 'amount': 1412400, 'price': 7.0800000000000001, 'date': Timestamp('2014-01-01 15:00:00', offset='D')})]
我的疑问：
commission 等于5 是怎么来的，price如何确定的，amount又是怎样？俩乘起来会不会超过初始资金10000000？？？？？？？？？？？？？

**Comment by handsomu** [comment]
commission为5，是一个产生交易之后固定的最小费用，就算设置了commission为0，也会产生。不过按照一般交易习惯，应该是每笔order中的所有trade产生的commission最小为5，而不是每笔trade。这里是个可以改进的地方。
amount应该是在目前cash允许范围之内，能够买取的最多股数。俩乘起来不应该超过初始资金的。因为股票有100股的round lot限制，所以在上面的情况下，显然(1412400+100) * 7.08就超过资金限制了。
7.08是2014-01-02的收盘价，具体撮合是以什么价格成交，可以在源代码中进行确认。

**Comment by cedricporter** [comment]
券商手续费最低5元。这个设定如果需要修改的话，可以修改下`rqalpha/analyser/commission.py`的 min_commission
