### ISSUE TITLE
rqalpha mod install 命令 bug

### ISSUE THREAD

**Issue by Cuizi7** [ricequant/rqalpha#111]
RQAlpha 2.1.4
pyhton 3.5
MacOS 10.12.4

执行 rqalpha mod insatall xxx
当尝试安装不存在的mod 试，虽然安装失败，但 mod 列表中仍会出现该不存在的mod。

**Comment by Cuizi7** [comment]
![Uploading 4050164C-8FA5-41F2-B079-68A26811C69B.png…]()

**Comment by Cuizi7** [comment]
![4050164c-8fa5-41f2-b079-68a26811c69b](https://cloud.githubusercontent.com/assets/20850839/25473130/c0f123c4-2b60-11e7-9ef5-0bee799f8e3e.png)

**Comment by wh1100717** [comment]
develop 分支已经修复~ 下一个版本发布会解决该问题
