### ISSUE TITLE
扩展数据源无法覆写get_last_price方法？

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#115]
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

```python
# 在自己的DataSource类里定义获取最新价格的函数
def get_last_price(self, *args, **kwargs):
    print("call here....")
    return super().get_last_price(*args, **kwargs)

```

并没有执行到

**Comment by dongyi** [comment]
看了下是要写在自己的price board类里，但是mod初始化注入的时候要生成一个BarDictPriceBoard的实例， 需要bar_dict参数  不知如何生成

**Comment by wh1100717** [comment]
BarDictPriceBoard 是基于AbstractPriceBoard 扩展的 但实际上不需要初始化的时候获取 bar_dict 这只是我们的一种实现而已。

实际上可以直接通过 Environment.get_instance().bar_dict 来获取。

https://github.com/ricequant/rqalpha/commit/2c076bb4600a05b1e507aa740a488e3fb1bc417d Commit 取消了初始化的时候 bar_dict 作为依赖项的传入，改用了 创建了一个 _bar_dict 的property 来实现对应数据的读取，您可以参考一下。

目前代码提交到了develop 分支，如果您需要继承BarDictPriceBoard，要么使用develop分支 要么稍微等一下 今天会发布一个新的版本，其中包含了此次修改。

**Comment by wh1100717** [comment]
@dongyi 2.2.0 已经发布
