### ISSUE TITLE
对期货平仓指令进行拓展

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha#116]
1. POSITION_EFFECT ENUM加入CLOSE_TODAY选项。
2. buy_close, sell_close加入position_effect参数。默认为None，此时的平仓操作针对上期所情况按照先进先出原则，先平昨仓，后平今仓。（所以可能会发出多笔订单）设置为'close'代表平昨仓；'close_today'代表平今仓。其他值无效。
3. 将现有发单函数 LimitOrder(10)这种创建限价单的方式进行拓展，只要用户在发单中指定了价格，自动按照限价单处理。
4. 引入order(order_book_id, quantity, price) API，对于期货来说，quantity为+1代表buy_close 1张或 buy_open一张。按照先平仓，后开仓的顺序进行订单创建。对于股票来说，等同于order_shares，按照股数进行订单创建。

**Comment by wh1100717** [comment]
1.  ✅ `POSITION_EFFECT ENUM` 增加 `CLOSE_TODAY` Option
2.  引入调仓函数 `order(order_book_id, quantity, price=None)` API
  * 如果不传入 `price` 则认为执行的是 MarketOrder 类型订单，否则下 LimitOrder 订单
  * 期货
    * quantity > 0: 往 BUY 方向调仓 quantity 手
    * quantity < 0: 往 SELL 方向调仓 quantity 手
  * 股票
    * 相当于 `order_shares` 函数
3.  引入调仓函数 `order_to(order_book_id, quantity, price=None)` API
  * 基本逻辑和 `order` 函数一致。
  * 区别在于 quantity 表示调仓对应的最终仓位
4.  现有所有下单函数，增加 `price` option，具体行为和 `order` | `order_to` 一致
5.  `buy_close` | `sell_close` 增加 `position_effect` 参数，默认为None。时的平仓操作针对上期所情况按照先进先出原则，先平昨仓，后平今仓。（所以可能会发出多笔订单）设置为'close'代表平昨仓；'close_today'代表平今仓。其他值无效。

**Comment by wh1100717** [comment]
@handsomu 这个已经全部实现了 develop 分支可测试。
