### ISSUE TITLE
运行回测报ZeroDivisionError

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#119]
## 1. RQAlpha的版本
- 2.2.0

## 2. Python的版本
- 3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
- 用你们最新的bcolz数据也会出这个问题， 就跑rsi那个策略

## 5. 您出现的错误堆栈日志信息
```python
  portfolio.py  line 116
  return self.total_value / self._units

ZeroDivisionError: division by zero
```

**Comment by wh1100717** [comment]
@dongyi 新版本如果通过命令行运行， 不指定--security  会出现一些问题  可以暂时通过指定 --security stock 的方式来解决。

一会会更新，默认为stock
