### ISSUE TITLE
测试rqalpha run -f multi_rsi.py   策略时出现amount error.

### ISSUE THREAD

**Issue by shaoshoutianheyu** [ricequant/rqalpha#12]
按照RQalpha的指导，测试了rsi策略。
背景：
本地的.rqalpha数据不是最新，但是有2014-1-1 到2016-1-1的数据
步骤：
运行以下命令，将开始回测
cd examples
rqalpha run -f multi_rsi.py -s 2014-01-01 -e 2016-01-01 -o result.pkl --plot
注 ： 策略完全就是RQalpha的例子，没有什么改动。
error提示:
[2016-08-31 23:54:59.420540] INFO: 报告: target available cash caled: 290.393311284
[2016-08-31 23:54:59.421540] ERROR: user_log: order_shares 601988.XSHG amount is 0.
测试结果：
结果和RQalpha的例子的结果是一致的。
疑问：
为什么会有这样的日志？INFO和ERROR说的是个什么？这个ERROR会不会影响到测试的准确性？INFO和ERROR在RQalpha项目里那个py文件可以查到？谢谢

**Comment by cedricporter** [comment]
ERROR 只是 提示出错，例如 `ERROR: user_log: order_shares 601988.XSHG amount is 0.`

是指下单的股数是0，所以报了一个错误。这里没有翻译成中文，造成误解，非常抱歉。

**Comment by StonePoe** [comment]
我在跑你们提供的multi_rsi这个示例的时候也有类似的问题，会有报错
[2015-12-02 15:00:00] ERROR: order_shares 000068.XSHE amount is 0.
这个对结果有影响吗

**Comment by cedricporter** [comment]
没有影响
