### ISSUE TITLE
set_data_source后， bar_dict是空的

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#120]
## 1. RQAlpha的版本
- 2.2.0

## 2. Python的版本
- 3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
- 扩展的DataSource， 在set_data_source后，运行回测报错， 报错信息里bar_dict = BarMap() 是空的

**Comment by dongyi** [comment]
和 #119 一样  用--security stock 就好了

**Comment by wh1100717** [comment]
@dongyi 恩 建议平时运行的时候就指定 要交易的 security  默认值的问题下一个小版本发布的时候会解决
