### ISSUE TITLE
update bundle之后 adjusted_dividends.bcolz 文件夹缺失

### ISSUE THREAD

**Issue by yu123ert** [ricequant/rqalpha#121]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本 
2.2.1

## 2. Python的版本
3.5

## 3. 是Windows/Linux/MacOS or others?
windows

## 5. 您出现的错误堆栈日志信息
   return bcolz.carray(rootdir=rootdir, mode=mode)
  File "bcolz/carray_ext.pyx", line 1067, in bcolz.carray_ext.carray.__cinit__ (bcolz\carray_ext.c:14879)
  File "bcolz/carray_ext.pyx", line 1369, in bcolz.carray_ext.carray._read_meta (bcolz\carray_ext.c:19583)
FiFileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\laofi_000\\.rqalpha\\bundle\\adjusted_dividends.bcolz\\meta\\sizes'

**Comment by wh1100717** [comment]
@yu123ert 在2.2.x 版本里不再使用adjusted_dividends.bcolz 这个文件了。

你是不是有两个环境，一个用来更新bundle  另一个环境用来执行策略，更新bundle的是2.2.x 版本 但运行策略的是 2.1.x 版本？

**Comment by yu123ert** [comment]
已经可以了，多谢。但是似乎停牌函数无效了。
