### ISSUE TITLE
扩展API中加入on_trade, on_order回调

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha#122]
on_trade(trade)
on_order(order)
针对on_order回调的触发时机，建议在order状态变化或order的filled_quantity变化时候被触发。

**Comment by hzliu** [comment]
要不要直接开放 add_event_listener 接口出来？

**Comment by wh1100717** [comment]
@hzliu 我觉得 API 和事件接口适用不同的人群。目前来看，先提供针对 order 和 trade 的回调 API 可能更好一些。 事件这块我是觉得可能还要再讨论一下。 比如这个 trade 的回调API 虽然是绑定了 trade 事件，但实际上要等同样绑定了 trade 事件的 仓位和账户 完成计算以后才能执行。 而现在 这方面其实没有太多好的控制方案。

**Comment by wh1100717** [comment]
@handsomu @hzliu 经过讨论 暂时不添加相关的回调 API 如果想获取到订单回报或者成交回报可以使用其他方式，在没有完全讨论充分的情况下，API 层先慎重一些 不添加。
