### ISSUE TITLE
输出重复trades记录

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#125]
## 1. RQAlpha的版本
-2.2.0

## 2. Python的版本
-3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
回测输出的trades记录， 有的卖出会产生2条trades， 后面一条 的last_quantity和tax是0  但是有transcation_cost和commission
在内网运行  没法截图和复制。  回测久一点应该能复现

**Comment by hzliu** [comment]
能不能给个最简单的能重现的策略？

**Comment by dongyi** [comment]
@hzliu 我这边数据和代码拿不出来。 random 买卖应该也可以重现

**Comment by dongyi** [comment]
应该是我策略判断卖出的问题
