### ISSUE TITLE
windows下使用pycharm调试

### ISSUE THREAD

**Issue by kukuwa** [ricequant/rqalpha#127]
windows下rqalpha在scripts目录下，但是是rqalpha.exe文件 ，pycharm **select scripts**选项无法选择。

**Comment by wh1100717** [comment]
https://github.com/ricequant/rqalpha/issues/7

这个Issue 里面给出了如何相应的答案。

另外 我刚才自己测试了一下，在windows 环境下， python 2.7 的Scripts目录下 确实只有 exe 文件。 在 python 3.5 3.6下是有对应的 `rqalpha-script.py` 文件的。

如果使用python 2.7 的话 需要跟上上面给的issue 找出rqalpha 的入口文件所在路径。

**Comment by myz8110** [comment]
@wh1100717 我刚下载了最新版的PyCharm的community版本,画风和rqalpha文档描述的差异巨大,且我Python版本为3.6,rqalpha版本为最新版2.2.3,但找不到 对应的 Scripts 目录里面的 rqalpha-script.py文件
