### ISSUE TITLE
新升级到 2.2.2 出现 KeyError: 'ACCOUNT_TYPE.STOCK' 错误

### ISSUE THREAD

**Issue by Lsgo** [ricequant/rqalpha#130]
## 1. RQAlpha的版本
2.2.2
## 2. Python的版本
3.4
## 3. 是Windows/Linux/MacOS or others?
linux
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
运行脚本 
rqalpha run -rt p -fq 1m  -d /home/data/rqalpha -f  ./examples/rsi.py -sc 100000 -mc sys_stock_realtime.enabled True -mc sys_stock_realtime.fps 60
## 5. 您出现的错误堆栈日志信息
![image](https://cloud.githubusercontent.com/assets/8808422/25838200/89afbe6c-34c4-11e7-857a-37492de25225.png)

**Comment by wh1100717** [comment]
@hzliu 看错误日志 像是 persist 的时候存在一些问题

**Comment by Lsgo** [comment]
原来可以跑的策略现在跑不了
![image](https://cloud.githubusercontent.com/assets/8808422/25839374/ea8db4c8-34c9-11e7-91d5-a7e8f6f77851.png)

**Comment by hzliu** [comment]
portfolio的 persist 方法稍微改了一下，要跑起来的话最简单的办法是你把persist 中的那个 key 改成 STOCK

**Comment by wh1100717** [comment]
@Lsgo 这里确实修改了 persist 时候 key 的存储逻辑。对应的修改代码 https://github.com/ricequant/rqalpha/commit/dd4ffedab83c312976c91f39778ba5b4e24a181f#diff-77268b1b0d24b3a4ac63e5e9476f4eb6R46

主要是修改了persist 的key  比如原本是 `ACCOUNT_TYPE.STOCK` 现在是 `STOCK`  现在是基于 Enum 的 name 做来persist 的了。 所以原本persist 的key 用新的代码获取不到。

**Comment by wh1100717** [comment]
@Lsgo 这个不算是 bug 不过确实是个 breaking change

**Comment by wh1100717** [comment]
@Lsgo 第二个截图里面 plot 确实是个bug  已经在解决了

**Comment by Lsgo** [comment]
@hzliu  最简单的办法是你把persist 中的那个 key 改成 STOCK 
 ..这个是什么意思.应该怎么操作.我把文档过了一遍看不到这块的修改

**Comment by Lsgo** [comment]
..看了一下目录.瞬间懂了.谢谢大家
