### ISSUE TITLE
run_file 启动的策略不能按模拟运行.直接运行完成就退出了

### ISSUE THREAD

**Issue by Lsgo** [ricequant/rqalpha#132]
## 1. RQAlpha的版本
2.2.2
## 2. Python的版本
3.4
## 3. 是Windows/Linux/MacOS or others?
linux
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
执行的配置如下

```
from rqalpha import run_file

config = {
    "base": {
        "data_bundle_path": "/home/data/rqalpha",
        "start_date": "2016-06-01",
        "end_date": "2016-12-01",
        "securities": ['stock'],
        "stock_starting_cash": 100000,
        "benchmark": "000300.XSHG",
        "run-type": "p",
        # "frequency": "1d",
    },
    "extra": {
        "log_level": "verbose",
    },
    "mod": {
        "sys_analyser": {
            "enabled": True,
            # "output_file": "results/模拟结果.pkl",
            # "plot_save_file": "results/模拟结果.png",
        },
        "sys_stock_realtime": {
            "enabled": True,
            # "fps": "1",
        },
        # "sys_simulation": {
        #     "commission_multiplier": 0.01,
        #     "matching_type": "current_bar",
        #     "slippage": 0,
        # },
    }
}

strategy_file_path = "./examples/rsi.py"

run_file(strategy_file_path, config)
```
## 5. 您出现的错误堆栈日志信息

![image](https://cloud.githubusercontent.com/assets/8808422/25843681/aba58798-34da-11e7-9ba5-f7b99d91d6b2.png)

按照我理解. "run-type": "p", 的时候应该是一个运行的状态不应该能直接退出吧
因为我按照  `rqalpha run -rt p -fq 1m  -d /home/data/rqalpha -f  ./examples/rsi.py -sc 100000 -mc sys_stock_realtime.enabled True -mc sys_stock_realtime.fps 60`

以上脚本运行就是这状态

**Comment by wh1100717** [comment]
@Lsgo  除了命令行使用 `-`(横线) 以外 其他地方参数配置都使用 `_`(下划线)  

具体的参数可以参考 http://rqalpha.io/zh_CN/latest/intro/run_algorithm.html#id7

改成 `run_type` 试试

**Comment by Lsgo** [comment]
谢谢..是这个原因  .我是拷贝命令行上面的
