### ISSUE TITLE
安装好以后，提示 Module compiled against API version 0xb but this version of numpy is 0xa

### ISSUE THREAD

**Issue by joezou** [ricequant/rqalpha#134]
如下所示，提示numpy版本问题，但是我卸载numpy，重新安全还是不行，numpy版本1.12.1，是最新的。
<img width="806" alt="2017-05-14 5 38 33" src="https://cloud.githubusercontent.com/assets/6194888/26032706/31fe1a68-38cc-11e7-859f-40cb663f7af6.png">

**Comment by sunchenglong** [comment]
我也遇到了这个问题。。。 应该是系统上有一个比较旧版本的numpy，冲突了

**Comment by wh1100717** [comment]
@joezou 这个更新numpy 有解决吗？  我没有遇到你的这个问题。如果没解决的话，是否可以提供一个复现的详细环境？

**Comment by hongshan** [comment]
我也遇到了，已经解决了。直接卸载 bcolz，然后重装。我觉得是rqalpha的安装导致了 bcolz不可用，因为我在安装好 bcolz后，测试import  bcolz是正确的，当安装完rqahpha后就报这个错了

**Comment by wh1100717** [comment]
@hongshan RQAlpha 安装不会修改bcolz库.... 我猜测是你重新安装bcolz 导致依赖库版本更新了，比如numpy 才没问题的...

**Comment by hongshan** [comment]
@wh1100717  他的确是不会修改，可能跟你说的一样吧，刚才新建了一个虚拟环境重新测了一遍，果然还是一样的，安装完rqalpha卸载bcolz，重新安装bcolz就好了。但是这回运行回测又出了其他版本的问题，又折腾了一下。

**Comment by yssource** [comment]
@hongshan +1
遇到同样的问题. 你的方法, 对我有效.

**Comment by wh1100717** [comment]
@hongshan @yssource @sunchenglong @joezou 我又做了一些测试，好神奇... 按照如下方式产生了不同的结果

```bash
# 在没有 numpy 的情况下 安装bcolz 会报错
pip install bcolz -i https://pypi.tuna.tsinghua.edu.cn/simple
```

![image](https://cloud.githubusercontent.com/assets/1681360/26444234/12861fd2-416e-11e7-91ec-22473544a0f2.png)


```bash
# 先安装 numpy 然后再安装bcolz 的时候，有时候报错，有时候没问题
pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install bcolz -i https://pypi.tuna.tsinghua.edu.cn/simple
```
![image](https://cloud.githubusercontent.com/assets/1681360/26444184/e50680e2-416d-11e7-9c0c-045f33b16e62.png)

![image](https://cloud.githubusercontent.com/assets/1681360/26444212/fdb67462-416d-11e7-9a61-8010e64b740c.png)

```bash
# 不管哪种方式，卸载了bcolz 再安装bcolz的时候，完全没问题....
pip uninstall bcolz
pip install bcolz
```
最后.... 不用清华的源的话...  没问题...

```bash
pip install bcolz --no-cache-dir
```

![image](https://cloud.githubusercontent.com/assets/1681360/26444349/aa8f6e6e-416e-11e7-829d-35e194f54fe9.png)

**Comment by wh1100717** [comment]
N
