### ISSUE TITLE
使用数据查询相关函数出现RuntimeError: stack is empty错误

### ISSUE THREAD

**Issue by cfz87862529** [ricequant/rqalpha#136]
你好，我在使用数据查询相关函数(如all_instruments、industry等)时发生如下错误：

RuntimeError: stack is empty

我使用的是2.2.4版本，win7 64位旗舰版、python3.6.1。已经使用rqalpha update_bundle命令获取到了数据。期待您的回复。

**Comment by cfz87862529** [comment]
@wh1100717

**Comment by cfz87862529** [comment]
看了下源码，明白了：all_instruments不能直接调用，需要在上下文方法内调用。希望这个还是在文档里说清楚一下比较好。

**Comment by wh1100717** [comment]
@cfz87862529 所有的API 都需要在 `init` | `before_trading` | `handle_bar` 等的函数内使用。

**Comment by cfz87862529** [comment]
@wh1100717 明白了，我是在测试的时候误以为可以直接调用api返回结果。
