### ISSUE TITLE
get_fundamentals 能否提供一个简单的例子

### ISSUE THREAD

**Issue by Lsgo** [ricequant/rqalpha#137]
我自己有财务数据.想自己写一个 get_fundamentals 的mod 但是我不是标准的程序员.能否给一简单的案例参考一一下如何实现 get_fundamentals 和 query 方法

**Comment by wh1100717** [comment]
@Lsgo 很抱歉，这部分的代码目前没有开源的计划

**Comment by felixhwj36** [comment]
这个开源也太没诚意了

**Comment by zxcpp** [comment]
您好，您的邮件已收到，我会尽快给您回复。
祝您工作顺利，生活愉快！
