### ISSUE TITLE
context.portfolio.positions[stock].avg_price的疑问,望回答.

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#138]
## 3. 是Windows
比如,我重复买卖某只股票,第一次5元买入,清仓(请注意已清仓),一个月再次以8元买入,此时的context.portfolio.positions[stock].avg_price平均价是多少?

**Comment by wh1100717** [comment]
@myz8110 目前avg_price 定义为 建仓成本，也就是每次开仓会进行加权平均来计算。
如果已经清仓，则再次按照8元来开仓，avg_price 则是8元

**Comment by wh1100717** [comment]
No reply && Close this issue
