### ISSUE TITLE
能否在开源中加入demo的扩展API？

### ISSUE THREAD

**Issue by braindevices** [ricequant/rqalpha#139]
我们下载rqalpha一般就是因为online editor没法满足要求，需要用线下的IDE比如pycharm等编写和测试程序，然后再拷贝到ricequant运行。
但是我们很难想象哪一个策略不会进行基本的基本面筛选，而目前 `get_fundamentals`完全没有开放出来，导致根本无法在线下用IDE进行编写和测试。

`NameError: name 'get_fundamentals' is not defined`

我理解你们可能对提供线下财务数据有很多顾虑，但是我想能不能提供一些demo的假数据同时开放扩展API,这样就满足了我们使用线下IDE的愿望，同时你们也可以有更多时间考率如何对财务数据进行开放。

**Comment by wh1100717** [comment]
@braindevices 很抱歉，这种类型的API 只是对于数据读取的封装，和RQAlpha本身就是无关的。我理解你觉得很多人在这方面是有需求，甚至基本需求，但数据是有价值的，而这个价值关乎所有人的利益。你去问问同花顺就算想免费开放level 2数据，交易所是否允许？

RQAlpha 的核心在于整套的量化底层引擎，方便各种扩展，这已经大大超出了独立“数据”免费所带来的价值。我们是希望有越来越多基于RQAlpha的应用产生、并开源，但这是一个漫长的过程，希望能理解。

**Comment by myz8110** [comment]
tushare有数据，处理下再用sql保存，使用时再读取出来。

**Comment by braindevices** [comment]
@wh1100717 您可能完全理解错我的提议，我只是建议开放一个虚假的数据接口，便于在线下编程的时候进行调试，根本没有希望你们免费开放数据。比如您的Demo API一切语法都是相同的，但是数据全部是随机虚假生成的，甚至都不需要实际的securities,只要有一两个虚假股票代码，虚假的财报就可以，一切只是为了便于调试。

**Comment by wh1100717** [comment]
@braindevices 从个人的需求角度来说，这是有意义的，但是可能从框架的角度来说提供这部分的支持并没有太大的意义。正如 @myz8110 所说，您可以使用第三方库来获取您要的财务数据，并自定义对应的指标来实现您策略的需求，或者自己Mock假数据。

实在抱歉

**Comment by braindevices** [comment]
@wh1100717 我理解了，你们是拒绝考虑开放哪怕是mock data。 我当然可以使用tushare,但这种线下code明显会和线上code完全不同，哪里有什么调试便利性？ 目前rqalpha本来就不可能用来线下回测或者虚拟盘，我们编写这种没有get_fundamentals的线下版本更加没有任何意义。 结论就是rqalpaha这种开源实际上对非机构用户并没有任何意义。

**Comment by wh1100717** [comment]
@braindevices 我再说一遍，“RQAlpha 的核心在于整套的量化底层引擎，方便各种扩展，这已经大大超出了独立“数据”免费所带来的价值。我们是希望有越来越多基于RQAlpha的应用产生、并开源，但这是一个漫长的过程，希望能理解。”

他是底层引擎，任何业务相关的代码都不应该出现在RQAlpha中(目前还存在一些，比如is_st_stock 之类的API)，而应该以Mod的形式，成为RQAlpha的扩展。你如果真的觉得 get_fundamentals API 非常有用，欢迎封装开源版基于tushare的API扩展Mod。这样别人加载了你做的Mod 就可以使用这个API了。

RQAlpha 开源项目的意义是什么，这是很大的一个话题，如果不满足你的业务场景，那请寻找更合适的，没必要下什么结论。

**Comment by hzliu** [comment]
get_fundamentals 这样的 api 相当复杂，要提供一个完整的 mock api
需要的工作量还是挺大的，如果您有这方面需求的话欢迎实现之后提交 pull request

2017-05-18 16:19 GMT+08:00 Eric Wang <notifications@github.com>:
