### ISSUE TITLE
生成csv文件是乱码

### ISSUE THREAD

**Issue by StonePoe** [ricequant/rqalpha#14]
运行
`rqalpha run -f gold_cross.py -s 2014-01-01 -e 2016-01-01 -o result.csv`

生成的result.csv文件直接用excel打开是乱码

€cpandas.core.frame																									
DataFrame																									
"q)乹}q(U	_metadataq]qU_typqU	dataframeqU_dataqcpandas.core.internals"																									
BlockManager																									
"q	)乹"																									
(]q(cpandas.indexes.base																									
_new_Index																									
qcpandas.indexes.base																									
Index																									
q																									
}q(Udataqcnumpy.core.multiarray																									
_reconstruct																									
qcnumpy																									
ndarray																									
qK匲b嘡q(K?卌numpy																									
dtype																									
qUO8KK嘡q(KU|NNNJJK?tb塢q(UalphaqUannualized_returnsqUbenchmark_annualized_returnsqUbenchmark_daily_returnsqUbenchmark_total_returnsqUbetaqUcashqU																									
daily_returnsqU																									
"downside_riskqUinformation_rateqUmarket_valueq Umax_drawdownq!Upnlq""Uportfolio_valueq#U	positionsq$Usharpeq%Usortinoq&Utotal_commissionq'U"																									
"total_returnsq(U	total_taxq)Utracking_errorq*Utradesq+U"																									
volatilityq	etbUnameq-Nu哛q.cpandas.tseries.index																								
_new_DatetimeIndex																									
q/cpandas.tseries.index																									
DatetimeIndex																									
q0}q1(Utzq2NUfreqq3NhhhK匲b嘡q4(K??卙UM8KK嘡q5(KU<NNNJJK}(UnsKKKt唗b塗H抚B_E9篆E綮敊FC~)鐵??G釥R匞02缬G妞縃lw9I?蝄I																									
歜獻Y+鼯IF叽錔昿I4K?迋K3搑袺? Lo啬M緄YZM																									

...

而且我第一次跑那个buy_and_hold例子的时候csv文件还是正常的，这是什么问题？

**Comment by cedricporter** [comment]
我猜您是打开了 -o 输出的pickle文件了

**Comment by StonePoe** [comment]
我确认了一下，直接打开pickle和csv都是乱码，是不是-o不能生成csv文件？

**Comment by cedricporter** [comment]
`-o`是生成 pickle 文件，不是 csv

**Comment by StonePoe** [comment]
那么有生成csv的方法吗？

**Comment by cedricporter** [comment]
有一个比较挫的。 先跑完回测，用`-o`生成一个`out.pkl`，然后用`rqalpha report out.pkl out.csv`生成csv

**Comment by StonePoe** [comment]
好的谢谢了。。。其实也没什么必要一定要生成csv的。。。
