### ISSUE TITLE
context_vars指定的变量无法在init(context)方法中使用

### ISSUE THREAD

**Issue by cfz87862529** [ricequant/rqalpha#140]
context_vars指定的变量无法在init(context)方法中使用，在handle_bar(context, bar_dict)中没有问题。

## 1. RQAlpha的版本
2.2.4

## 2. Python的版本
3.6.1

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
None

## 5. 您出现的错误堆栈日志信息
None

**Comment by cedricporter** [comment]
因为使用 extra_vars 替换 context 的流程是在 init 后替换的，所以你在 init 内部是取到你赋值的值，但是 before_trading, handle_bar, after_trading 里面取到的就是你传入的值。

**Comment by cfz87862529** [comment]
@cedricporter 为什么不放在init之前呢？

**Comment by cedricporter** [comment]
在 init 过程中执行 Python 代码不就又用代码的值覆盖掉了吗 ？

这里除非把初始值放在 init 外面才能解决问题了，

**Comment by wh1100717** [comment]
No reply && Close this issue
