### ISSUE TITLE
无法获取最新数据

### ISSUE THREAD

**Issue by ruanyl** [ricequant/rqalpha#142]
#### 1. RQAlpha的版本
2.2.5

#### 2. Python的版本
3.5.1

#### 3. 是Windows/Linux/MacOS or others?
MacOS

#### 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
正常运行`rqalpha update_bundle`，但是获取的最新数据只是2017.05.12号的，貌似数据源没有更新

**Comment by cfz87862529** [comment]
我也碰到这个问题，只能认为是更新的数据其实本身就不一定有到当前时间，只是最后更新时间。

**Comment by ruanyl** [comment]
应该是数据源更新延迟，今天已经能正常获取数据了
