### ISSUE TITLE
IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by quantiger** [ricequant/rqalpha#145]
windows 10 系统 anaconda2环境
rqalpha 2.2.4 使用正常
使用pip install rqalpha --upgrade 升级到2.2.5后，执行rqalpha update_bundle或是rqalpha run启动策略
出现上述错误。

![Uploading rqalpha_error_2.png…]()
![rqalpha_error_1](https://cloud.githubusercontent.com/assets/16666051/26393078/58bf8afc-409b-11e7-8ce8-8ef31197dd8f.png)

**Comment by quantiger** [comment]
![rqalpha_error_2](https://cloud.githubusercontent.com/assets/16666051/26393153/8588d17e-409b-11e7-8e52-31b41cf680b3.png)

**Comment by wh1100717** [comment]
这个确实是在下载的bundle的时候空间不足导致的，你之前在群里说空间都是够得... 这个就比较麻烦了...  你试着指定一下 bundle的路径试一下？  `rqalpha update_bundle -d 你指定的路径`  这种方式

**Comment by hzliu** [comment]
https://stackoverflow.com/questions/19283118/python-ioerror-errno-0-error-what-is-triggering-this-error-in-my-code

@quantiger 你试着将 colorma 降到 0.3.6 试试看

**Comment by wh1100717** [comment]
No reply && Close this issue
