### ISSUE TITLE
用户能否扩展自己的事件源分类呢?

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#146]
虽然多种方法能实现在策略代码中直接 import 调用 [实盘易自动打新](https://github.com/sinall/ShiPanE-Python-SDK/blob/master/shipane_sdk/client.py#L127) .  但是我更倾向于, **Mod** 的机制,

当我想 使用 [实盘易自动打新](https://github.com/sinall/ShiPanE-Python-SDK/blob/master/shipane_sdk/client.py#L127), 这个API 接口时, 发现 缺少对应的 事件源分类.

目前只有下面3个分类, 用户能否继承扩展自己的分类呢?
- SystemEvent
- MarketEvent
- OrderEvent

**Comment by wh1100717** [comment]
@yssource 打新相关的内容确实没有，不过关于如何在外部扩展事件源这里，我们还没有太多想法，非常感谢，我们内部先讨论一下 看看这里 如何改善，从而满足更多的扩展需求~~
