### ISSUE TITLE
文档错误：get_dividend()方法返回的类型是numpy.ndarray，而非pandas.DataFrame

### ISSUE THREAD

**Issue by cfz87862529** [ricequant/rqalpha#148]
文档错误：get_dividend()方法返回的类型是numpy.ndarray，而非pandas.DataFrame
## 1. RQAlpha的版本
2.2.5
## 2. Python的版本
3.6.1
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
None
## 5. 您出现的错误堆栈日志信息
None

**Comment by wh1100717** [comment]
@cfz87862529 非常感谢~~ 我们尽快更改文档，或者您提交一个PR来修复此问题。
