### ISSUE TITLE
实时行情没有处理缺失数据

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#149]
## 1. RQAlpha的版本
- 2.2.7

## 2. Python的版本
- 3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
https://github.com/ricequant/rqalpha/blob/master/rqalpha/mod/rqalpha_mod_sys_stock_realtime/redis_data_source.py#L35

如果实时行情server 某一个股票的价格缺失（比如今天停牌）那么这里就抛出异常退出了

**Comment by wh1100717** [comment]
@dongyi 这个只是个demo 示例 如果要完善的话 还有很多工作要做的
