### ISSUE TITLE
rqalpha开发时，源码怎么调试的

### ISSUE THREAD

**Issue by ethonchen** [ricequant/rqalpha#15]
改了一些东西，发现不起作用，debug发现跑到lib里面了。应该是运行的时候跑了安装好的rqalpha。

试了试直接调用 main，发现报错。。

`
Traceback (most recent call last):
  File "/opt/project/rqalpha/rqalpha/__main__.py", line 33, in <module>
    from . import StrategyExecutor
SystemError: Parent module '' not loaded, cannot perform relative import
`
请问这个怎么整

**Comment by cedricporter** [comment]
您好，您需要参考这样调试 #7

**Comment by ethonchen** [comment]
这样也不行，我是说怎么改了 rqalpha的代码，怎么让他生效。这样只会跑到 Library里面

**Comment by ethonchen** [comment]
不过后面找到一个办法。进到 site-packages/rqalpha-0.0.70-py3.5.egg 里面把源码 软连接到 rqalpha里面，可以改 源码生效

![image](https://cloud.githubusercontent.com/assets/3139756/18271584/78d47378-7465-11e6-9747-600dcc490179.png)

**Comment by cedricporter** [comment]
你可以先 `pip uninstall rqalpha` 然后 `pip install -e .`
