### ISSUE TITLE
建议，增加成本价，保本价、过户费的计算

### ISSUE THREAD

**Issue by zhaohuiyingxue** [ricequant/rqalpha#155]
1、现有功能包括网站上，貌似没有成本价和保本价的信息，虽然positions里有平均价，但没有加入交易费用的计算。
2、交易费用未考虑股票沪市的过户费

**Comment by handsomu** [comment]
目前的平均开仓价、持仓价等价格信息全部都没有考虑费用。这是我们的规则，短期内应该不会变动。
有关过户经手费的问题，我们会尽快加入进来，非常感谢您的反馈！

**Comment by Cuizi7** [comment]
暂不打算加入成本价，保本价、过户费的计算。
