### ISSUE TITLE
什么时候可以支持两融账户（融资融券账户）模拟交易呢？

### ISSUE THREAD

**Issue by leevi2010** [ricequant/rqalpha#156]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by wh1100717** [comment]
@leevi2010 融资融券这块的逻辑目前没有相关的计划，涉及的内容还是很多的。 不过我们有一个简易版本，允许做空， http://rqalpha.io/zh_CN/latest/intro/run_algorithm.html#mod-option   `- - short-stock` :	[sys_risk]允许股票卖空

区别在于 不像融资融券，有相应的成本计算。short-stock 存储就是可以仓位为负，但是对于回测的话 应该也够用了。
