### ISSUE TITLE
卖出小于1手的情况

### ISSUE THREAD

**Issue by xiaofeifei218** [ricequant/rqalpha#157]
## 1. RQAlpha的版本
2.2.7
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
问题比较简单，ALPHA策略中由于分红送股，导致持仓数小于1手，这些零散的持仓无法凑整也无法卖出，在计算调仓中非常消耗计算。

**Comment by wh1100717** [comment]
@xiaofeifei218 这个问题很赞~~  貌似确实没有做这方面的判断。 @handsomu 有时间看看这个issue ~~

**Comment by hzliu** [comment]
order_target_percent 和 order_target_value 对这种情况都有判断

**Comment by cedricporter** [comment]
如 @hzliu 说的，order_target_percent  或 order_target_value  设为 0，就会自动将可卖仓位全部卖掉。就不会导致「零散的持仓无法凑整也无法卖出」。
