### ISSUE TITLE
上交所股票交易加入经手费计算

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha#161]
上交所（.XSHG）的合约
合约类别为 CS, LOF, ETF 在回测以及PT的时候费用加入经手费计算。该费率性质与印花税类似，为强制征收，用户不能进行设置
费率参考 http://www.sse.com.cn/services/tradingservice/charge/ssecharge/

股票：按照成交金额 0.00487% 买卖双向收取
ETF, LOF：按照成交金额 0.0045% 买卖双向收取

需要注意，债券ETF以及货币基金不收取经手费。
因为目前并没有更详细的二级品种分类，所以只能将内容hard code在代码里了。

债券ETF列表 参考 http://www.sse.com.cn/assortment/fund/etf/list/
货币基金列表 参考 http://www.sse.com.cn/assortment/fund/tcurrencyfund/home/

**Comment by Cuizi7** [comment]
暂不打算加入经手费计算。
