### ISSUE TITLE
模拟交易模式下不能用自己的扩展数据源

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#162]
## 1. RQAlpha的版本
- 2.2.7

## 2. Python的版本
- 3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
- 用了自己的模块  初始化的时候， set_data_source了，然后在模拟交易的时候， 发现系统用的是RedisDataSource，就没法用我的数据源获取历史数据了

**Comment by wh1100717** [comment]
@dongyi 你是说用了 [rqalpha_mod_sys_stock_realtime](https://github.com/ricequant/rqalpha/blob/master/rqalpha/mod/rqalpha_mod_sys_stock_realtime/README.rst) Mod 进行模拟交易吗？

这个 Mod 只是一个demo  你既然自己封装了实时数据data_source  那按照这个Mod 进行仿写一个 使用自己的数据源的即可。

**Comment by dongyi** [comment]
@wh1100717 对，按你说的方法搞定了
