### ISSUE TITLE
求助问题：股票账户在没有交易的情况下现金突然增加了很多

### ISSUE THREAD

**Issue by wanhanwan** [ricequant/rqalpha#163]
![default](https://user-images.githubusercontent.com/10461249/27273092-10b89ae0-5500-11e7-93fb-f139f91b3f5c.png)

在回测结束之后加载股票账户的结果，发现在2017-3-15日现金账户突然增加了两万多。
而且在交易清单中，2017-3-14和2017-3-15日没有任何交易记录。请问这是一个bug吗，还是有某些规则能够突然增加现金账户的现金？
RQAlpha版本：2.2.7
Python版本：3.6.1
Windows平台

提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Cuizi7** [comment]
有可能持仓的股票产生了分红，分红会直接加到现金中。

**Comment by wanhanwan** [comment]
@Cuizi7 
![default](https://user-images.githubusercontent.com/10461249/27273831-49f1be56-5503-11e7-944a-70808db5de21.png)

我查了股票账户的分红情况，那几天都没有分红的事件。

**Comment by hzliu** [comment]
检查一下持仓，一个可能是持有的合约到期或股票退市

2017-06-19 15:24 GMT+08:00 wanhanwan <notifications@github.com>:
