### ISSUE TITLE
mac osx下安装rqalpha后执行数据下载问题

### ISSUE THREAD

**Issue by eru1030** [ricequant/rqalpha#168]
安装好后，在terminal下执行rqalpha update_bundle，提示：--bash： rqalpha：command not found。

我在网上看到有的文章提到这个信息：我认为就是rqalpha命令的配置文件，请问要是什么原因导致找不到这个命令的？如问题不够清晰，请指出，谢谢
Usage: rqalpha [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose
  --help         Show this message and exit.

Commands:
  examples       generate example strategies to target folder
  plot           draw result DataFrame
  run            run strategy from file
  update_bundle  update data bundle, download if not found

**Comment by wh1100717** [comment]
你是通过参照 http://rqalpha.io/zh_CN/latest/intro/install.html 文档安装的吗？ 是否在虚拟环境安装的？  如果找不到rqalpha 命令，基本上是你安装的环境和你执行命令的python环境不同，或者安装失败导致。 安装的过程中是否有报错信息？ 

请提供更多的信息，以方便其他人帮你排查问题。

**Comment by wh1100717** [comment]
No reply && Close
