### ISSUE TITLE
rqalpha在ubuntu和osx上运行没用--plot指令但是却生成了结果图

### ISSUE THREAD

**Issue by StonePoe** [ricequant/rqalpha#17]
我在ubuntu16.04上跑  rqalpha run -f multi_rsi.py -s 2014-01-01 -e 2016-01-01 -o result.pkl， 结果自己跑出个图出来。在os x上运行也有同样的问题。

**Comment by cedricporter** [comment]
如果不需要图，请使用 `--no-plot`
