### ISSUE TITLE
请问为什么使用python setup.py安装就出错？

### ISSUE THREAD

**Issue by ohaiyofei** [ricequant/rqalpha#173]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by wh1100717** [comment]
因为 setup.py 不是用来直接用 python 来执行的安装脚本文件.....  你如果想要安装 rqalpha， 请参考文档 http://rqalpha.readthedocs.io/

如果你需要本地安装 请使用 `pip install .`
