### ISSUE TITLE
rqalpha/data/adjust.py复权函数bug

### ISSUE THREAD

**Issue by sein-tao** [ricequant/rqalpha#174]
rqalpha 3.0.2
In file `rqalpha/data/adjust.py`， function `adjust_bars`  have no check on the shape of bars
when len(bars) == 0, assignment of `start_date` and `end_date` would lead to index error.

Fix: add check of shape
```
 def adjust_bars(bars, ex_factors, fields, adjust_type, adjust_orig):
-    if ex_factors is None:
+    if ex_factors is None or len(bars) == 0:
         return bars if fields is None else bars[fields]
```

bug是在回测中发现的。估计是在股票上市的第一天的`before_trading`中调用`history_bars`时产生的，没有做仔细的确认。因为Fix很简单，就直接改了。

**Comment by hzliu** [comment]
多谢，这个在 develop 分支已经修改了
