### ISSUE TITLE
RQAlpha 当前 Universe 在 tick 级别策略中的逻辑 bug。

### ISSUE THREAD

**Issue by Cuizi7** [ricequant/rqalpha#175]
RQAlpha 当前 tick 逻辑如下：

> 策略 Universe 中的合约会触发 tick 事件，tick 事件一方面触发合约最新价格变化，另一方面触发 handle_tick。

在此逻辑下，若策略的持仓中有未订阅的合约，则该合约对应持仓的 holding_pnl，total_value 等不会动态更新，导致策略持仓、账户等计算错误。

可行的解决办法：
1.  将 Universe 拆分，在 rqalpha 层和策略层维护两个 universe，rqalpha 层的 universe 是用户 universe 以及持仓合约的并集。该方案不会改变现有 universe 的概念和逻辑，但会影响性能，且比较丑陋。
2. 更改 universe 逻辑，发生交易时自动帮策略订阅合约，且策略不可取消订阅当前持仓的合约。该方案可能会导致老策略的运行结果与之前相比发生变化，但逻辑上比较合理。

**Comment by handsomu** [comment]
需要在 update_universe 以及 unsubscribe 的时候针对期货合约做检验。如果当前仓位中包含的合约存在被取消订阅行情的可能，则取消订阅行情这一操作无效，并且需要在日志中输出warning

**Comment by Cuizi7** [comment]
已修复
