### ISSUE TITLE
接入自有行情数据后，无法下单

### ISSUE THREAD

**Issue by shuizuo** [ricequant/rqalpha#178]
## 1. RQAlpha的版本
Current Version:  (3, 0, 2)
## 2. Python的版本
Python 2.7.13 |Continuum Analytics, Inc.| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
## 3. 是Windows/Linux/MacOS or others?
Windows 10
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
开了一个mod，用于接入自有行情数据
核心代码：

# -*- coding: utf-8 -*-

import six
from datetime import date
from dateutil.relativedelta import relativedelta
from rqalpha.data.base_data_source import BaseDataSource
import pandas as pd

class LocalDataSource(BaseDataSource):

    csv_df = None

    def __init__(self, path):
        LocalDataSource.csv_df = self.read_cvs_as_df("C:/Users/AA/Desktop/stock.csv")
        super(LocalDataSource, self).__init__(path)

    @staticmethod
    def read_cvs_as_df(csv_path):
        data = pd.read_csv(csv_path, delimiter=',', index_col='index', encoding='utf-8')
        data['date'] = pd.to_datetime(data['date'], format='%Y%m%d')
        return data

    @staticmethod
    def get_bar_data_from_df(code, start, end):
        code_df = LocalDataSource.csv_df.loc[[code]]
        code_df.set_index('date', inplace=True)
        code_df.sort_index(inplace=True)
        code_period_df = code_df.loc[pd.to_datetime(start): pd.to_datetime(end)]
        code_period_df.reset_index(inplace=True)
        print "---------------get_bar_data_from_df start--------------"
        print code_period_df
        print "---------------get_bar_data_from_df end----------------"
        return code_period_df

    @staticmethod
    def get_local_bar_data(instrument, start_dt, end_dt):
        order_book_id = instrument.order_book_id
        code = order_book_id.replace("XSHE", "SZ").replace("XSHG", "SH")
        print code
        return LocalDataSource.get_bar_data_from_df(code, start=start_dt.strftime('%Y-%m-%d'),
                                                    end=end_dt.strftime('%Y-%m-%d'))

    def get_bar(self, instrument, dt, frequency):
        if frequency != '1d':
            return super(LocalDataSource, self).get_bar(instrument, dt, frequency)

        bar_data = self.get_local_bar_data(instrument, dt, dt)

        if bar_data is None or bar_data.empty:
            return super(LocalDataSource, self).get_bar(instrument, dt, frequency)
        else:
            print "----------------get bar start-------------"
            print bar_data.iloc[0].to_dict()
            print "----------------get bar end---------------"
            return bar_data.iloc[0].to_dict()

    def history_bars(self, instrument, bar_count, frequency, fields, dt,
                     skip_suspended=True, include_now=False,
                     adjust_type='pre', adjust_orig=None):
        if frequency != '1d' or not skip_suspended:
            return super(LocalDataSource, self).history_bars(instrument, bar_count, frequency, fields, dt,
                                                             skip_suspended)

        start_dt_loc = self.get_trading_calendar().get_loc(
            dt.replace(hour=0, minute=0, second=0, microsecond=0)) - bar_count + 1
        start_dt = self.get_trading_calendar()[start_dt_loc]

        bar_data = self.get_local_bar_data(instrument, start_dt, dt)

        if bar_data is None or bar_data.empty:
            return super(LocalDataSource, self).history_bars(instrument, bar_count, frequency, fields, dt,
                                                             skip_suspended)
        else:
            if isinstance(fields, six.string_types):
                fields = [fields]
            fields = [field for field in fields if field in bar_data.columns]
            return bar_data[fields].as_matrix()

    def available_data_range(self, frequency):
        return date(2005, 1, 1), date.today() - relativedelta(days=1)

之后，运行买入持有策略：
 %%rqalpha -s 20170320 -e 20170605 -p -bm 000731.XSHE --account stock 1000000

def init(context):

    logger.info("init")
    context.s1 = "002439.XSHE"
    update_universe(context.s1)
    context.fired = False
    
    
def handle_bar(context, bar_dict):

    if not context.fired:
        cur_position = context.portfolio.positions[context.s1].quantity
        print cur_position# 为0
        shares = context.portfolio.cash/bar_dict[context.s1].close
        print shares
        order_percent(context.s1, 1)
        cur_position = context.portfolio.positions[context.s1].quantity
        print cur_position# 为0
        shares = context.portfolio.cash/bar_dict[context.s1].close
        print shares
        context.fired = True
## 5. 您出现的错误堆栈日志信息
运行结果：
![_20170803103103](https://user-images.githubusercontent.com/10682147/28903413-49bd5114-7837-11e7-98f8-7d4bb83b4b2f.png)
并且输出异常信息：
2017-03-20 WARN 订单被拒单: [000731.XSHE] 已涨停。

当我不激活mod的时候，即不使用自有行情数据的时候，运行正常：
![image](https://user-images.githubusercontent.com/10682147/28914834-af2bb49a-786f-11e7-8717-6338159cf1d1.png)

**Comment by shuizuo** [comment]
解决了是自身的数据问题

**Comment by mozartAlpha** [comment]
@shuizuo 你好,请问有联系方式吗?能请教下吗?谢谢!

**Comment by shuizuo** [comment]
@mozartAlpha 抱歉，很可能帮助不到你，这部分工作是在去年我实习的时候做的，已经有大概一年的时间没有接触了，所以对这方面的知识已经忘记了，抱歉

**Comment by mozartAlpha** [comment]
@shuizuo 好的,谢谢!
