### ISSUE TITLE
请问是否回测考虑了涨停买不进跌停卖不出的情况？

### ISSUE THREAD

**Issue by allenjame** [ricequant/rqalpha#18]

**Comment by wh1100717** [comment]
是的，RQAlpha 在这方面做了限制，当下单时 security 处于 涨停或者跌停的情况下，market_order 会直接拒单，limit_order 会一直挂单，直到不再是涨跌停的时候才可能会买入。

当然，您如果希望能够买入/卖出，也可以关闭对应的功能，设置 validator.bar_limit 为False 即可。具体的参数配置请参考 [RQAlpha 参数配置](http://rqalpha.readthedocs.io/zh_CN/latest/api/config.html)
