### ISSUE TITLE
净值计算的问题

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#183]
## 1. RQAlpha的版本
- 3.0.2

## 2. Python的版本
- 3.6

## 3. 是Windows/Linux/MacOS or others?
- windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
请问下最后输出结果的portfolio.csv里的  static_unit_net_value  是不是理论上就等于前一天的unit_net_value？
      如果是的话，发现有一些误差，可能是因为 rqalpha_mod_sys_analyser/mod.py里
             对static_unit_net_value和unit_net_value调用_safe_convert保留小数位数不同造成的吗？
                  如果是这样：
                        static_unit_net_value的误差会导致daily_returns有误差，然后因为max_drawdown里的指数运算会把max_drawdown的误差变的很大

我跑了一个回测，有一段时间的净值从3.4跌倒2.3，最后max_drawdown算出来只有16%，如果我直接把unit_net_value.shift(1) 赋给static_unit_net_value,  算出来就和直观上一样了

**Comment by hzliu** [comment]
daily returns 的计算并不受 _safe_convert 的影响

**Comment by dongyi** [comment]
@hzliu static_unit_net_value 是不是前一天的unit_net_value呢？为啥我最后的portfolio.csv里有不小的差距

**Comment by Cuizi7** [comment]
static_unit_net_value 应该等于前一天结算后的 unit_net_value。
@dongyi 在我测试的策略中 static_unit_net_value 确实与前一日结算后的 unit_net_value 是相同的。您可否把能够复现的测试代码贴一下。

**Comment by dongyi** [comment]
@Cuizi7 我代码在内网拿不出来, 我自己替换了priceBoard 和DataSource, 为啥会造成前后两天的static_unit_net_value 和unit_net_value有误差呢...奇怪

**Comment by Cuizi7** [comment]
您使用默认的priceBoard  和 DataSource 可以复现吗？

**Comment by dongyi** [comment]
@Cuizi7 应该是我的priceboard的问题
