### ISSUE TITLE
请问当天的data bundle何时才能够升级获取？

### ISSUE THREAD

**Issue by wanhanwan** [ricequant/rqalpha#184]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.2
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha update_bundle
## 5. 您出现的错误堆栈日志信息
您好，我在2017年8月9日的19点在命令行里运行update_bundle命令，但是仍然只能获取到前一天(2017.8.8)的数据，请问当日(2017.8.9)的data bundle何时才能下载到呢？谢谢!

**Comment by zjuguxi** [comment]
每天的Bundle在19:20左右生成，你在19点取不到当天数据是正常的，晚一点就可以了
