### ISSUE TITLE
使用ProcessPoolExecutor进行参数调优，为何启动的很多python进程总是休息？

### ISSUE THREAD

**Issue by wuxin1030** [ricequant/rqalpha#191]
## 1. RQAlpha的版本
3.x
## 2. Python的版本
3.5
## 3. 是Windows/Linux/MacOS or others?
win0
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
命令行下 执行参数调优的py文件，看到顺利启动了多个python进程，cpu满载运行。但是过一回之后，这些python进程就“休息”了，必须在主进程的窗口按回车，才能刺激多个python进程再度活跃。

似乎是被挂起了，优先级不够吗？必须要界面给输入才能提高优先级？

**Comment by hzliu** [comment]
这个看起来是你鼠标选中了文字？windows 上是这样的，选中后进程被暂停
