### ISSUE TITLE
rqalpha的小问题

### ISSUE THREAD

**Issue by shihangwen** [ricequant/rqalpha#193]
新装了这个第三方库，想做一个测试，结果在运行的时候，出现了这个错误。请问如何解决？
![image](https://user-images.githubusercontent.com/13978535/30631748-f97039ae-9e17-11e7-9eb1-3c9bf55303a4.png)

**Comment by zsluedem** [comment]
`--account stock 100000`改为`--stock-starting-cash 100000`

**Comment by Cuizi7** [comment]
麻烦更新一下 rqalpha 的版本
