### ISSUE TITLE
执行rqalpha update_bundle之后运行策略出错

### ISSUE THREAD

**Issue by mepwang** [ricequant/rqalpha#197]
RQAlpha的版本: 最新的3.0.6
Python的版本: python 3.5
Ubuntu 16.04，已经apt update && apt upgrade
我是使用virtualenv建立的python，
虚拟环境使用pip list -o查看并使用pip install -U将所有过时python包更新到最新
包括rqalpha、bcolz等依赖的其他包
有时在执行rqalpha update_bundle之后，在完全正常没有报错的情况下，
查看~/.rqalpha/bundle目录，里面只有funds.bcolz和futures.bcolz以及instruments.pk。
不出意外，在执行股票相关的策略的时候出错了（找不到某些文件）
我用手工的方式将rqbundle文件下载并解压到bundle目录之后策略能够正常运行
请问这种情况可能是什么原因导致的？怎么解决呢？

**Comment by ruizengalways** [comment]
请问下载哪里手工下载bundle呢，我运行update_bundle 指令，程序只给我下载了funds.bcolz，请问能否把手动下载的地址给我下，我网上找了好久也没找到

**Comment by hzliu** [comment]
@mepwang 如果可以重现的话你 strace 看看是什么原因吧

**Comment by cedricporter** [comment]
https://github.com/ricequant/rqalpha/blob/7941921e851e10f536d7f3ae3ba376df775c06a1/rqalpha/main.py#L131-L175

update_bundle 的代码如上，就是下载压缩包、删除原文件夹和解压。如果您自己的手工可以解压成功的话，那可能是 python 解压的时候遇到了问题，导致部分文件解压失败了。

**Comment by cedricporter** [comment]
no resp & close
