### ISSUE TITLE
Anaconda全面更新至pyqt5，当前plot选项不能输出图了，是否可以跟进更新版本

### ISSUE THREAD

**Issue by princelai** [ricequant/rqalpha#20]
>     from PyQt4 import QtCore, QtGui
>     ImportError: cannot import name 'QtCore'

因为qt,pyqt,matplotlib,spyder这些都更新了，已经没有qt4，所以出现了问题

**Comment by cedricporter** [comment]
您好，您可以升级一下 matplotlib 试试
