### ISSUE TITLE
请问如何引入并使用自己编写的其他模块？

### ISSUE THREAD

**Issue by stiger104** [ricequant/rqalpha#208]
比如，我想在自己的算法模块中使用TensorFlow，并且想存储经过训练的神经网络参数，这块逻辑非常复杂，需要单独编写一个模块，又可以在主流程中使用，可能的做法是什么？

**Comment by hzliu** [comment]
把这个模块做成一个包，安装到 rqalpha 的运行环境中去。和引用tensorflow 一样引入就可以了
