### ISSUE TITLE
No module named 'rqalpha.mod.simulation'

### ISSUE THREAD

**Issue by lizhi2013** [ricequant/rqalpha#209]
如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
rqalpha version 
3.0.6
## 2. Python的版本
Python 3.5.3
## 3. 是Windows/Linux/MacOS or others?
官方的镜像

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
执行
%rqalpha -s 20100101 -e 20170505 -p -bm 000001.XSHG --account stock 100000
最简单的例子的时候提示 No module named 'rqalpha.mod.simulation'

**Comment by hzliu** [comment]
删除 ~/.rqalpha/config.yml ~/.rqalpha/mod_config.yml
