### ISSUE TITLE
日线数据能获得更长历史吗？

### ISSUE THREAD

**Issue by Chinese-Xu** [ricequant/rqalpha#21]
或者是否可以开放本地数据缓存结果，这样会有人做出本地数据导入导出工具的。

**Comment by Chinese-Xu** [comment]
试了下，数据是动态加载的。所以是否可以命令方式补充指定区间的历史数据呢?

**Comment by Chinese-Xu** [comment]
最早从2005年开始吗？是否能进一步提供从1997年开始的数据呢？记得涨停板就是从那个时候开始的。

**Comment by Chinese-Xu** [comment]
最早从2005年开始吗？是否能进一步提供从1997年开始的数据呢？记得涨停板就是从那个时候开始的。

**Comment by harvey1993** [comment]
没错的话，从Ricequant一开始的时候就是05年的数据，如果要提供更长时间的数据，应该需要和公司发一下邮件~

**Comment by akulatatama** [comment]
是的，目前我们只提供05年开始的数据。
