### ISSUE TITLE
update_bundle 11月6日不能更新11月3日的数据

### ISSUE THREAD

**Issue by fndjjx** [ricequant/rqalpha#210]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
Current Version:  (3, 0, 6)
## 2. Python的版本
Python 3.6.0
## 3. 是Windows/Linux/MacOS or others?
Ubuntu 12.04
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
date
Mon Nov  6 09:27:56 CST 2017

rqalpha update_bundle
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171106.tar.bz2 ...
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171105.tar.bz2 ...
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171104.tar.bz2 ...
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171103.tar.bz2 ...
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171102.tar.bz2 ...
下载中 ...  [####################################]  100%

**Comment by hzliu** [comment]
现在应该已经 fix
