### ISSUE TITLE
In OSX, local strategy code seems not support UTF-8 encoding.

### ISSUE THREAD

**Issue by ceruleanacg** [ricequant/rqalpha#213]
## 1. RQAlpha的版本
3.0.6

## 2. Python的版本
2.7

## 3. 是Windows/Linux/MacOS or others?
OSX

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
I have statement of encoding:   
![image](https://user-images.githubusercontent.com/4054687/32531920-130232bc-c48a-11e7-891a-93a68d9e4f9f.png)
And set my pycharm file encoding as:   
![image](https://user-images.githubusercontent.com/4054687/32531934-2fab76f8-c48a-11e7-8448-b1f9ad32c68f.png)

## 5. 您出现的错误堆栈日志信息
![image](https://user-images.githubusercontent.com/4054687/32531922-194da58e-c48a-11e7-8254-ba7d450e759a.png)

**Comment by ceruleanacg** [comment]
But if I do not have statement of coding=utf-8, there will be like this:
![image](https://user-images.githubusercontent.com/4054687/32531989-5c4fe6a8-c48a-11e7-93cc-5740617fcdf3.png)

**Comment by cedricporter** [comment]
可以升级到 python 3 ，兼容性会好些，就没有这些问题了。

Python 2.7 will not be maintained past 2020. https://pythonclock.org/
