### ISSUE TITLE
rqalpha如何编写自己的data bundle

### ISSUE THREAD

**Issue by StonePoe** [ricequant/rqalpha#22]
之前有个问题的回答是data_accesser 但是能不能提供一个详细的自定义数据源的教程？

**Comment by hetykai** [comment]
支持

**Comment by hzliu** [comment]
新版本会有相应的接口定义

**Comment by wh1100717** [comment]
Deprecated Issue https://github.com/ricequant/rqalpha/issues/35 相关的文档会尽快写的......
