### ISSUE TITLE
rqALPHA 3.0 win7, in "mod.py", we need removed line 223,235 "df['date'] = pd.to_datetime(df['date'])", otherwise there is error about "C long".

### ISSUE THREAD

**Issue by gaoyunhua** [ricequant/rqalpha#222]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by cedricporter** [comment]
duplicate with #221
