### ISSUE TITLE
安装成功后使用数据api报错

### ISSUE THREAD

**Issue by xin1314** [ricequant/rqalpha#228]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
from rqalpha.api import *
# 选择日期
trading_dates = get_trading_dates(start_date='2016-01-01',end_date='20170801')

## 5. 您出现的错误堆栈日志信息
![image](https://user-images.githubusercontent.com/18678883/34100685-393cb5c0-e41e-11e7-8e3a-1bc6dfbdabdd.png)

**Comment by cedricporter** [comment]
这些API是「回测」专用的API，不是在 notebook 里面用的。
