### ISSUE TITLE
run_weekly遇到节假日应该自动延后一天吗

### ISSUE THREAD

**Issue by dongyi** [ricequant/rqalpha#235]
## 1. RQAlpha的版本

`3.0.9`

## 2. Python的版本

`3.6`

## 3. 是Windows/Linux/MacOS or others?

`windows`

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

比如我用run_weekly(trading_day=1)  但是周一是节假日  没有交易, 那么是否应该延后到下一个交易日交易呢

**Comment by hzliu** [comment]
默认是会的。
