### ISSUE TITLE
当策略里有错误而导致 rqalpha 异常退出的时候, 终端返回码应该是非 0

### ISSUE THREAD

**Issue by xieyuheng** [ricequant/rqalpha#236]
目前有异常的时候 终端返回码也是 0

**Comment by xieyuheng** [comment]
另外, rqalpha.run_code(code, config) 好像也吧所有异常都接住了 ?
这样不方便用 pytest 写测试

**Comment by Cuizi7** [comment]
策略的异常确实会被框架接住。策略抛出错误应该不属于框架本身运行异常，所以终端返回码是0。
框架在接住异常后会将策略运行状态及异常对象通过 tear_down 方法传递给 mod，可以通过 mod 获知以上信息。

**Comment by xieyuheng** [comment]
需要写一个 mod 才能用 pytest 做测试 ?
run_code 和 run_func 可以加个参数, 让它不接住策略异常吗 ?

**Comment by xieyuheng** [comment]
rqalpha/tests/api/ 里的测试是怎么跑的 ?
不是在这个路径里运行 pytest 吧 ?

**Comment by xieyuheng** [comment]
看到 rqalpha/test.py 了
别自己写测试框架了, 用 pytest 吧

另外目前跑 test.py 的时候,
内存溢出, 可能是因为 lru_cache.

**Comment by xieyuheng** [comment]
我测试的时候 assert run_code(code, config) 就行了
