### ISSUE TITLE
请问RQ何时能加入做空机制呢？？？

### ISSUE THREAD

**Issue by lzhw520110** [ricequant/rqalpha#24]
看了源码貌似还不支持做空，请问RQ何时能加入做空机制呢？？？

**Comment by akulatatama** [comment]
我们在做一些新的开发和迭代，很有可能下周发布以后会把github这里的代码做相关更新加入做空

**Comment by wh1100717** [comment]
Deprecated Issue https://github.com/ricequant/rqalpha/issues/3
