### ISSUE TITLE
run_func 模式运行代码无法输出常规日志

### ISSUE THREAD

**Issue by AdaJass** [ricequant/rqalpha#240]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by AdaJass** [comment]
[2018-01-12 14:10:19.119086] DEBUG: basic_system_log:
{'base': {'accounts': {'FUTURE': 1000000.0},
          'benchmark': None,
          'data_bundle_path': 'C:\\Users\\星瀚资本/.rqalpha\\bundle',
          'end_date': datetime.date(2016, 12, 1),
          'frequency': '1d',
          'init_positions': [],
          'margin_multiplier': 1,
          'matching_type': 'current_bar',
          'persist': False,
          'persist_mode': PERSIST_MODE.REAL_TIME,
          'resume_mode': False,
          'run_type': RUN_TYPE.BACKTEST,
          'source_code': None,
          'start_date': datetime.date(2016, 6, 1),
          'strategy_file': './AE_strategy.py'},
 'extra': {'context_vars': None,
           'dividend_reinvestment': False,
           'enable_profiler': False,
           'force_run_init_when_pt_resume': False,
           'is_hold': False,
           'locale': 'zh_Hans_CN',
           'log_level': 'verbose',
           'logger': [],
           'user_log_disabled': False,
           'user_system_log_disabled': True},
 'mod': {'sys_accounts': {'enabled': True},
         'sys_analyser': {'enabled': True, 'plot': True},
         'sys_funcat': {'enabled': False},
         'sys_progress': {'enabled': True},
         'sys_risk': {'enabled': True},
         'sys_simulation': {'enabled': True},
         'sys_stock_realtime': {'enabled': False}},
 'validator': {'cash_return_by_stock_delisted': False, 'close_amount': True},
 'version': '0.1.6',
 'whitelist': ['base', 'extra', 'validator', 'mod']}

**Comment by AdaJass** [comment]
更正一点，run_func运行代码是log可以显示，但是在before_trading 和 init 处的log无法显示，只有在handle_bar里才正常

**Comment by Cuizi7** [comment]
您好，麻烦附上一份可以浮现问题的代码。

**Comment by AdaJass** [comment]
sorry, but i all forgot about that bug, and hope you the same.
