### ISSUE TITLE
你好！我想问一个关于股票实盘的问题

### ISSUE THREAD

**Issue by Zhangjiahong001** [ricequant/rqalpha#246]
貌似rqalpha想在不能实现股票的实盘施因为没有券商的交易接口是吗？假如我能自己实现股票实盘交易部分，那么在rqalpha上能实现股票的实盘吗

**Comment by hzliu** [comment]
可以的

2018-01-24 23:02 GMT+08:00 Zhangjiahong001 <notifications@github.com>:

**Comment by Zhangjiahong001** [comment]
你实现了吗？我的思路是把easytrader集成上去。你可以讲讲具体怎么实现吗？或者我加你qq，跟你请教一下

**Comment by Cuizi7** [comment]
欢迎了解下我们的终端产品，提供了基于 rqalpha 的完全合规的实盘。
https://www.ricequant.com/solution/hedge_fund
