### ISSUE TITLE
你好，rqalpha在回测的时候考虑配股的信息了吗

### ISSUE THREAD

**Issue by mountainStill** [ricequant/rqalpha#247]
我发现bundle下的几个bcolz中并没有配股的信息。当我们用rqalpha回测到某只股票配股的那一天，rqalpha是怎么处理的？

**Comment by hzliu** [comment]
目前没有处理配股

2018-01-25 11:51 GMT+08:00 mountainStill <notifications@github.com>:

**Comment by mountainStill** [comment]
是因为影响不大才不处理配股吗？
