### ISSUE TITLE
data bundle能否每日收盘后一定时间内自动更新

### ISSUE THREAD

**Issue by easunlu** [ricequant/rqalpha#25]
注意到目前的data bundle更新时间好像不固定，能否于当日收盘后固定时间自动更新data bundle，谢谢！ @cedricporter @hzliu

**Comment by hzliu** [comment]
现在其实是每天晚上10点有更新的，但是上传到七牛的过程中可能出错，还在看原因。

2016-11-07 13:40 GMT+08:00 easunlu <notifications@github.com>:

**Comment by easunlu** [comment]
谢谢，上传失败有邮件通知就好了，非常感谢！ @hzliu
