### ISSUE TITLE
API get_trading_calendar接口问题

### ISSUE THREAD

**Issue by semigodking** [ricequant/rqalpha#257]
数据接口的get_trading_calendar()函数不接受任何参数。这个函数应该要接受一个参数，可以是order_book_id也可以是exchange，这样才能反回相应市场的正确的交易时间啊。

**Comment by hzliu** [comment]
多谢建议，如果需要同时交易多个市场的话确实是需要多个交易日历的；对多市场的支持需要改动的地方还是比较多的

**Comment by Cuizi7** [comment]
4.0.0 版本 data_proxy.get_trading_calendar 已加入 trading_calendar_type 参数，且 DataSource.get_trading_calendar 改为返回交易日历字典，可以通过实现该方法以实现多交易日历（多市场、场内和银行间）的支持。
