### ISSUE TITLE
commission设置有问题

### ISSUE THREAD

**Issue by billcheuk** [ricequant/rqalpha#26]
在init函数中使用：
    context.commission = 0.02
最终的commission是2%，并不是0.02%。

commission.py文件中没有对设定的值再除100

**Comment by wh1100717** [comment]
@billcheuk 在新版本中，commission不再可以直接设置，具体的手续费会根据对应的合约/股票来获取默认值。换言之， 每个合约的commission标准都可能是不同的。

如果需要自行设置commission的话，可以通过commission_multiplier来进行设置，相当于对所有合约的commission计算进行scale up/down. 具体的文档请参考  [RQAlpha 参数配置](http://rqalpha.readthedocs.io/zh_CN/latest/api/config.html)
