### ISSUE TITLE
关于is_suspended函数的疑问

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#263]
is_suspended - 全天停牌判断
参数: | order_book_id (str) – 某只股票的代码或股票代码，可传入单只股票的order_book_id, symbolcount (int) – 回溯获取的数据个数。默认为当前能够获取到的最近的数据
-- | --
count为1时 bool; count>1时 pandas.DataFrame

请问count为1时 bool返回的数据是当日的数据,还是前一天的数据?比如我在handle_bar加入此函数,它返回的数据是当天的还是前一天的??

**Comment by hzliu** [comment]
count不为1时，返回的是一个数组，包含最近的 count 个交易日的停牌情况

在 2018年3月6日 下午11:22，myz8110 <notifications@github.com>写道：
