### ISSUE TITLE
关于回测系统的一些疑问

### ISSUE THREAD

**Issue by szhu3210** [ricequant/rqalpha#266]
1. 回测支持选股吗？

2. 是不是只能在init的时候定义若干股票代码（股票池）？

3. 是否支持全市场选股的策略呢？

4. 有没有回测时间限制（比如回测从A股诞生以来的所有时间段）？

谢谢！

**Comment by Cuizi7** [comment]
1. 支持选股
2. 股票池可以动态更新
3. 支持全市场选股的策略
4. 回测的时间限制取决于回测所使用的历史行情数据的时间范围
