### ISSUE TITLE
better-exceptions包问题

### ISSUE THREAD

**Issue by lunaMoon1010** [ricequant/rqalpha#267]
_PS C:\Windows\system32> pip install better-exceptions
安装rqalpha需要better-exceptions包，这个包很新，在https://www.lfd.uci.edu/~gohlke/pythonlibs/
这个网站没有编译的使用的包。请问在windows环境下如何安装这个包使得rqalpha能够安装成功

**Comment by Cuizi7** [comment]
使用 pip install better-exceptions==0.1.8 有什么问题吗？

**Comment by site-packages** [comment]
[man] @lunaMoon1010 不妨看看文档， https://github.com/Qix-/better-exceptions  的 Usage 部分

**Comment by Cuizi7** [comment]
No response, closed.
