### ISSUE TITLE
扩展mod账户及API无法调用

### ISSUE THREAD

**Issue by lw5885799** [ricequant/rqalpha#269]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
linux
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
`  config = {
    "base": {
      "start_date": "2016-06-01",
      "end_date": "2016-12-01",
      "frequency": "1d",
      "accounts": {
          "huobi": 555555
      }
    },
    "extra": {
      "log_level": "verbose",
    },
    "mod": {
      "sys_analyser": {
        "enabled": True,
        "plot": True
      }
    }
  }`
## 5. 您出现的错误堆栈日志信息
huobi是我自建MOD的账户，由于对整个系统不太熟悉，mod中API和account,position都已改写
`env.get_instance().get_account_model(CUSTOM_ACCOUNT_TYPE.HUOBI.name)` 
可以获取相关对象
运行时报错
`ERROR:root:Exception calling application: module 'better_exceptions' has no attribute 'format_traceback'
Traceback (most recent call last):
  File "/home/rq/PycharmProjects/rqalpha/rqalpha/utils/arg_checker.py", line 400, in api_rule_check_wrapper
    return func(*args, **kwargs)
  File "/home/rq/PycharmProjects/rqalpha/rqalpha/mod/rqalpha_mod_sys_accounts/api/api_stock.py", line 309, in order_percent
    account = Environment.get_instance().portfolio.accounts[DEFAULT_ACCOUNT_TYPE.STOCK.name]
KeyError: 'STOCK'`
按照自建的MOD来说，应该是调用自定义mod下的api，而实际运行时调用了api_stock
请教这里如何修改？如需详细配置信息请邮箱联系，感谢！

**Comment by Cuizi7** [comment]
麻烦简述下您是如何在mod中注册api的，欢迎附上相关代码。

**Comment by lw5885799** [comment]
@Cuizi7 已经解决了

**Comment by leewi9** [comment]
@lw5885799 怎么解决的，说一下啊。别就说个已经解决了啊
