### ISSUE TITLE
get_fundamentals

### ISSUE THREAD

**Issue by Elegent** [ricequant/rqalpha#27]
数据查询相关函数

get_fundamentals - 查询财务数据

get_fundamentals(query, entry_date=None, interval=None, report_quarter=True)
获取历史财务数据表格。目前支持中国市场超过400个指标，具体请参考财务数据文档。目前仅支持中国市场。需要注意，一次查询过多股票的财务数据会导致系统运行缓慢。

**Comment by Elegent** [comment]
没有财务数据查询函数支持呢

**Comment by hzliu** [comment]
是的，如果需要财务数据，您可以在ricequant网站上进行回测。

2016-11-13 1:27 GMT+08:00 Elegent <notifications@github.com>:

**Comment by 9590** [comment]
连这都没有，看来用处不大了

**Comment by wh1100717** [comment]
Deprecated issue https://github.com/ricequant/rqalpha/issues/34
