### ISSUE TITLE
开箱即用虚拟机root密码是什么

### ISSUE THREAD

**Issue by dduyk** [ricequant/rqalpha#270]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Cuizi7** [comment]
rqalpha
