### ISSUE TITLE
https://www.ricequant.com  网站的源代码可以开源吗？

### ISSUE THREAD

**Issue by jackiilong** [ricequant/rqalpha#271]
网站做得挺不错的

**Comment by morya** [comment]
那个应该是通过shpinx自动生成加readthedocs.org的主题。

**Comment by superyyrrzz** [comment]
可以自己参照文档编译：https://github.com/ricequant/rqalpha/tree/master/docs

**Comment by jackiilong** [comment]
不好意思，写错网址了，是这个网站https://www.ricequant.com/

**Comment by superyyrrzz** [comment]
个人觉得不太可能。。。人家一商业公司得靠这网站业务赚钱，工具能开源，网站不行

**Comment by hzliu** [comment]
不会开源。
