### ISSUE TITLE
中文显示问题： 部分中文显示正常 + 部分中文乱码 问题

### ISSUE THREAD

**Issue by pythonwood** [ricequant/rqalpha#272]
![screenshot - 2018 03 21 - 09 50 58](https://user-images.githubusercontent.com/5157880/37691621-19abad38-2cee-11e8-8c90-c0760a1753e5.png)

本人有一定python基础

之前已解决了不能显示中文问题，但现在这个问题难解！！！

修改过rqalpha/mod/rqalpha_mod_sys_analyser/plot.py换过字体，还是不行

**Comment by pythonwood** [comment]
## 修bug方法：修改gettext函数保证返回是unicode

原来的
 58 def gettext(message):
 59     trans_txt = localization.trans.gettext(message)
 60     return to_utf8(trans_txt)
改成
 58 def gettext(message):
 59     trans_txt = localization.trans.gettext(message)
 60     return unicode(to_utf8(trans_txt))
成功解决！

## 分析
我看到文件头部写的from rqalpha.utils.py2 import to_utf8， 好笑啊，之前兼容py2所用的to_uft8函数恰恰是导致我这次问题原因。 

## 结论
本身给Matplotlib函数传参最好就是用unicode字参，但因为贵司代码里专门为"兼容py2" 而对传入函数utf8化处理而引入这个bug。 

## 建议
将相关代码回滚或修改，对Matplotlib函数传参统一用unicode而不是utf8。（这在py2/py3都是推荐做法）
 

![screenshot - 2018 03 21 - 11 00 48](https://user-images.githubusercontent.com/5157880/37692958-2357a59a-2cf7-11e8-8ee8-446ba94abe66.png)

**Comment by hzliu** [comment]
@cedricporter

**Comment by mar-heaven** [comment]
目前支持python3+
