### ISSUE TITLE
装了virtualBox一键开箱即用虚拟机，运行第一示例报错“非法指令,核心已转储”

### ISSUE THREAD

**Issue by thathappiness** [ricequant/rqalpha#276]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.4.5
## 3. 是Windows/Linux/MacOS or others?
Linux/ubantu
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha run -f ~/examples/buy_and_hold.py -s 2017-01-01 -e 2017-12-31 --account stock 100000 --benchmark 000300.XSHG --plot
## 5. 您出现的错误堆栈日志信息
非法指令 (核心已转储)

**Comment by uhyuuhyu** [comment]
pip uninstall bcolz
pip install bcolz==1.1.2
CPU不支持预编译的bcolz中使用的指令集导致，重新编译bcolz即可
