### ISSUE TITLE
为什么会有next_bar, 却没有current_bar_open?

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#277]
在现实中的量化交易逻辑通常如下:
1. 利用历史数据来选股, 如果是以日为单位的话, 就是以昨天以前的数据来进行选股.

2. 在当前的bar中以当前的价格来成交,   在当前bar中可以知道的价格有开盘价和收盘价， 例如，如果是以日("1d")以上周期为单位的话,  开盘价成交表示是在早晨开盘时运行策略并以当时的市场价格成交，如果是以收盘价成交表示是在下午收盘前运行策略成交。

在运行策略的时候, 是不可能知道下一个bar的价格的, 甚至连下一个bar都不一定存在.

但是rqalpha却存在matching_type为"next_bar"的情况, 当然在回测中大部分情况下都可以获取未来的数据, 但是如果是运行昨天的回测呢, 它是没有next bar数据的。
如果把rqalpha接到实际的交易中, next_bar的运行逻辑是怎样的?

而且rqalpha当matching_type为"current_bar"时以收盘价成交而不是以开盘价成交也与其它回测框架不太一致。

**Comment by Cuizi7** [comment]
首先要理解 撮合 的概念。
使用 rqalpha 运行回测的时候，rqalpha 使用了内置的撮合引擎对策略发的单进行撮合，代替了真是交易中交易所的工作，所以实盘中不存在 matching_type 这个可配置项。
为了模拟真是市场中发生的事、测试策略在不同市场反应中的表现同时保持框架逻辑的简洁，rqa设计了不同的撮合类型（matching_type）。其中 next_bar 是指在下一个bar开盘时对当前市场上（当前策略发出的）所有挂单进行撮合。这种撮合类型一定程度上模拟了真是市场上订单的成交偏离下单时间及价格的情况。这种撮合类型不一定适用于所有策略所有粒度的回测。

**Comment by tiandian** [comment]
`其中 next_bar 是指在下一个bar开盘时对当前市场上（当前策略发出的）所有挂单进行撮合。`
-----
为什么要在下一个bar开盘时对当前市场上（当前策略发出的）所有挂单进行撮合? 
而不是当前bar开盘时对以前市场上所有挂单进行撮合?
在现实中大家都是希望尽快买卖的, 当前价格/当前的股票基本面/和股票以前的情况是已知的, 所以在当前成交是可控制的。
不希望等到明天再成交的， 如果明天价格大涨或大跌还会去成交吗? 明天股票要退市会去交吗?明天的价格和消息都未知, 很少有人会把行动放到明天.

但我试过几个其它的量化平台，它们基本上都没有使用next_bar的情况,  但都有开盘成交的情况。

所以@Cuizi7  你的解释无法令人满意呀。

**Comment by Cuizi7** [comment]
不同的回测粒度以及撮合类型适用于不同的撮合类型，你的上述策略可以使用更细粒度的回测或者其他撮合类型或者信号模式。

**Comment by tiandian** [comment]
您的解释是无法令人满意,  这个问题和更细粒度的回测没有关系.

我在上面列举了使用next_bar的缺点,  我认为它相对于使用当前bar开盘价来说只有缺点，没有优点。

能否请您解释一下使用next_bar开盘价 相对于 使用当前bar开盘价的优点在哪里?

**Comment by XavierOwen** [comment]
emmm分钟回测应该就可以避免这个问题？分钟回测的撮合机制是不是当前分钟级时间结束后撮合呢？

**Comment by handsomu** [comment]
@tiandian 设置 next bar 撮合方式出发点就是当前 bar 的高开低收策略全都知道，可以做出很多不符合实际的操作。为了避免这一点，引入了 next bar 的撮合方式。跟您说的不矛盾，您说的是 使用截止到昨天收盘的数据 采用当前 bar 开盘价进行撮合；而我们这里是 使用截止到今天收盘的数据 采用下一 bar 开盘进行撮合。整体后移了一个交易日而已。您在设置的时候选择回测截至日期前移一天即可。
@XavierOwen 分钟回测撮合机制 也分 current bar  next bar，是一样的，前者是当前分钟线收盘价，后者是下一分钟线开盘价。
另外， rqalpha 也提供了按照指定价格成交的方式， 可以在文档里面查到，这样可以使用您认为合适的价格直接作为成交价。
在 mod  sys_simulation 里面，设置 signal=True 即可
