### ISSUE TITLE
is_hold配置参数有什么用?

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#279]
is_hold配置参数在RQAlpha 文档 和Ricequant 文档都没有介绍, 
@run_when_strategy_not_hold中用到了它,
请问其用途是什么, 什么时候会将is_hold设为True?

**Comment by Cuizi7** [comment]
hold 是 策略对一种状态，该状态下策略的一些逻辑不能执行，如 handle_bar， handle_tick，发单撤单等。用于模拟交易或实盘中因为某些原因需要暂停策略。

**Comment by tiandian** [comment]
知道了, 谢谢!
