### ISSUE TITLE
数据可能存在错误

### ISSUE THREAD

**Issue by easunlu** [ricequant/rqalpha#28]
代码000540.XSHE，时间2015-03-31~2015-04-01，价格变动一倍多。可能是除权等出现的问题。
该数据问题不是个例。

**Comment by cedricporter** [comment]
检查数据，是一个月翻倍的。您可以打开同花顺看看K线，该股票在牛市的时候，那段时间确实暴涨，一个月翻倍了

**Comment by easunlu** [comment]
我这边查看数据发现的是：
000540.XSHE
2015-03-31 OHLC：5.29, 5.65, 5.07, 5.53
2015-04-01 OHLC：14.19, 14.46, 12.98, 13.74
中间间隔一天

**Comment by easunlu** [comment]
我今天更新了下bundle，又好了。不过之前确实是我所述的样子。
