### ISSUE TITLE
分钟级别的回测事件源不准确

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#281]
在simulation_event_source.py的_get_stock_trading_minutes函数中会生成分钟级别的事件源:
```
def _get_stock_trading_minutes(trading_date):
        trading_minutes = set()
        current_dt = datetime.datetime.combine(trading_date, datetime.time(9, 31))
        am_end_dt = current_dt.replace(hour=11, minute=30)
        pm_start_dt = current_dt.replace(hour=13, minute=1)
        pm_end_dt = current_dt.replace(hour=15, minute=0)
...
```
从上面的代码可以看出有如下问题:
1. 上午9:30分未生成事件, 而是在9:31分才开始生成事件, 这是不准确的,  其实在9:25分时已经生成了开盘价, 9:30分已经具备生成事件的所有信息, 应该生成交易事件.

2. 上午11:30分生成了事件, 但上午11:30分已经停牌了, 此时不应再发送事件了.

3. 同理, 下午13:00分应生成事件, 而15:00分不应生成事件.

**Comment by Cuizi7** [comment]
rqa 的分钟 bar 数据反应的是过去的一分钟内市场的变动情况，所以在第一分钟走完的时候推送出来是合理的。

**Comment by hzliu** [comment]
目前并没有对集合竞价部分做处理，所以第一个分钟线是在9:31分

**Comment by tiandian** [comment]
@Cuizi7 你的解释不能让人满意呀, 在9:31和15:00发送一个交易信号是没法成交的. 
  和next_bar问题一样, 为什么非要等下一个bar处理呀.
ricequant 其它方面都很不错, 这一点和其它量化平台(MindGo/joinquant/...)不同，且不合理呀.
我看过joinquant的设定是比较严谨的, 和现实紧密切合:
https://joinquant.cn/api?f=home&m=memu#%E5%9B%9E%E6%B5%8B%E8%BF%87%E7%A8%8B

**Comment by Cuizi7** [comment]
bar数据（以及国内市场的tick数据）中不包含逐笔数据，所以不可能（大多数情况下也没有必要）实现和交易所一致的连续竞价撮合逻辑。回测框架中只能对撮合的过程进行抽象，抽象出的模型可能有多种，next_bar 就是其中一种，不一定适用于所有回测，可以不使用。

rqalpha提供了多种撮合类型可供使用。
如果有其他合理的撮合类型欢迎提pr～
