### ISSUE TITLE
rqalpha中关于Portfolio和Account的逻辑问题。

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#282]
在rqalpha中, 一个Portfolio下可以包含多个Account,  而且可以包含多个不同类型的帐号, 也就是可以同时包含股票和期货等不同类型的帐号,  这样不但导致设计复杂，而且逻辑上与现实是不符合的.

在现实中, 股票和期货是在不同的地方开户的,  他们交易的官方机构不同，交易对象的性质不同, 把他们放在一起做投资组合进行量化分析是没有意义的。

股票有很多因子, 做量化分析就是希望能找出合理的量化策略来运用这些因子进行买卖, 但如果把股票的因子运行在期货上是行不通的.

在同一个策略里同时购买股票和期货是没有任何意义的,  进行回测也是没有意义的, 找不出有任何有价值的因子或策略.

如果有一种量化策略,  可以同时从股票和期货(或其它交易对象)中选择交易对象, 且具有现实意义, 希望能提供相关的事例, 以便帮助用户更好的理解rqalpha的设计思路, 谢谢!

**Comment by Cuizi7** [comment]
将期货期权和现货组合在一起进行套利或者对冲是很普遍的做法吧。

**Comment by tiandian** [comment]
理解了, 若考虑到对冲这种情况, rqalpha这样设计是很必要的,  又学到了一些新的东西, 非常感谢!
