### ISSUE TITLE
关于stock_account.py->_handle_dividend_book_closure函数中的dividend_reinvestment

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#286]
在stock_account.py中的197行:_handle_dividend_book_closure函数中的通过dividend_reinvestment模拟股票分红再投资, 其代码如下:

```
    def _handle_dividend_book_closure(self, trading_date):
...
            if config.extra.dividend_reinvestment:
                last_price = Environment.get_instance().data_proxy.get_bar(order_book_id, trading_date).close
                shares = position.quantity * dividend_per_share / last_price
                position._quantity += shares
            else:
...

```
在上述代码中, 分红再投资是用未复权的**昨日收盘**价购来买股票, 这是否不太准确的?
是否应该用今日的**昨收盘价**购买更准确?

**Comment by Cuizi7** [comment]
注意上述 trading_date 为 book_closure_date 即股权登记日，是除权除息日的上一个交易日。

**Comment by tiandian** [comment]
trading_date是股权登记日（昨天）, 也就是今天(除权除息日)的前一天.

举个例子:
假设股权登记日帐号情况如下:
1000股, 每股10元, 因此除权除息前总市值是1000*10=10000元

假设分红计划是: 每股分红1元.

那么按照当前rqalpha的计算方式, 到了今天(除权除息日):
总股数是 1000  + 1000*1/10 = 1100股,
除权价格是: 10-1 = 9元, 所以总市值只有1100*9 = 9900元, 导致除权除息后少了100元. 基本上是相当于市值缩水1%, 这个误差有些大呀.

**Comment by Cuizi7** [comment]
按照你说的使用trading_date的昨收也有同样的问题呀。
有更好的处理方式欢迎提出讨论～
