### ISSUE TITLE
安装提示pip.req错误

### ISSUE THREAD

**Issue by Lsgo** [ricequant/rqalpha#288]
安装或者更新rqalpha 提示错误
No modle name 'pip.req'

rqalpha 3.0.9
python 3.5
pip 10.0.0

https://leanote.com/api/file/getImage?fileId=5ad41180ab6441354a00096a

https://leanote.com/api/file/getImage?fileId=5ad41181ab6441354a00096b

**Comment by bopo** [comment]
pip 10.0.0 我也出这问题

**Comment by haibinyang** [comment]
将pip的版本降级为9.0.1版本可以解决问题
