### ISSUE TITLE
貌似下载的日线数据不准了。。。

### ISSUE THREAD

**Issue by haogefeifei** [ricequant/rqalpha#29]
```python
import os
import datetime
from rqalpha.data import LocalDataProxy

data_bundle_path = os.path.expanduser("~/.rqalpha")
data_proxy = LocalDataProxy(data_bundle_path)
day = datetime.date.today()
dates = data_proxy.history("600325.XSHG", day, 30, "1d", "close")

print dates
```

**Comment by haogefeifei** [comment]
2016-10-12    13.58
2016-10-13    13.70
2016-10-14    13.70
2016-10-17    13.30
2016-10-18    13.54
2016-10-19    13.50
2016-10-20    13.46
2016-10-21    13.36
2016-10-24    13.37
2016-10-25    13.35
2016-10-26    13.44
2016-10-27    13.35
2016-10-28    13.50
2016-10-31    13.22
2016-11-01    13.14
2016-11-02    12.89
2016-11-03    12.87
2016-11-04    12.95
2016-11-07    13.14
2016-11-08    13.10
2016-11-09    13.10
2016-11-10    13.10
2016-11-11    13.10
2016-11-14    13.26
2016-11-15    13.31
2016-11-16    13.29
2016-11-17    13.27
2016-11-18    13.26
2016-11-21    13.15
2016-11-22    13.15

**Comment by haogefeifei** [comment]
注意2016-11-04 ~ 2016-11-11.....

**Comment by hzliu** [comment]
这只股票11月9号到11号是停牌的，我们用停牌之前的数据进行了补齐。

2016-11-22 12:55 GMT+08:00 好个飞飞 <notifications@github.com>:

**Comment by haogefeifei** [comment]
![9a9c9f83-402e-4097-bd04-c0d23a04db95](https://cloud.githubusercontent.com/assets/5234670/20737292/b4880bbe-b6e6-11e6-882d-3cf94e0cce8d.jpg)补齐。。。。 这样算指标真的大丈夫？

**Comment by haogefeifei** [comment]
```python
    close = data_proxy.history("600325.XSHG", day, 30, "1d", "close")
    volume = data_proxy.history("600325.XSHG", day, 30, "1d", "volume")

    # 删除掉停牌的数据
    close = close.reindex(volume[volume.values != 0].index)
```

这样处理下好像可以了.... 我只是想从外部使用rqalpha提供的日线数据

**Comment by hzliu** [comment]
嗯，这样是可以的。我们在新版本中将会直接提供过滤停牌数据的选项。

2016-12-01 11:34 GMT+08:00 好个飞飞 <notifications@github.com>:

**Comment by haogefeifei** [comment]
新版本有什么计划吗。。？

**Comment by wh1100717** [comment]
@haogefeifei 新版本已经更新，能麻烦再试一下看看是否还有这个问题吗？

**Comment by haogefeifei** [comment]
我看看

**Comment by haogefeifei** [comment]
3.x代码变化挺大的，花了点时间消化更新的代码，已经不用自己剔除停牌数据了，外部使用日线数据的代码改了下

```python
import os
import datetime
from rqalpha.data.data_proxy import DataProxy
from rqalpha.data.base_data_source import BaseDataSource

data_bundle_path = os.path.expanduser("~/.rqalpha/bundle")
data_proxy = DataProxy(BaseDataSource(data_bundle_path))
day = datetime.date.today()
dates = data_proxy.history("600325.XSHG", 30, "1d", "close", day)

print(dates)
```

**Comment by haogefeifei** [comment]
但还是有点小问题的样子，比如执行如上代码取600325的日线，打印出来
```
2017-01-13    12.8699
```
这天的收盘价实际上应该是12.87

**Comment by wh1100717** [comment]
@haogefeifei 这个价格也算不上是小问题，因为考虑到复权数据  可能往前的价格会很小，所以两位小数容易产生较大的偏差，所以价格增加至4位，然后12.8699属于浮点数精度截取后的结果，不影响使用。

**Comment by wh1100717** [comment]
@haogefeifei 童鞋 我有给你发邮件 你有收到吗？

**Comment by haogefeifei** [comment]
@wh1100717 不好意思，才看到

**Comment by haogefeifei** [comment]
那这样的话数据就没什么问题了
