### ISSUE TITLE
pip 10.0.0的python setup.py install 报错

### ISSUE THREAD

**Issue by poloxue** [ricequant/rqalpha#291]
pip 10.0.0版本的setup.py安装报错。

from pip.req import parse_requirements 这句话会import error

找到的解决方案是
try:
    from pip.req import parse_requirements
except ImportError:
    from pip._internal.req import parse_requirements

**Comment by Lsgo** [comment]
这问题我碰到过.已经修复在pull requests 里.你可以用那个版本下载..还没有合并到主版本里面

**Comment by Cuizi7** [comment]
fixed in master branch
