### ISSUE TITLE
Error: no such option: --plot

### ISSUE THREAD

**Issue by hrtddpcx** [ricequant/rqalpha#296]
## 1. RQAlpha的版本
(rq) C:\Users\Peng>rqalpha version
Current Version:  (3, 0, 9)

## 2. Python的版本
(rq) C:\Users\Peng>python -V
Python 3.6.5 :: Anaconda, Inc.

## 3. 是Windows/Linux/MacOS or others?
WIN10

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
Pycharm环境，parameters输下面的报错，去掉--plot恢复正常
run -f C:\Users\Peng\OneDrive\Documents\rq\rq.py -s 2018-02-12 -e 2018-04-12 --account stock 1000000 --benchmark 000300.XSHG --plot

## 5. 您出现的错误堆栈日志信息
Error: no such option: --plot

Process finished with exit code 2

**Comment by hrtddpcx** [comment]
命令行下，加--plot，正常输出图形。
PyCharm下，仍然提示：Error: no such option: --plot

应该是主要参数在__main__.py里，而--plot在mod\rqalpha_mod_sys_analyser\__init__里所导致

怎么解决呢？

**Comment by tiandian** [comment]
不仅仅是--plot选项, 所有在扩展mod中增加的选项如--plot-save都无效.

根源在在__init__.py文件中的这个语句:
from rqalpha.__main__ import cli
这导致__main__.py文件被执行两次, 生成了两个cli变量, 一个在__init__.py中, 一个在__main__.py中, inject_mod_commands修改的是__init__.py中的cli, 而__main__.py运行时使用的是__main__.py中的cli.

有几个解决办法, 改动最小的解决办法是在__main__.py的entry_point函数中增加一句'from rqalpha import cli', 如下:

```
def entry_point():
    inject_mod_commands()
    from rqalpha import cli
    cli(obj={})
```

但这种方法这只是掩盖了代码上的问题,  要彻底解决问题还是需要重新组织__main__.py和__init__.py中的代码, 在入口语句前不要交叉引用。

**Comment by hrtddpcx** [comment]
改config搞定
