### ISSUE TITLE
关于api_base.py的subscribe函数

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#297]
api_base.py中subscribe的注释如下:

```
def subscribe(id_or_symbols):
    """
    订阅合约行情。该操作会导致合约池内合约的增加，从而影响handle_bar中处理bar数据的数量。

    需要注意，用户在初次编写策略时候需要首先订阅合约行情，否则handle_bar不会被触发。
    ....

```
关于该函数有两个问题:

1. 上面有这句话--"**需要注意，用户在初次编写策略时候需要首先订阅合约行情，否则handle_bar不会被触发**"是否有误,  因为无论是否订阅, 当策略加载后, handle_bar都会被调用, 这是在Strategy.py中处理的, 与是否subscribe无关。

2. subscribe/update_universe/unsubscribe的作用除了更新Environment的_universe成员外, 没有发现有其它实际用途, 与其相关的代码是否是遗留下来的无用代码?

**Comment by Cuizi7** [comment]
在 bar 级别的策略运行中，event_source 可能会根据策略订阅的合约选择性触发bar事件（如只订阅了 A 股就只触发 A 股对应交易时间的 bar，订阅了某些期货合约会触发夜盘等）。上边说的 handle_bar 不会被触发指的是某些时间段的bar不会被触发。
在 tick 级别的策略运行中，event_source  可能只会发出订阅了的合约的tick事件。发出所有tick会对性能造成极大浪费，同时也会增加策略判断的成本。

**Comment by andrewchenshx** [comment]
在文档的[策略例子](https://rqalpha.readthedocs.io/zh_CN/latest/intro/examples.html)中，有些（比如股指期货MACD日回测）在init中调用了subscribe，有些没有。如果确实要调用，建议在例子中都明确加上。

**Comment by hzliu** [comment]
日级别的都不需要调用subscribe
