### ISSUE TITLE
设置允许卖空时，参数类型出错

### ISSUE THREAD

**Issue by yu123ert** [ricequant/rqalpha#3]
![qq 20160805205441](https://cloud.githubusercontent.com/assets/1884623/17437200/eae20a64-5b4e-11e6-8e2d-ad1936feb000.png)

def init(context):
    context.short_selling_allowed = True

  File "d:\python\lib\site-packages\rqalpha\strategy.py", line 158, in execute
    init(strategy_context)
  File "examples/buy_and_hold.py", line 7, in init
    context.short_selling_allowed = True
TypeError: short_selling_allowed() takes 1 positional argument but 2 were given

在ricequant平台上策略代码测试可用

**Comment by cedricporter** [comment]
目前暂时还不支持卖空，后续会加上

**Comment by wh1100717** [comment]
无论是Ricequant，还是RQAlpha，都不再支持股票的做空API，因为本来就无法做空..... 而且这里面还涉及到做空成本计算和管理等虚拟出来的一些逻辑。 如果有类似的做空的需求，可以试着通过股票 +  股指 混合策略来实现。
