### ISSUE TITLE
create instrument by symbols

### ISSUE THREAD

**Issue by FrankMN** [ricequant/rqalpha#30]
看到文档中说到可以用symbol来创建instrument, 不一定需要知道code.XSHE这类的id
实际操作中，`instruments(['平安银行', '000024.XSHE'])`会报错：`ERROR: order_book_id 平安银行 not exists!`

**Comment by wh1100717** [comment]
@FrankMN 抱歉，之前的版本确实不支持symbol，新版本的RQAlpha 已经支持通过symbol 来查询instrument了。
