### ISSUE TITLE
建议将rqalpha.data包也做成可替换的mod

### ISSUE THREAD

**Issue by tiandian** [ricequant/rqalpha#302]
目前的rqalpha地rqalpha.data包是建立在.bcolz格式上的,  且rqalpha的设计不方便替换数据源,
而用户选股数据源来源方式多样, 可能直接来自于网络, 也可能是来自于关系数据库, 
建议将rqalpha.data包拆分为interface和mod两部分, 这样当用户使用其它格式的数据源时可以方便的替换.bcolz格式的数据源.

**Comment by Cuizi7** [comment]
rqalpha.interface.AbstractDataSource 封装了一系列框架和策略可能用到的数据api，可以通过实现这些api替换数据。
