### ISSUE TITLE
print函数咨询

### ISSUE THREAD

**Issue by hrtddpcx** [ricequant/rqalpha#303]
## 1. RQAlpha的版本
C:\Users\Peng>rqalpha version
Current Version:  (3, 0, 9)

print函数打印结果，都有一个日期+INFO前缀，怎么能去掉这个前缀？
2018-04-20 INFO ******

**Comment by Cuizi7** [comment]
rqalpha 将策略中的 print 替换为了 logger.info，以方便框架对日志的统一管理。
不想使用框架提供的日志管理的话可以尝试 pprint.pprint 或 six.print_ 等第三方库提供的函数。

**Comment by hrtddpcx** [comment]
能介绍一下怎么做到改写print的吗？看了logger.py和base.py，没看懂-_-#

**Comment by hrtddpcx** [comment]
想学习理解你们这个事件驱动框架，有没有什么书推荐？
