### ISSUE TITLE
什么时候能更新一下对pandas的支持

### ISSUE THREAD

**Issue by deepfuzzy** [ricequant/rqalpha#304]
现在好多常用包已经不支持0.21以下的版本了，各种冲突啊

**Comment by liuli1735** [comment]
这个问题都好久了，也没解决

**Comment by amy0li** [comment]
pandas更新了以后，rqalpha就用不了了，重装也不行

**Comment by zihaozhu93** [comment]
是啊，可能弃更了吧

**Comment by Cuizi7** [comment]
rqalpha 3.2.0 已移除对 pandas 版本上限的限制。可以使用最新版本的 pandas。
