### ISSUE TITLE
求助，macOS用SSH方法连接使用远程服务器上的rqalpha 无法绘图

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#313]
## 1. RQAlpha的版本
Current Version:  (3, 0, 9)
## 2. Python的版本
Python 3.6.4 |Anaconda, Inc.
## 3. 是Windows/Linux/MacOS or others?
MacOS终端ssh连接ubuntu16.04
## 4. 您出现的错误堆栈日志信息
<img width="717" alt="2018-05-08 6 22 24" src="https://user-images.githubusercontent.com/25770147/39752040-cec365e8-52ec-11e8-9305-f52cb78f27bd.png">
在mac上用ssh username@remotehost的方式连接了rqalpha server（Ubuntu16.04）
应用已经启动但是没有绘图也没有报错，也试过ssh -X的方式。同样的操作用ubuntu连接server再启动可以绘图成功，mac就是不行，没反应，求助各位大佬

**Comment by ronlym** [comment]
https://stackoverflow.com/questions/39622173/cant-run-ssh-x-on-macos-sierra 大概是这个原因吧。。

**Comment by ronlym** [comment]
但是还有一个情况，是我用ubuntu的虚拟机去连接rqalpha的server ssh -X 也绘制不出图像 用ubuntu物理机就可以，实在是不懂什么原因，不知道是matplotlib的问题还是rqalpha要怎样设置，没有什么日志输出，结果还是跟mac的截图一样，现在这个问题在困扰我

**Comment by poloxue** [comment]
可以把结果拿出来用rqalpha plot result.pkl去画图，ssh远程连接画图没用过。我都是直接装在mac上啊，如果无界面的linux上回测，把结果拿出来用rqalpha plot画图就行了。

**Comment by ronlym** [comment]
本意是想把rqalpha服务器化，考虑性能问题回测什么的就都在服务器上做了，所以用ssh去连服务器。不过这个问题暂时解决了，虚拟机防火墙关掉并且设置对服务器的DISPLAY变量就可以了，不然X文件传不过来，具体教程网上有的，暂时当一个解决办法吧。
