### ISSUE TITLE
安装时问题

### ISSUE THREAD

**Issue by tby1995** [ricequant/rqalpha#314]
你好：

利用pip 10.0.1 安装时出现以下问题

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      **File "C:\Users\boyu\AppData\Local\Temp\pip-install-1jwijk9p\rqalpha\setup.py", line 20, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'**

网上说此原因可能与 pip 10 更新有关， 可否将 setup.py", line 20  
 from pip.req import parse_requirements

改为
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements

**Comment by amy0li** [comment]
遇到同样问题，pip更新到最新了，最后怎么解决呢？

**Comment by ronlym** [comment]
pip降到10以下

**Comment by wuxin1030** [comment]
最方便的就是主动降级pip
python.exe -m pip install -U pip==9.0.3

**Comment by lw5885799** [comment]
遇到同样的问题 pip降到10以下的话  安装其他的库又会要求升级怎么破

**Comment by wooego** [comment]
降级pip到9.0.3安装成功后，再升级回10.0.1

**Comment by kid143** [comment]
现在pip官方把req移到_internal里面了，表示不对外开放了，简直日了狗。

**Comment by Cuizi7** [comment]
fixed in 3.0.10
