### ISSUE TITLE
小白提问，求帮解答

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#315]
首先自己对回测业务不是很熟悉，所以尽量避开业务在看源码。但注释确实有些少→_→
这里想问些应该比较基础的问题，希望能有人大佬帮解答一下。
Q1：instrument类和order类是什么关系啊，为什么instrument对象会有order对象例如order_book_id这样的属性，比如在[http://rqalpha.readthedocs.io/zh_CN/latest/development/data_source.html#tushare](url)中，实现抽象数据类时order_book_id = instrument.order_book_id这里没有懂..

**Comment by Cuizi7** [comment]
order_book_id 是交易资产（instrument）的唯一代码（可以理解成股票代码）。
instrument 是交易资产对象。
