### ISSUE TITLE
扩展数据源

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#317]
您好：
最近在学习使用rqalpha框架，**想使用自己定制的数据源**，按着http://rqalpha.readthedocs.io/zh_CN/latest/development/data_source.html#tushare中的内容：

- 继承了BaseDataSource并override了对应接口，实现了自己数据源的抽象类；

- 实现并加载了对应Mod；

按着http://rqalpha.readthedocs.io/zh_CN/latest/intro/tutorial.html#id3中的内容：

- 写了个test策略做测试

其中
![2018-05-14 6 56 39](https://user-images.githubusercontent.com/25770147/39993750-83591384-57a9-11e8-8bff-39f0465b7986.png)
将context.s1内容替换为了自己数据源中的symbol_code，e.g:000001.SZ，运行策略时报了下列错误
<img width="718" alt="2018-05-14 6 59 40" src="https://user-images.githubusercontent.com/25770147/39993757-8dc2a39e-57a9-11e8-8893-c93f2b6c30f0.png">
个人理解是000001.SZ这个股票代码不是预设好instrument类，

所以想请问我哪里理解有错误吗.. 如果想要扩展自有数据源，有哪些一定要改动的地方，或者有其他再详细一点教程可以参考吗，感谢了..

**Comment by ronlym** [comment]
没有，只实现了readthedocs上要求的内容，如果还有其他类似一定需要实现方法，希望能在文档上体现一下。

**Comment by ronlym** [comment]
但是f

**Comment by poloxue** [comment]
@ronlym 默认的股票合约代码都是以.XSHG或者.XSHE实现的，如果需要使用其他资产需要修改对应的获取合约代码的地方。

**Comment by ronlym** [comment]
@poloxue 好的谢谢，继续啃源码就是了

**Comment by liyangxie2019** [comment]
请教一下get_all_instruments应该如何实现，谢谢！
