### ISSUE TITLE
可以实时模拟交易吗？

### ISSUE THREAD

**Issue by FrankMN** [ricequant/rqalpha#32]
看到网站上可以实时模拟，看了一下开源的代码好像没发现实时模拟的功能。

**Comment by handsomu** [comment]
实时模拟功能目前并没有提供。目前开源的版本只支持日回测。因为实时模拟涉及到连接实时数据源，涉及到多个模块（不仅是RQAlpha）之间的交互（比如RQAlpha与Market data gateway）。目前单就开源的RQAlpha来说是做不到的。
