### ISSUE TITLE
为rqalpha.model模块下的类Instrument定义interface

### ISSUE THREAD

**Issue by HereticSK** [ricequant/rqalpha#321]
rqalpha是我目前看到结构最清晰、扩展最方便的框架，首先感谢米筐开源。

`AbstractDataSource.get_all_instruments`要求返回一个以`Instrument`为元素的list
```Python
class AbstractDataSource(object):

    def get_all_instruments(self):
        """
        获取所有Instrument。

        :return: list[:class:`~Instrument`]
        """
        raise NotImplementedError
```

而`rqalpha.model.instrument.Instrument`似乎没有定义清楚`Instrument`应该具有什么结构，但它又经常被rqalpha的其他模块引用。目前我看到在`InstrumentMixin`就出现了2处，假设了`Instrument`具有`order_book_id`和`symbol`两个属性：
```Python
class InstrumentMixin(object):
    def __init__(self, instruments):
        self._instruments = {i.order_book_id: i for i in instruments}
        self._sym_id_map = {i.symbol: k for k, i in six.iteritems(self._instruments)
                            # 过滤掉 CSI300, SSE50, CSI500, SSE180
                            if not i.order_book_id.endswith('INDX')}
        try:
            # FIXME
            # 沪深300 中证500 固定使用上证的
            for o in ['000300.XSHG', '000905.XSHG']:
                self._sym_id_map[self._instruments[o].symbol] = o
            # 上证180 及 上证180指数 两个symbol都指向 000010.XSHG
            self._sym_id_map[self._instruments['SSE180.INDX'].symbol] = '000010.XSHG'
        except KeyError:
            pass
```

这导致扩展自有数据源的时候经常因为`Instrument`的结构而产生`AttributeError`。[readthedocs](https://rqalpha.readthedocs.io/zh_CN/latest/development/data_source.html)上关于tushare的例子对此也没有提及。

因此希望能有一个关于Instrument的interface，以便扩展到A股和期货之外的数据

P.S. 在尝试扩展数据源的时候，个人觉得目前的框架还是有改善空间：
- 即使是`AbstractDataSource`，也还是提及了资产的具体逻辑，比如`get_yield_curve`是债券特有的，比如`history_bars`的signature涉及了停牌、复权类型等股票的具体逻辑。把这些放到具体的类下面是不是更好呢？
- 事件源实际使用的是`DataProxy`而不是`DataSource`，而`DataProxy`又加入了`InstrumentMixin`和`TradingDatesMixin`，这么隔了一层，有可能即使实现了`AbstractDataSource`也因为`DataProxy`的问题而报错

不知道维护者们是怎么考虑这两个问题的呢？我很乐意提交PR，如有兴趣可另开issue详细讨论。谢谢。

**Comment by Cuizi7** [comment]
Instrument 需要的字段现在已写成了 property 的形式，方便对接第三方数据源。
