### ISSUE TITLE
pip10安装出错

### ISSUE THREAD

**Issue by Laughtalk** [ricequant/rqalpha#322]
http://rqalpha.io/zh_CN/latest/intro/install.html
文档中描述的安装方法建议先更新pip
但是pip在升级到10.x之后，安装会报错没有pip.req包，因为这个包在9.x才有
所以建议文档修改一下，加入这个提示，防止错误
或者，修改代码来适应pip10

**Comment by zhangshoug** [comment]
我也遇到了，不过自己想办法解决了。https://blog.csdn.net/zhangshoug/article/details/80462395

**Comment by Cuizi7** [comment]
fixed in 3.0.10
