### ISSUE TITLE
RQAlpha中文字体问题

### ISSUE THREAD

**Issue by zhangshoug** [ricequant/rqalpha#323]
$ cat /etc/issue
Linux Mint 18.3 Sylvia \n \l
$ conda -V
conda 4.3.30
$ python -V
Python 3.6.2 :: Continuum Analytics, Inc.
$ rqalpha version
Current Version:  (3, 0, 9)
$ rqalpha plot result.pkl
[2018-05-26 16:47:15.972687] WARN: system_log: Missing Chinese fonts. Fallback to English.
linux默认中文安装，按说系统中有中文字体了。还出这个提示不知怎么弄.

**Comment by vincent4java** [comment]
`sudo mkdir /usr/share/fonts/chinese
cd /usr/share/fonts/chinese
sudo  wget https://static.ricequant.com/data/WenQuanYi%20Micro%20Hei.ttf
fc-cache -fv
fc-list
rm -rf ~/.cache/matplotlib
rm -rf ~/.fontconfig`

linux发行版可以参考
http://rqalpha.readthedocs.io/zh_CN/latest/intro/detail_install.html
