### ISSUE TITLE
有没有对接实时行情的代码？

### ISSUE THREAD

**Issue by jackiilong** [ricequant/rqalpha#324]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by jackiilong** [comment]
@Cuizi7   thanks for reply!
这个好像是把data load过来后。push给redis的，所以这个实时性是不是有点延迟

**Comment by jackiilong** [comment]
可以实时抓取yahoo或者新浪实时数据，然后push给redis，再push events吗？

**Comment by Cuizi7** [comment]
redis速度不是瓶颈。不过这只是个demo，数据质量、速度、稳定性都不能保证。
