### ISSUE TITLE
函数handle_bar没有执行。为什么呢

### ISSUE THREAD

**Issue by jackiilong** [ricequant/rqalpha#326]
rqalpha run -f ./rqalpha/examples/buy_and_hold.py -d ./rqalpha/bundle/ -s 2016-06-01 -e 2016-12-01 --account stock 100000 --benchmark 000300.XSHG --plot
运行这个策略时，函数handle_bar没有执行。为什么呢

**Comment by Cuizi7** [comment]
尝试在 handle_bar 中加入 print 进行调试，并加上参数 -l debug。

**Comment by jackiilong** [comment]
@Cuizi7 这个函数是怎么被调用的？

**Comment by Cuizi7** [comment]
可以尝试用单步调试等方法查看下rqa是如何运行的。
