### ISSUE TITLE
#1405cae BUG, env.get_universe()._set = set()

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#328]
[env.get_universe()](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/environment.py#L149) 拿到的就是 set, 所以 `set()._set` 这里是一个 bug 吧? 

[env.get_universe()._set = set()](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/core/strategy_universe.py#L47)

1405cae
clear the strategy universe before forced run init

**Comment by Cuizi7** [comment]
看起来是的，多谢

**Comment by yssource** [comment]
04fbd26 fix typo
