### ISSUE TITLE
sector() 获取板块出错

### ISSUE THREAD

**Issue by 9590** [ricequant/rqalpha#33]
用sector()时提示 'sector()' is not defined

**Comment by geraybos** [comment]
这个开源版本不支持 sector, index_component之类的函数吧，只能手动添加

**Comment by wh1100717** [comment]
在 [RQAlpha API Doc](http://rqalpha.readthedocs.io/zh_CN/latest/api/base_api.html) 中，给出了详细的文档信息，以及哪些API 因为数据不开源，暂时不提供，如果对应的数据您有使用需求，可以使用Ricequant 进行回测。
