### ISSUE TITLE
交易后账户 仓位信息的持久化

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#331]
您好，请问怎样实现一个策略中账户仓位信息的持久化，

例如在一个策略中我order了一只或多只股票，账户仓位信息随着更新，当我下一次或者第二天再运行这个策略的时候，想检查上一次的仓位情况，根据上一次的仓位情况下单，有办法实现这种应用场景吗

**Comment by Cuizi7** [comment]
可以。参考 [PersistProvider 接口](http://rqalpha.io/zh_CN/latest/development/basic_concept.html#persistprovider) 。
