### ISSUE TITLE
Account Position类的使用问题

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#332]
自定义了一个Mod，接了自己的数据源，
请问如果要使用交易功能（order_share等），**Account** 和**Position**类一定要在**Mod**的**start_up**阶段注册吗，没实现似乎也能交易，请问这两个类有什么作用，要怎么使用呢，解释起来麻烦的话大概给个思路就行，谢谢。

还有请问
`env.get_position_model(account_type)`、`env.get_account_model(account_type)` 
与 
`env.set_position_model(account_type, PositionModel)`、`env.set_account_model(account_type, AccountModel)`
有什么联系，是如果用get方法的话，就省去了写AccountModel的过程，得到一个默认的基础Model的意思吗

**Comment by Cuizi7** [comment]
Account 和 Position 类提供了账户和仓位的维护逻辑，由于不同交易标的逻辑可能不同，所以提供了扩展功能，与交易没有直接关系。

set 方法用于注册自定义 model，get 方法用于取得 model。
