### ISSUE TITLE
策略参数的问题 start_dt end_dt 和count_bar

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#333]
这三个变量的逻辑是

从start_dt到end_dt之间的每一天，都向前获取count_bar条数据，举个例子

`start_dt=20180501, end_dt=20180520, count_bar=20`

那么handle_bar中的history_bars就会运行20遍（1号到20号），其中每一遍都向前取20天，即

第一次是20180410-20180501的回测结果，直到最后一次20180501-20180520。

我是想问为什么是这样的逻辑呢，是为了绘图还是其他作用吗，直接回测start_dt到end_dt间数据这样参数

的意义不是更直观点么，

这样的逻辑有什么优势或者优点吗

**Comment by Cuizi7** [comment]
[history_bars](http://rqalpha.io/zh_CN/latest/api/base_api.html#history-bars) 没有 start_dt 和 end_dt 参数啊。

**Comment by ronlym** [comment]
@Cuizi7 描述的有些误解，已经修改。我是想问最后传入到history_bars中的dt，就是最开始设定的start_dt到end_dt区间中的每天是吗，也就是说逻辑是像我描述的那样，对每一天都向前做count_bar天数的回测。
我原本以为是对start_dt到end_dt规定的范围进行回测，也就是只运行一次。所以想问问为什么选择这样的逻辑
