### ISSUE TITLE
api 不完整

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#34]
api 不完整
比如没有 xueqiu.top_stocks()

**Comment by yssource** [comment]
@https://github.com/ricequant/rqalpha/issues/27
api 不完整, 用处不大

**Comment by wh1100717** [comment]
在 [RQAlpha API Doc](http://rqalpha.readthedocs.io/zh_CN/latest/api/base_api.html) 中，给出了详细的文档信息，以及哪些API 因为数据不开源，暂时不提供。

**Comment by yssource** [comment]
> 未来我们可能会考虑以接口和授权的方式来开放数据源的获取，届时Extend API 将可以在RQAlpha中被调用。

对非机构用户的接口和授权, 有时间和价格表吗?

**Comment by wh1100717** [comment]
@yssource 有计划，但目前还没有确切的时间和价格表，您如果现在着急使用的话，可以在Rciequant上免费使用。
