### ISSUE TITLE
请问如何修改 output_file 中的字段

### ISSUE THREAD

**Issue by ronlym** [ricequant/rqalpha#342]
请问在哪里修改输出文件中的字段？
<img width="1114" alt="2018-06-11 11 21 43" src="https://user-images.githubusercontent.com/25770147/41211405-b024c306-6d69-11e8-9f5c-edf5d7c9eb1b.png">
例如像把trade中 last_price字段改为price或者frozen_price，
或者添加这样的字段

**Comment by Cuizi7** [comment]
https://github.com/ricequant/rqalpha/blob/ce15cd03463ed799b9c97c9c0410c620797e9ad7/rqalpha/mod/rqalpha_mod_sys_analyser/mod.py#L227

**Comment by Cuizi7** [comment]
https://github.com/ricequant/rqalpha/blob/ce15cd03463ed799b9c97c9c0410c620797e9ad7/rqalpha/mod/rqalpha_mod_sys_analyser/mod.py#L227
