### ISSUE TITLE
Windows在安装rqalpha时出错

### ISSUE THREAD

**Issue by Soledadzyh** [ricequant/rqalpha#344]
## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
![default](https://user-images.githubusercontent.com/35110178/41483322-4e4d0242-710b-11e8-92e5-cd5a16088bda.png)
![default](https://user-images.githubusercontent.com/35110178/41483526-06f429ce-710c-11e8-99ab-1cc033e84eeb.png)

**Comment by emaiqi** [comment]
http://www.emaiqi.com/2018/06/25/win7%E4%B8%8A%E5%AE%89%E8%A3%85rqalpha/

**Comment by Soledadzyh** [comment]
用虚拟环境我也用过 结果是一样的 一直都在报同样的错误

**Comment by Soledadzyh** [comment]
所有需要的包我都安装好了 但就是一直在报错

**Comment by Soledadzyh** [comment]
我是参考官方文档下载的，需要下载的包都装好了但是就是最后安装的时候会报错

**Comment by Cuizi7** [comment]
请先尝试使用 whl 包或者用 conda 安装 bcolz，然后再安装 3.1.1 版本 rqalpha。
