### ISSUE TITLE
安装时可否对应最新的bcolz版本

### ISSUE THREAD

**Issue by amy0li** [ricequant/rqalpha#349]
目前安装要求bcolz 1.2.0，然而 whl 包，已经更新到1.2.1了，旧的包又找不到

这里：

bcolz>=1.1.0,<=1.2.0

**Comment by kelvinfuhao** [comment]
bcolz==1.2.0 已经没有whl了 急求一个 bcolz‑1.2.0‑cp35‑cp35m‑win_amd64.whl
阿阿阿 有的发我个邮箱谢谢（860861021@qq.com） 百度网盘给个链接也行 谢谢谢谢

**Comment by IvonDing** [comment]
同求 bcolz‑1.2.0‑cp36‑cp36m‑win_amd64.whl

**Comment by huntergd** [comment]
没有 bcolz的1.20 whl了，可以下载源码，直接修改 requirment.txt 里面的版本，直接用源码安装 rqalpha

**Comment by Cuizi7** [comment]
RQAlpha 3.1.1  在 python 2.7/3.5/3.6 环境下支持 bcolz 1.2.1 版本。
