### ISSUE TITLE
能否出个对接自有行情数据的指南？

### ISSUE THREAD

**Issue by freemanxzx** [ricequant/rqalpha#35]
如题

**Comment by wh1100717** [comment]
@freemanxzx  RQAlpha 会在近期进行一次大的更新，其中包含了相关文档的完善，以及如何对接自有行情、对接实盘，增加自定义模块等等的相关文档，敬请期待。

**Comment by cedricporter** [comment]
这里有个简单的对接 tushare 行情的简单 demo 可以参考下
https://github.com/ricequant/rqalpha/tree/develop/rqalpha/mod/simple_stock_realtime_trade

**Comment by wh1100717** [comment]
@freemanxzx 

http://rqalpha.readthedocs.io/zh_CN/latest/development/data_source.html

@Cuizi7 写了一个接入 tushare 数据源 替换日线回测数据的文档
