### ISSUE TITLE
ImportError: cannot import name 'RLock'

### ISSUE THREAD

**Issue by nunoyu** [ricequant/rqalpha#350]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：
安装后，import时候出现错误ImportError: cannot import name 'RLock'

## 1. RQAlpha的版本
 3.0.10
## 2. Python的版本
3.6 64X
## 3. 是Windows/Linux/MacOS or others?
windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
import rqalpha
## 5. 您出现的错误堆栈日志信息
 ---> 31     from gevent._threading import (Lock as ThreadLock,
     32                                    RLock as ThreadRLock,
     33                                    get_ident as thread_get_ident,

ImportError: cannot import name 'RLock'

**Comment by Cuizi7** [comment]
rqalpha 限制的 logbook 版本与 gevent 存在不兼容情况，卸载 gevent 即可。
`pip uninstall gevent`

**Comment by Cuizi7** [comment]
RQAlpha 3.1.1 支持新版本的 logbook，与 gevent 兼容。
