### ISSUE TITLE
没有概念板块数据

### ISSUE THREAD

**Issue by huntergd** [ricequant/rqalpha#351]
## 1. RQAlpha的版本
基础API中没有 concept - 概念股票列表 函数 concept(concept_name1, concept_name2, ...)
希望加上，谢谢！

**Comment by huntergd** [comment]
提了10天都没半点反应，只能去用聚宽了。

**Comment by akulatatama** [comment]
@huntergd 开源项目一般不会提供数据，我们提供了基础的日级别数据便于大家回测，其他数据不会提供，如有需要可以寻求一下数据源，或者看我司的付费数据源rqdata, 谢谢。ricequant.com上有提供概念股票列表，欢迎在网站上使用。

**Comment by huntergd** [comment]
OK,好
