### ISSUE TITLE
如何用realtime mod进行实盘模拟？？

### ISSUE THREAD

**Issue by Albert819** [ricequant/rqalpha#354]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Albert819** [comment]
我接受到了实时行情，也yield了事件，可是就没有下文了。我是说生成的事件好像没有被publish。这个问题怎么解决？我当然知道这是一个demo的mod，可是我想实现完整的实盘模拟，谢谢帮助

**Comment by Cuizi7** [comment]
可以调试看看yield语句是否运行到了，yield出来的Event对象会被Executor接收，Executor再publish事件。

**Comment by Albert819** [comment]
我调试过，可以yield事件，也可以publish。我的问题是如何完整地实现实盘模拟，需要我重写一个broker吗或者需要实时数据？谢谢指教

**Comment by Cuizi7** [comment]
实盘模拟用  mod_sys_simulation 中的 SimulationBroker 处理订单就可以，数据和事件可以测试下 mod_sys_stock_realtime 也可以自己对接。
