### ISSUE TITLE
history_bars 读出来的前复权和后复权数据不准

### ISSUE THREAD

**Issue by huntergd** [ricequant/rqalpha#359]
history_bars 读出来的部分数据前复权不准，如：

1、贵州茅台 600519.XSHE  20140703 收盘价 121.68 
      而实际上在同花顺和通达信 次日的前复权收盘价都是 102.30  ,相差近20元

 2、东方财富 300059.XSHE 20140703 收盘价为3.11
       而实际上在同花顺和通达信 次日的前复权收盘价都是 3.04 

而“不复权”是准确的。

## 1. RQAlpha的版本
         3.1.0
## 2. Python的版本
         3.6
## 3. 是Windows/Linux/MacOS or others?
        Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
       closes = history_bars(code, bars, frequency, 'close', adjust_type=‘pre’, skip_suspended=False)

**Comment by Michshelle** [comment]
你好，
前复权数据和其他数据供应商获取不同，时不时都会被提到。基本会和方法论不同相关。
比如针对分红导致的复权，业内目前有两个手法：1. 直接把分红从股票价格里减掉。2. 不复权价格去除以复权因子，并对之后的各类复权因子连除。https://www.zhihu.com/question/50211502/answer/123635003 可参考下这个帖子里的公式图片

RQ采用的就是第二种。
比如茅台：
143.26/(1.119463*  1.021596*1.015109*1.01419) = 121.68。
分母可以用get_ex_factor找出来。
`get_ex_factor('600519.XSHG')`

**Comment by huntergd** [comment]
好的，谢谢您的答复！你们很专业。

希望能提供参数，可选择第一种复权算法（其他主流的炒股软件一样的算法）？
因为，大多数用户用同花顺等软件看盘的，如果通过RQ的数据和策略跑出来的价格，跟这些主流炒股软件的价格不一样，用户会认为我们这系统不靠谱。而且，您也说了，这个问题时不时都会被提到，说明了大家都用同样的疑惑。

期待回复和此特性，谢谢！

**Comment by huntergd** [comment]
OK，谢谢！期待！

**Comment by Cuizi7** [comment]
@Michshelle Mi，暂时 close，如果有变动再 reopen 哈
