### ISSUE TITLE
rqalpha 的交易成本如何设置？

### ISSUE THREAD

**Issue by Darren199612** [ricequant/rqalpha#360]
# 提 ISSUE 须知

在本地的rqalpha main.py中
def init(context):
    context.commission_multiplier = 10.0

更改 context.commission_multiplier  的值不影响交易费用，该如何设置手续费的比例？
## 1. RQAlpha的版本
RQAlpha (3,0,10)
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
Windows

**Comment by Cuizi7** [comment]
请参考文档 [多种方式运行策略](http://rqalpha.io/zh_CN/latest/intro/run_algorithm.html)，使用命令行参数等方式对策略进行配置。
