### ISSUE TITLE
PriceBoard缺乏统一的更新接口

### ISSUE THREAD

**Issue by xystcz** [ricequant/rqalpha#363]
rqalpha中的交易撮合是基于PriceBoard实现，在最新的行情数据Event触发前，PriceBoard就应优先更新，否则在撮合成交时基于的价格仍然是前一笔行情数据（行情订阅列表中，撮合成交要早于用户自己编写的strategy）。
目前代码https://github.com/ricequant/rqalpha/blob/master/rqalpha/core/executor.py在run函数的95行有bar数据更新PriceBoard的逻辑，但是tick数据并没有实现相应的接口。
基于rqalpha通过插件的形式实现tick数据回测时，在不改动executor.py源代码的情况下，无法实现正确的撮合成交逻辑。
建议提供通用的api接口，由插件编写者自己实现。

**Comment by Cuizi7** [comment]
BarDictPriceBoard 只适用于 bar 级别的策略，tick 级别的策略应该额外实现一个基于 tick 的 PriceBoard。
interface.py 提供的 AbstractPriceBoard 就是为了让插件编写者继承实现的。

**Comment by Cuizi7** [comment]
也可以考虑直接在框架中直接把 TickPriceBoard 提供出来。

**Comment by xystcz** [comment]
即使开发者实现了基于AbstractPriceBoard的tick的PriceBoard，当收到一笔新的tick数据时，策略基于该笔tick数据出发信号生成订单，按照正常的逻辑应该是在下一个tick撮合交易，但是由于PriceBoard没有在executor.py中更新，而撮合成交代码在Event.TICK订阅列表的最前面，在收到下一笔tick数据时，仍然是基于触发信号的那笔TICK撮合，这样显然是有问题的。
这种情况只修改TickPriceBoard无法避免。

**Comment by Cuizi7** [comment]
您可以在 TickPriceBoard 中订阅 tick 事件更新行情数据。

**Comment by xystcz** [comment]
非常感谢您的耐心解答。

不过我的关注点在于确保tick Event发出前，PriceBoard已经更新了；
如果将这一操作放在tick Event的订阅列表中实现，必须保证它是订阅列表的第一个元素，否则任何在它之前的订阅操作中调用PriceBoard都是使用的旧数据；
但是EventBus.prepend_listener这一api任何插件都可以调用，无法保证更新代码在订阅列表第一个元素中。
从系统鲁棒性的角度看，我更倾向于单独的系统代码来更新PriceBoard，而非放在订阅列表中。

**Comment by Cuizi7** [comment]
您说的有道理。
也可以 PriceBoard 自己不缓存价格，需要的时候通过 DataSource 或其他组件获取行情信息。

**Comment by xystcz** [comment]
是的，这也是一种非常可行的实现方式。

**Comment by hzliu** [comment]
看一下 PRE_TICK 事件？可能需要在 PRE_TICK 事件中将对应的 tick object 打包进去

在设计的时候，PRE_* 事件和 POST_* 事件就是留给系统及各扩展 mod 使用的。

xujunyong <notifications@github.com> 于2018年8月12日周日 下午9:12写道：
