### ISSUE TITLE
order_value() 加入佣金和滑点 的考虑，以解决全仓买入时手续费不足的bug

### ISSUE THREAD

**Issue by wmsby** [ricequant/rqalpha#366]
在原代码中，order_percent(security, 1)全仓买入某只股票，出现 "创建订单失败：可用资金不足"的拒单行为。拒单本身是对的，这是因为全仓买后没有足够的手续费。但可用金额远远大于买入一手股票的资金，“可用资金不足”显然不合逻辑，令人费解。

修改后的代码可以解决这个bug，不但加入了佣金的考虑，还加入了市价单滑点的考虑，修改如下

文件路径：/mod/rqalpha_mod_sys_accounts/api/api_stock.py

order_value函数:

===================================================================
```python

    if cash_amount > 0:
        commission_decider = env.broker._matcher._commission_decider.deciders[DEFAULT_ACCOUNT_TYPE.STOCK.name]
        commission_rate = commission_decider.rate * commission_decider.multiplier
        min_commission = commission_decider.min_commission
        cash_amount = min(cash_amount, 
                          account.cash / (1 + commission_rate), 
                          account.cash - min_commission)

    if isinstance(style, MarketOrder):
        slippage_decider = env.broker._matcher._slippage_decider.decider
        slippage_rate = slippage_decider.rate
        if cash_amount > 0:
            amount = int(Decimal(cash_amount) / Decimal(price * (1 + slippage_rate)))
        else:
            amount = int(Decimal(cash_amount) / Decimal(price * (1 - slippage_rate)))
    else:
        amount = int(Decimal(cash_amount) / Decimal(style.get_limit_price()))

```
=================================================================
欢迎讨论，如有理解有误，请一定指正。

**Comment by Cuizi7** [comment]
多谢提交。
我认为 order_percent 的含义是，买入价值占总权益一定比例的证券，而不是花掉价值占总权益一定比例的现金。所以目前的拒单是合理的。

**Comment by wmsby** [comment]
这样也有一定道理，各个模块会更独立。但从策略编写的角度来看，常常的想法是出现买点全仓买入，出现卖点全仓卖出，这时候不管是用order_value(security, availbale_cash), 还是order_percent(security, 1), 时不时会出现拒单行为...比如现在空仓有1000万可用资金，全仓买入一个10元的股票，order_value(security, availbale_cash)或order_percent(security, 1)会买入100万股，这时候会拒单。除非在下单前，先根据佣金和滑点算好要买的股数，有没有更好的处理办法呢？

**Comment by Cuizi7** [comment]
下单api考虑滑点意义不大，实盘中滑点是没法控制的。
当然实盘中也不应过于依赖 order_value order_percent 这类 ”智能“ 的 API，在没有 executor 之前这种 api 一个大单打出去是非常危险的，策略必须要自己考虑下多少股的问题。
