### ISSUE TITLE
期货context.future_account.daily_pnl和context.portfolio.daily_pnl不一致bug

### ISSUE THREAD

**Issue by v12know** [ricequant/rqalpha#371]
在使用rqalpha进行回测的时候，如果对合约进行持仓过夜之后查看context.future_account.daily_pnl和context.portfolio.daily_pnl，这两个变量的值，发现会有比较大的出入。
查看源码rqalpha/rqalpha/mod/rqalpha_mod_sys_accounts/position_model/future_position.py发现：
daily_pnl（当日盈亏）依赖于_buy_realized_pnl，_sell_realized_pnl这两个内部变量，但按阅读apply_trade函数的逻辑，发现_buy_realized_pnl得到的平仓盈亏是（平仓价-开仓价）得到的。而根据网上提供的资料，当日盈亏是（平仓价-昨日结算价）来得到的。
恳请项目组大神抽空看看是我理解偏差还是确实存在bug，谢谢！！！

**Comment by Cuizi7** [comment]
对于昨仓来说，buy_old_holding_list 中的 “开仓价” 就是昨结价。
