### ISSUE TITLE
document not found

### ISSUE THREAD

**Issue by TracyDay** [ricequant/rqalpha#373]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.1.0/2.0.0b0

## 2. Python的版本
2.7

## 3. 是Windows/Linux/MacOS or others?
windows

## 5. 您出现的错误堆栈日志信息
在使用3.1.0版本时进行数据获取出现IOError
![image](http://pc64xr6lq.bkt.clouddn.com/site_images/ASJKFOW-230-2FASJF2JKFLASLJFKASJKLJFK34KL43JKLJ.png)
在使用2.0.0.b0版本时不会出现这个问题，但是并未下载到数据，并且直接在网页中打开获取数据的链接出现document not found

**Comment by Cuizi7** [comment]
rqalpha 3.2.0 已移除对 colorama 的依赖，请卸载 colorama 并安装 3.2.0 以上版本 rqalpha。
