### ISSUE TITLE
order_percent 指定用开盘价买入时，部分股票无法成交

### ISSUE THREAD

**Issue by huntergd** [ricequant/rqalpha#374]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.1.0
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
             price = self.bar_dict[code].open
            shares = self.context.portfolio.cash / price  # 计算现在portfolio中的现金可以购买多少股票
            if cur_position <= 0 and shares > 100:
                result = order_percent(code, self.context.trade_buy_percent, price=price)
                print('买入 : ', self.selector.securities[code]['name'], ' 价格: ', price, self.context.trade_buy_percent * 100, '% 结果：', result)

## 5. 您出现的错误堆栈日志信息
2018-03-08 00:00:00 =============================================
买入 :  东方财富  价格:  13.76 10.0 % 结果： Order({'order_id': 15366586320000, 'secondary_order_id': None, 'trading_datetime': datetime.datetime(2018, 3, 8, 15, 0), 'datetime': datetime.datetime(2018, 3, 8, 15, 0), 'quantity': 700, 'unfilled_quantity': 700, 'order_book_id': '300059.XSHE', 'side': SIDE.BUY, 'position_effect': POSITION_EFFECT.OPEN, 'message': '', 'filled_quantity': 0, 'status': ORDER_STATUS.ACTIVE, 'price': 13.76, 'type': ORDER_TYPE.LIMIT, 'avg_price': 0, 'transaction_cost': 0, 'frozen_price': 13.76})
现金:  90368.0
持仓 : 

2018-03-09 00:00:00 =============================================
现金:  100000.0
持仓 : 

2018-04-13 00:00:00 =============================================
买入 :  中兴通讯  价格:  31.59 10.0 % 结果： Order({'order_id': 15366586320001, 'secondary_order_id': None, 'trading_datetime': datetime.datetime(2018, 4, 13, 15, 0), 'datetime': datetime.datetime(2018, 4, 13, 15, 0), 'quantity': 300, 'unfilled_quantity': 0, 'order_book_id': '000063.XSHE', 'side': SIDE.BUY, 'position_effect': POSITION_EFFECT.OPEN, 'message': '', 'filled_quantity': 300, 'status': ORDER_STATUS.FILLED, 'price': 31.59, 'type': ORDER_TYPE.LIMIT, 'avg_price': 31.2, 'transaction_cost': 7.488, 'frozen_price': 31.59})
现金:  90632.512
持仓 : 
中兴通讯  :  300 股

2018-04-18 00:00:00 =============================================
买入 :  青岛海尔  价格:  17.22 10.0 % 结果： Order({'order_id': 15366586320002, 'secondary_order_id': None, 'trading_datetime': datetime.datetime(2018, 4, 18, 15, 0), 'datetime': datetime.datetime(2018, 4, 18, 15, 0), 'quantity': 500, 'unfilled_quantity': 0, 'order_book_id': '600690.XSHG', 'side': SIDE.BUY, 'position_effect': POSITION_EFFECT.OPEN, 'message': '', 'filled_quantity': 500, 'status': ORDER_STATUS.FILLED, 'price': 17.22, 'type': ORDER_TYPE.LIMIT, 'avg_price': 16.74, 'transaction_cost': 6.696000000000001, 'frozen_price': 17.22})
现金:  82255.816
持仓 : 
中兴通讯  :  300 股
青岛海尔  :  500 股

2018-07-27 00:00:00 =============================================
买入 :  中国石油  价格:  7.56 10.0 % 结果： Order({'order_id': 15366586320003, 'secondary_order_id': None, 'trading_datetime': datetime.datetime(2018, 7, 27, 15, 0), 'datetime': datetime.datetime(2018, 7, 27, 15, 0), 'quantity': 1200, 'unfilled_quantity': 1200, 'order_book_id': '601857.XSHG', 'side': SIDE.BUY, 'position_effect': POSITION_EFFECT.OPEN, 'message': '', 'filled_quantity': 0, 'status': ORDER_STATUS.ACTIVE, 'price': 7.56, 'type': ORDER_TYPE.LIMIT, 'avg_price': 0, 'transaction_cost': 0, 'frozen_price': 7.56})
现金:  73354.816
持仓 : 
中兴通讯  :  300 股
青岛海尔  :  500 股

其中，东方财富和中国石油，无法成交，而 中兴通讯和青岛海尔可以。
如果不指定price，则，4只股票都可以成交。
这是Bug吗？

**Comment by huntergd** [comment]
怎么两周了，都没有回复？使用过程中遇到很多问题，有时真想放弃使用这个平台。

**Comment by hzliu** [comment]
限价单不能成交是很正常的

Hunter <notifications@github.com> 于2018年9月26日周三 上午11:08写道：
