### ISSUE TITLE
最新rqalpha版本，python3.5windows下可以正常下载bundle数据，但是运行任何示例代码都会导致2-3秒后python崩溃

### ISSUE THREAD

**Issue by sfhmzpig** [ricequant/rqalpha#378]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Cuizi7** [comment]
no reply, close.
