### ISSUE TITLE
clone的话，到底该怎样组织目录结构，才能确保relative import可以用呢？

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha#38]
clone的话，到底该怎样组织目录结构，才能确保relative import可以用呢？
现在运行的时候，一堆relative import的异常；

**Comment by wh1100717** [comment]
并不是很清楚是什么意思.... 如果是0.3.0版本，在Python 2 下 确实会有relative import。
现在新版本(0.3.2 及以上) 应该不会了。
