### ISSUE TITLE
卖股票时，不需要调整amount为100的倍数

### ISSUE THREAD

**Issue by chsobin** [ricequant/rqalpha#382]
https://github.com/ricequant/rqalpha/blob/02b10b337f3ed710150ccfec96d2a0ac7d7465d7/rqalpha/mod/rqalpha_mod_sys_accounts/api/api_stock.py#L121-L128

第二个 if 的条件  逻辑有问题，
如果是卖操作，amount不需要一手一手的卖，因此不需要调整
amount != env.portfolio.accounts[DEFAULT_ACCOUNT_TYPE.STOCK.name].positions[order_book_id].sellable

**Comment by Cuizi7** [comment]
请参考上交所对卖出股票时相关规则的说明
http://www.sse.com.cn/lawandrules/guide/jyznlc/jytz/c/c_20150912_3986109.shtml

**Comment by chsobin** [comment]
了解了，多谢指正
