### ISSUE TITLE
请问可以提供一下关于实盘模拟的说明文档吗 或者代码

### ISSUE THREAD

**Issue by plckOne** [ricequant/rqalpha#388]
文档中没有找到，在issues中的连接地址已经404
## 1. RQAlpha的版本
3.1.2
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
linux

**Comment by Cuizi7** [comment]
Ricequant 使用 rqalpha 实现模拟交易的相关代码是闭源的。
