### ISSUE TITLE
自定义数据源的问题

### ISSUE THREAD

**Issue by Gwill** [ricequant/rqalpha#393]
看文档：

https://rqalpha.readthedocs.io/zh_CN/latest/development/data_source.html#id2

是不是对于读入的数据的必须要有类似 https://github.com/ricequant/rqalpha/blob/master/rqalpha/examples/IF1706_20161108.csv 的字段结构？

文档里只有数据读入的说明，没有使用的说明，对于字段要求不是很理解

**Comment by Cuizi7** [comment]
这个例子的意思是，策略作为python脚本可以读取任意数据，并基于这些数据作出决策。与框架关系不大，字段完全取决于策略自己的需求。
