### ISSUE TITLE
plot能不能即时动态绘图?

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#394]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 5. 您出现的错误堆栈日志信息

       我觉得plot能即时动态绘图是更合乎逻辑的做法.很多时候我可以在绘图上即时看到收益率曲线,我就知道自己对策略是否满意和是否需要进行修改,而不是等到最后策略运行完了我才知道.动态绘图会节省更多的时间.所以我尝试了一下用pyqtgraph来做这件事,试了几天,仍然没有头绪,动态绘图可以做出来,但没办法用在rqalpha上.  
        所以我过来问一下,你们有没有动态绘图的打算??或者有什么建议给我开发一下思路?比如我想问问在rqalpha里产生的数据pickle是动态的吗?我可不可以Pickle出来用于即时绘图??反正我想在我的rqalpha策略里用pyqtgraph进行动态绘图时,试了很多种方法都没有成功.

**Comment by Cuizi7** [comment]
plot 是用 matplotlib 在回测结束后画出来的，pickle 的数据也是在回测结束后落盘的。
可以写个mod在运行过程中发数据出来然后由前段画图。
Ricequant的网站以及终端产品都实现了动态绘图的功能，这部分实现不会放到开源框架中。
