### ISSUE TITLE
12月开始不能更新数据了吗？update了一直尝试链接失败。。

### ISSUE THREAD

**Issue by yelublue** [ricequant/rqalpha#396]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Cuizi7** [comment]
请检查电脑网络设置，检查能否访问 7xjci3.com1.z0.glb.clouddn.com
