### ISSUE TITLE
emmmmm官网居然有错别字

### ISSUE THREAD

**Issue by WenJunwen** [ricequant/rqalpha#397]
![image](https://user-images.githubusercontent.com/23470504/49773384-dd1ebb80-fd2b-11e8-86a1-b2ab5d0f2791.png)
而且微信信号通知，读起来也怪怪的。。。

**Comment by Cuizi7** [comment]
多谢提醒，已反馈至前端同学。

**Comment by poppinlp** [comment]
已修复，感谢反馈。 👍
