### ISSUE TITLE
Add VWAP decider

### ISSUE THREAD

**Issue by SeanHuang904** [ricequant/rqalpha#398]
可否在Day Bar回测中加入VWAP撮合的功能。看了一下matcher的框架，如果加入_current_bar_vwap_decider的话应该改动不大，需要的数据在Day Bar中都已经有了。能想到的问题是决定是否达到Up/Down limit的时候用VWAP价格可能不太合适。

**Comment by mar-heaven** [comment]
@SeanHuang904 dev 已加入
