### ISSUE TITLE
关于 000001.XSHE 平安银行 接口数据与公告数据不符情况

### ISSUE THREAD

**Issue by gucasbrg** [ricequant/rqalpha#4]
在'dividend.bcolz'文件中，猜测：
#announcement_date：公告日期
#book_closure_date：股权登记日
#ex_dividend_date：除权除息
#payable_date：股息到帐日

## **下载下来数据：**

![image](https://cloud.githubusercontent.com/assets/3182658/17460170/6e9baad4-5c8c-11e6-98ba-3198dca550fd.png)
## **同花顺数据：**
![image](https://cloud.githubusercontent.com/assets/3182658/17460174/928c12b2-5c8c-11e6-9451-9bf559969db8.png)
## **2015年公告数据：**
 [平安银行股份有限公司 2014 年年度权益分派实施公告](http://www.cninfo.com.cn/finalpage/2015-04-07/1200788275.PDF)
数据源跟官方不一致很可能造成回测的失误呀。。
希望能确保数据源的准确性

**Comment by gucasbrg** [comment]
add 同花顺

**Comment by hzliu** [comment]
分红数据是经过前复权处理的。
