### ISSUE TITLE
股票不能卖空

### ISSUE THREAD

**Issue by FrankYuFR** [ricequant/rqalpha#400]
目前A股市场支持融券卖空的，
但Rqalpha 却股票不能卖空

## 1. RQAlpha的版本
3,2,0
## 2. Python的版本
3,6
## 3. 是Windows/Linux/MacOS or others?
windows

**Comment by Cuizi7** [comment]
可以通过设置 mod_sys_risk（前端风控模块）的 validate_stock_position 配置关闭验券以达到卖空股票的目的。

**Comment by FrankYuFR** [comment]
这样做会有一些问题，比如：
卖空后如果碰上送转股，会导致持仓量不是100的整数倍，然后由于平仓的时候会检测下单是否整手，从而导致那个低于100的股是永远无法平掉的

**Comment by FrankYuFR** [comment]
再比如：
在rqalpha中卖股票后，对应市值为负（如果还有其他多仓，总市值会相互抵消），并且不占用资金（现实中融券是需要资金抵押的），这样会导致账户中可用资金多余实际可用资金，而总市值会明显小于实际市值。

**Comment by Cuizi7** [comment]
rqalpha 卖空不检测是否是整手

**Comment by FrankYuFR** [comment]
平仓买入时需要检测是否整手。
而卖空后如果碰上送转股，会导致持仓量不是100的整数倍。
如是总有小于100的仓是平不掉的

**Comment by FrankYuFR** [comment]
平仓买入时需要检测是否整手。
而卖空后如果碰上送转股，会导致持仓量不是100的整数倍。
从而会导致小于100的仓是平不掉的

**Comment by hzliu** [comment]
这种实际是如何处理的呢？允许买入非整手的？

Frank <notifications@github.com> 于2019年1月8日周二 下午5:00写道：

**Comment by mar-heaven** [comment]
@FrankYuFR 现在版本的可以了

**Comment by liningbo** [comment]
rqalpha 4.x版本现在支持融券的下单和账户的相关结算了？
