### ISSUE TITLE
请问如何配置参数进行模拟实盘？

### ISSUE THREAD

**Issue by simplezhang57** [ricequant/rqalpha#401]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.2

## 2. Python的版本
3.6

## 3. 是Windows/Linux/MacOS or others?
WIN

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
run_type=p

**Comment by Cuizi7** [comment]
模拟实盘需要在开源的 RQAlpha 基础上实现基于实时行情的 DataSource 和 EventSource。
