### ISSUE TITLE
无法通过pycharm进行调试，报错SyntaxError: invalid or missing encoding declaration for 'D:/Python/Anaconda3/Scripts/rqalpha.exe'

### ISSUE THREAD

**Issue by freakybridge** [ricequant/rqalpha#403]
## 1. RQAlpha的版本
版本3.2.0

## 2. Python的版本
3.7.1

## 3. 是Windows/Linux/MacOS or others?
Windows 7 Ulitmate

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
由于之前python用的不多，所以仍是探索阶段
目前已经以下工作：
1，conda环境配置
2，rqalpha安装完毕
3，复制了example里面的buy hold策略，并新建project为“firstStrategy“
4，运行配置如下:
Script Path: D:\Python\Anaconda3\Scripts\rqalpha.exe（并没有找到rqalpha-script.py）
Parameter: run -f C:\Users\dell\Desktop\testRQ\firstStrategy.py -s 2015-01-01 -e 2018-12-25 -d D:/Python/RQalpha/bundle --account stock 100000 --benchmark 000300.XSHG --plot -o result.pkl

点击run，一切正常，可以出绩效和回测图
点击debug，报错：SyntaxError: invalid or missing encoding declaration for 'D:/Python/Anaconda3/Scripts/rqalpha.exe'
使用的策略就是example中的buy hold策略，只不过是新建了project，并命名为firstStrategy

代码如下
-------------------------------------------------------------------------------------------------------------------
def init(context):
    logger.info("init")
    context.s1 = "000001.XSHE"
    update_universe(context.s1)
    context.fired = False

def before_trading(context):
    pass

def handle_bar(context, bar_dict):
    if not context.fired:
        order_percent(context.s1, 1)
        context.fired = True

-------------------------------------------------------------------------------------------------------------------

## 5. 您出现的错误堆栈日志信息
D:\Python\Anaconda3\python.exe D:\Python\PyCharm\helpers\pydev\pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 50809 --file D:/Python/Anaconda3/Scripts/rqalpha.exe run -f C:\Users\dell\Desktop\testRQ\firstStrategy.py -s 2015-01-01 -e 2018-12-25 -d D:/Python/RQalpha/bundle --account stock 100000 --benchmark 000300.XSHG --plot -o result.pkl
pydev debugger: process 9232 is connecting

Connected to pydev debugger (build 183.4886.43)
Traceback (most recent call last):
  File "D:\Python\Anaconda3\lib\tokenize.py", line 385, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\PyCharm\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "D:\Python\PyCharm\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Python\PyCharm\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Python\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 11, in execfile
    stream = tokenize.open(file)  # @UndefinedVariable
  File "D:\Python\Anaconda3\lib\tokenize.py", line 449, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "D:\Python\Anaconda3\lib\tokenize.py", line 426, in detect_encoding
    encoding = find_cookie(first)
  File "D:\Python\Anaconda3\lib\tokenize.py", line 390, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'D:/Python/Anaconda3/Scripts/rqalpha.exe'

**Comment by uhyuuhyu** [comment]
不要直接调用rqalpha.exe，参考https://github.com/ricequant/rqalpha/issues/7
