### ISSUE TITLE
安装 Rqalpha 时 一直报错啊

### ISSUE THREAD

**Issue by xiaolai1218** [ricequant/rqalpha#404]
安装 Rqalpha 时 一直报错啊

Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-tf__vkc1/line-profiler/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-record-n3_wvqdx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-tf__vkc1/line-profiler/

**Comment by Cuizi7** [comment]
`conda install line_profiler`

**Comment by xiaolai1218** [comment]
不行 这个命令行 以及安装bcolz  、rqalpha 都会报一样的错误  

  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
  #include <algorithm>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for bcolz



然后最后一个报错：
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-_vgc9amf/bcolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-record-gb621it8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-_vgc9amf/bcolz/

**Comment by zhnlk** [comment]
pip install Cython git+https://github.com/rkern/line_profiler.git
@xiaolai1218 试试这一句
