### ISSUE TITLE
安装 Rqalpha 时 一直报错啊

### ISSUE THREAD

**Issue by xiaolai1218** [ricequant/rqalpha#405]
安装bcolz  、rqalpha 都会报一样的错误  

  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
  #include <algorithm>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for bcolz

然后最后一个报错：
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-_vgc9amf/bcolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-record-gb621it8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ry/mmdd6qc90hbbq4cqpp_lb1zc0000gn/T/pip-install-_vgc9amf/bcolz/

_Originally posted by @xiaolai1218 in https://github.com/ricequant/rqalpha/issues/404#issuecomment-450281081_

**Comment by xiaolai1218** [comment]
$ conda install bcolz -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  这个命令 就可以   不用pip install

**Comment by poloxue** [comment]
文档里面给了说明了，好好看下文档。http://rqalpha.io/zh_CN/latest/intro/install.html。以下是截图的内容：

Windows 环境下因为默认没有安装 Visual C++ Compiler, 需要自行下载并安装 visual-cpp-build-tools，如果觉得麻烦，也可以直接去 http://www.lfd.uci.edu/~gohlke/pythonlibs/#bcolz 下载相应版本的 bcolz wheel 包，直接安装编译后的 bcolz 版本。

除了 bcolz 库以外，line-profiler 安装时也同样需要 C++ 编译器，如果出现安装失败，也可以前往 http://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler 下载相应的版本 line-profiler wheel 包来进行安装。
