### ISSUE TITLE
bcolz update

### ISSUE THREAD

**Issue by curme** [ricequant/rqalpha#406]
RQAlpha==3.2
Python==3.5.2 64位
OS==Ubuntu 16.04 64位

按照[安装指南](https://rqalpha.readthedocs.io/zh_CN/latest/intro/install.html#intro-install-get-data)安装后，在获取数据（rqalpha update-bundle）环节会遇到报错：ValueError: numpy.dtype has the wrong size, try recompiling.

将bcolz从1.2.0更新为1.2.1后不报错。

**Comment by Cuizi7** [comment]
可能是 bcolz 编译的环境和使用的环境使用了不同版本的numpy。
