### ISSUE TITLE
同一投资组合中，股票账户和期货账户资金互转

### ISSUE THREAD

**Issue by plckOne** [ricequant/rqalpha#409]
请问现在有办法做到这一功能吗，考虑到做对冲策略时，可能需要灵活调整整个portfolio的资金分配，而不是在初始化就写死股票和期货账户的初始资金，请问目前有什么思路来暂时做到这一点吗。（如果将要实现这一功能，希望能考虑实际转账中的时效问题，即股票账户提现第二日到账，才能存入期货账户这一情况）

**Comment by Cuizi7** [comment]
目前 rqalpha 暂不支持
