### ISSUE TITLE
plot图但是报错ValueError: _getfullpathname: embedded null character

### ISSUE THREAD

**Issue by szuyanghongyu** [ricequant/rqalpha#41]
运行：
rqalpha run -f C:\Users\91963_000\Desktop\rqalpha\examples\golden_cross.py -s 2013-01-01 -e 2015-01-01  --plot
就报这个错误。查了下网上说是编码问题，目前操作系统win8。
。。。。。想问下是不是我要去装个linux虚拟机来跑，还是说有其他简单的解决方法。

提前感谢

**Comment by szuyanghongyu** [comment]
噢。。。我发现我的版本太老了，现在更新了。

**Comment by wh1100717** [comment]
@szuyanghongyu RQAlpha 之后会更新比较频繁，建议经常升级 哈~
