### ISSUE TITLE
bar_count calculation bug in _on_system_init of benchmark_provider.py

### ISSUE THREAD

**Issue by mysl** [ricequant/rqalpha#412]
Currently,  bar_count = len(env.config.base.trading_calendar) + 1.  But I think it's a bug, it shouldn't +1 here. This bug would not expose in usual case,  but if the config.base.start_date <= the start of the bundle,  the len(close_series) would be always less than bar_count by 1,  and cause exception

============================================================

        bar_count = len(env.config.base.trading_calendar) + 1
        end_date = env.config.base.end_date
        close_series = env.data_proxy.history_bars(
            self._order_book_id, bar_count, "1d", "close", end_date, skip_suspended=False, adjust_type='pre'
        )
        if len(close_series) < bar_count:
               raise RuntimeError(_("Invalid benchmark: unable to load enough close price."))

**Comment by Cuizi7** [comment]
if config.base.start_date <= start of the bundle, such instrument is not supposed to be a benchmark, because daily return of benchmark on start_date should be the change rate between last_price on start_date and the previous day of start_date instead of 1.
