### ISSUE TITLE
history_bars - 某一合约历史数据

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#413]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 5. 您出现的错误堆栈日志信息

调用时间 | 返回数据
-- | --
T日before_trading | T-1日day bar
T日handle_bar | T日day bar

这里的意思是指如果在T日handle_bar使用history_bars可以取到T日的收盘价吗?如果我在T日handle_bar使用history_bars取获取到的数据的最后一位,即history_bars('000002.XSHE', 5, '1d', 'close')[-1],是不是盘中就知道收盘价了,是不是有了未来函数?

**Comment by Cuizi7** [comment]
日回测是把整个交易日的数据压缩到一个 bar 中，每个 bar 都包含了整个交易日的数据。日回测中不存在 “盘中” 的概念。
分钟回测盘中调用 history_bars 是不能获取到当日日线数据的。
