### ISSUE TITLE
Mac 10.14.3 安装bcolz失败

### ISSUE THREAD

**Issue by wjs0702cn** [ricequant/rqalpha#414]
Mac 10.14.3 安装bcolz失败

    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/wangjs/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5q/gcz_1lxn51s8bhk215_chp4w0000gn/T/pip-install-kjz3oI/bcolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5q/gcz_1lxn51s8bhk215_chp4w0000gn/T/pip-record-i3uiLs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5q/gcz_1lxn51s8bhk215_chp4w0000gn/T/pip-install-kjz3oI/bcolz/

有人遇到这个问题么？ 好像是mac这个版本没有stdlibc++了， bcolz怎么安装啊？

**Comment by Lhfcws** [comment]
brew install ta-lib

**Comment by Cuizi7** [comment]
可以使用anaconda安装
`conda install bcolz`

**Comment by jiangzhonglian** [comment]
mac上 pip如何安装啊？
