### ISSUE TITLE
rqalpha mod install shipane安装失败

### ISSUE THREAD

**Issue by jxhuliqun138** [ricequant/rqalpha#415]
## 5. 您出现的错误堆栈日志信息
  ******************************************************************************
***
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 install
ed?
  ******************************************************************************
***
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
  Building wheel for tushare (setup.py) ... done
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\c1\
0d\95\a0f892fd23e1e99449ba477d92675580939fccda1d404e381f
  Building wheel for rqopen-client (setup.py) ... done
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\b3\
f4\3a\5543a7eae267a6848ab79df9fd4a4862caddaf132f13b625b9
  Building wheel for bs4 (setup.py) ... done
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\a0\
b0\b2\4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
  Building wheel for tzlocal (setup.py) ... done
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\15\
ae\df\a67bf1ed84e9bf230187d36d8dcfd30072bea0236cb059ed91
Successfully built tushare rqopen-client bs4 tzlocal
Failed to build lxml
tushare 1.2.21 has requirement lxml>=3.8.0, but you'll have lxml 3.6.4 which is
incompatible.

    C:\Users\ADMINI~1\AppData\Local\Temp\xmlXPathInitx64m12y9.c(1): fatal error
C1083: 无法打开包括文件: “libxml/xpath.h”: No such file or directory
    ****************************************************************************
*****
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 insta
lled?
    ****************************************************************************
*****
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to d:\anaconda3\lib\site-packages\lxml-4.2.1-py3.6.egg-info
   from d:\anaconda3\lib\site-packages\~xml-4.2.1-py3.6.egg-info
  Moving to d:\anaconda3\lib\site-packages\lxml\
   from d:\anaconda3\lib\site-packages\~xml
Command "d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:
\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-tlufycy_\\lxml\\setup.py';f
=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f
.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI
~1\AppData\Local\Temp\pip-record-k9idpe0p\install-record.txt --single-version-ex
ternally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppDat
a\Local\Temp\pip-install-tlufycy_\lxml\

**Comment by jxhuliqun138** [comment]
@管理员 麻烦帮忙看一下这个问题

**Comment by Cuizi7** [comment]
这是个第三方 mod，Ricequant 不负责维护支持。

**Comment by Cuizi7** [comment]
原 mod 仓库：https://github.com/wh1100717/rqalpha-mod-ShiPanE 现在已经被作者删掉了
其他开发者 fork 的：https://github.com/sinall/rqalpha-mod-ShiPanE

**Comment by jxhuliqun138** [comment]
C:\Users\Administrator>pip install  -f lxml==3.6.4
ERROR: You must give at least one requirement to install (maybe you meant "pip i
nstall lxml==3.6.4"?)
请问这个是什么问题?
