### ISSUE TITLE
rqalpha 期货策略是不是不能再本地运行

### ISSUE THREAD

**Issue by studyquant** [ricequant/rqalpha#419]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 2. Python的版本
3.7 
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha 期货策略是不是不能再本地运行， 有提供期货策略的样例代码，但是我在本地搭建，运行的时候，并不能跑，股票策略可以跑。请问是什么原因

**Comment by Cuizi7** [comment]
请附上具体报错信息。
