### ISSUE TITLE
mod_sys_transaction_cost佣金率设置

### ISSUE THREAD

**Issue by dxma** [ricequant/rqalpha#420]
请考虑将每笔佣金费率commission_rate改为配置项，此为计算交易成本的核心因素，目前该费率（万八）hardcore在代码中，无法配置。

<code>
class CNStockTransactionCostDecider(StockTransactionCostDecider):
    def __init__(self, commission_multiplier, min_commission):
        super(CNStockTransactionCostDecider, self).__init__(0.0008, commission_multiplier, min_commission)
        self.tax_rate = 0.001
</code>

感谢

**Comment by Cuizi7** [comment]
可以通过 commission_multiplier 调整佣金

**Comment by dxma** [comment]
这样倒也可以达到目的，只是这个乘数主要是针对期货的。

感谢
