### ISSUE TITLE
【建议】所有交易接口返回错误代码

### ISSUE THREAD

**Issue by dxma** [ricequant/rqalpha#421]
当前所有下单接口均使用logger打印方式输出交易异常信息（停牌，cash不足等原因拒单），代码层面直接return返回。建议加入类似errorno的错误代码机制，可以在代码层面更好处理。

**Comment by Cuizi7** [comment]
RQAlpha 除了要满足程序员对需求外，还要满足对程序设计了解不多的金融行业用户，errorno 或者 raise Exception 的方式对他们可能不是非常友好。
不过也可以考虑在保留当前 API 的基础上加入“面向程序员”的下单函数。

**Comment by ruifeng96150** [comment]
感觉不需要，这些错误最好提前预防，不能等出错了再处理

**Comment by Cuizi7** [comment]
暂不准备支持错误代码，如楼上所说，提前预防是个好主意
