### ISSUE TITLE
【建议】基本API添加end

### ISSUE THREAD

**Issue by dxma** [ricequant/rqalpha#422]
对应init，end(context)在回测执行完成后调用，可以系统收集想要处理的数据，生成文件。
与zipline中analyse类似，目前只有通过mod/tear_down可以实现此功能。

感谢

**Comment by Cuizi7** [comment]
rqalpha 除了回测外还要支持模拟交易和实盘，这样的 end 函数在模拟交易和实盘中永远都不会触发。

**Comment by dxma** [comment]
我个人认为和其他external mod一样，默认disable，是不会造成太多误会的。end有很多实际应用场景，比如处理context，或者调用外部程序分析analyser数据结果。
当然这些的确是回测场景，其他场景的确用处不大。
