### ISSUE TITLE
rqalpha matplot 

### ISSUE THREAD

**Issue by GooglePeng** [ricequant/rqalpha#423]
RQalpha3.3.1 | Python3.6 | Windows10
想了解下RQalpha将matplotlib生成plot图的函数封装在哪了？我想在运行example中的示例代码后自动保存图片，但找不到RQalpha库中哪个源码导入了Matplotlib库

**Comment by Cuizi7** [comment]
https://github.com/ricequant/rqalpha/blob/master/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py
