### ISSUE TITLE
动态更新股池的例子能否给一个

### ISSUE THREAD

**Issue by zhangshoug** [ricequant/rqalpha#426]
看了下自带的几个例子，没有动态更新股池的例子，都是回测前固定股票池，如那个rsi.py多股票的例子也是回测前固定的。不知能否给一个动态更新股池的例子，如每日选底背离的股加入股池，设置观察期（如10个交易日），观察期内符合买入条件（如macd金叉）买入，过观察期不在持仓中从股池清除

**Comment by Cuizi7** [comment]
可以使用 subscribe 和 unsubscribe 函数更新股票池，亦可以使用其他方法维护策略自己的股票池。
