### ISSUE TITLE
window10 环境下编译好rqalpha，无法生成examples

### ISSUE THREAD

**Issue by kanghua309** [ricequant/rqalpha#43]
rqalpha examples -d ./ 或 rqalpha examples -d c:\ 
等在当前目录下或c:都没有创建出examples 目录，而且静默失败，没有任何提示。
不知道我哪里搞错了。

rqalpha  编译过程都ok，而且 rqalpha  version 显示 （0,3,0）

**Comment by wh1100717** [comment]
@kanghua309 麻烦升级到0.3.2再试一下~~

**Comment by kanghua309** [comment]
我升级到0.3.2  。现象依旧，没有创建出examples 目录。
到底哪里错了？

**Comment by wh1100717** [comment]
@kanghua309 问题已经解决，请升级至0.3.3版本

**Comment by kanghua309** [comment]
ok，已验证，解决了。不错，赞一个
