### ISSUE TITLE
rqalpha cmd with PyYAML YAMLLoadWarning

### ISSUE THREAD

**Issue by bingyao** [ricequant/rqalpha#433]
## 0. 主要问题描述

`PyYAML`出于[安全性考虑][1]，从5.1版本开始，所有`yaml.load()`中未指定`Loader=`的用法都会触发`YAMLLoadWarning`。

> Use of PyYAML's `yaml.load` function **without specifying the Loader=... parameter, has been deprecated.**

[1]: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

## 1. RQAlpha的版本

```bash
$ rqalpha version
Current Version:  (3, 3, 1)
```

## 2. Python的版本

```python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'5.1'
```

## 3. 是Windows/Linux/MacOS or others?

* **macOS**

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

运行任何`rqalpha`命令行程序

## 5. 您出现的错误堆栈日志信息

```bash
$ rqalpha update-bundle
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/rqalpha/utils/config.py:40: 
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
   return yaml.load(f)
```

**Comment by Cuizi7** [comment]
fixed in develop branch

**Comment by Cuizi7** [comment]
fixed on 3.3.2
