### ISSUE TITLE
启动参数--signal问题

### ISSUE THREAD

**Issue by fstonyguan** [ricequant/rqalpha#435]
## 1. RQAlpha的版本
3.3.1
## 2. Python的版本
3.6.7
## 3. 是Windows/Linux/MacOS or others?
Linux
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
命令行加入--signal
rqalpha run -fq 1d -f ma60ma300.py --start-date 2018-01-05 --end-date 2019-06-11 -o results/000010.XSHE.pkl --account stock 100000 --progress -bm 000010.XSHE --signal --extra-vars '{"s1": "000010.XSHE"}'
交易函数：
    cur_position = context.portfolio.positions[context.s1].quantity
    shares = context.portfolio.cash / bar_dict[context.s1].close

    order_shares(context.s1, shares)

    order_shares(context.s1, -cur_position)
## 5. 您出现的错误堆栈日志信息
2018-01-08 WARN 您在 BAR_STATUS.LIMIT_UP 下成交 16100 手 000010.XSHE (请尽量避免涨跌停时下单)
2018-01-15 WARN 订单创建失败: 下单量为 0
检查发现：不是涨停的话，成交后，portfolio仓位有改变，卖出时订单能创建成功；而涨停时，虽然warn提示了成交，但portfolio仓位没变，以至于接下来的卖出订单创建失败。

**Comment by Cuizi7** [comment]
在 master 分支做了修复，但还未测试。

**Comment by Cuizi7** [comment]
fixed in 3.3.2
