### ISSUE TITLE
是否考虑将DataProxy和Scheduler也改为可自己重写的

### ISSUE THREAD

**Issue by marvin-zhao** [ricequant/rqalpha#438]
版本 3.3.1
当前rqalpha的可扩展功能很强，但是DataProxy和scheduler是在run方法中写死指定的，在proxy和scheduler中针对自己想要的场景做一些调整，现在除了直接hack rqalpha，没法通过mod来实现，是否考虑将这两部分也改成接口方式

**Comment by ruifeng96150** [comment]
DataProxy 这一部分是可以通过mod重写了吧，但是对bundle有些依赖性，然后只实现自己有用的数据就可以了，比如只研究股票，那就只写股票相关的数据接口。（最终的目的，不用每天更新bundle甚至不用安装bcolz）

对于scheduler，我的看法是：
1 不是必须集成在mod里，只要有相关的回调就可以了。
2 一些大的时间周期用处不大，如scheduler.run_weekly - 每周运行，为了安全，脚本不大会跑这么长时间，一般是每天定时开闭。
3时分秒级别的scheduler，还是有用的，建议添加固定时间间隔的scheduler，以周期性执行某些任务。

**Comment by Cuizi7** [comment]
DataProxy 的一个重要作用是简化 DataSource 的实现的同时方便其他模块的调用；如 instrument 和 trading_dates 数据，DataSource 只需要实现 get_all_instruments 和 get_all_trading_dates 即可。DataProxy 又在此基础上实现了更多灵活的方法。

当然目前 DataProxy 也有一些方法是对 DataSource 中方法的重复定义，背离了上述功能，这部分我觉得应该干掉。其他的方法如果大家在开发中发现有哪些影响了扩展性欢迎提出来我们逐个讨论是否下放到 DataSource。

**Comment by Cuizi7** [comment]
scheduler 与核心逻辑关系不大，我觉得可以考虑整体放到 mod 中，至于抽象成 interface 我还没什么好的想法

**Comment by joysboy** [comment]
现在的scheduler的运行时间判断是写死的，如果不是用于股票，就不太适用，例如开盘时间不是9点半

dataproxy虽然有些别扭，有时也可以直接获取datasource来调用一些自定义的方法，但scheduler现在除了hack没法来自定义开盘收盘时间

**Comment by Cuizi7** [comment]
scheduler 的需求我明白了，我想想怎么处理

**Comment by hzliu** [comment]
如果不喜欢目前的scheduler，完全可以通过mod实现自己的scheduler

**Comment by Cuizi7** [comment]
4.0.0 版本已将 scheduler 移动到 mod 中，可以 disable 掉该 mod 替换为自己的实现。
