### ISSUE TITLE
替换已有数据源，自定义的DataSource类放在base_data_source文件下吗？

### ISSUE THREAD

**Issue by Lord1992** [ricequant/rqalpha#439]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by Cuizi7** [comment]
不需要

**Comment by Lord1992** [comment]
那应该放在哪里？

**Comment by Cuizi7** [comment]
http://rqalpha.io/zh_CN/latest/development/data_source.html#tushare

**Comment by Lord1992** [comment]
我如果想用本地数据直接替换，有没有参考的案例借鉴？

**Comment by Cuizi7** [comment]
上边发的链接就是替换数据源的教程，其他例子暂无。
