### ISSUE TITLE
rqalpha update_bundle 命令在window10 有问题

### ISSUE THREAD

**Issue by kanghua309** [ricequant/rqalpha#44]
1. rqalpha update_bundle 并未在~/.rqalpha 下发现对应目录，是不是应有个bundle目录出现
2. 如果执行 rqalpha update_bundle -d c:\  该命令是否会删除C目录下文件？ 造成系统崩溃？ 请检查一下。

**Comment by kanghua309** [comment]
补充一下 1， update_bundle 执行后 没有bundle子目录出现 ./rqalpha/bundle/

**Comment by wh1100717** [comment]
@kanghua309 你看一下~/.rqalpha 下是否生成了一堆 *.blocz 文件， 如果是的话，就是正确的。
