### ISSUE TITLE
替换数据源

### ISSUE THREAD

**Issue by Lord1992** [ricequant/rqalpha#440]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
![image](https://user-images.githubusercontent.com/37130834/61781619-45438d00-ae37-11e9-91ea-56af63bd6790.png)
这部分放在哪个文件夹下，需要分开放吗？

**Comment by Cuizi7** [comment]
麻烦阅读文档 http://rqalpha.io/zh_CN/latest/development/mod.html

**Comment by Lord1992** [comment]
PyPI方式安装自定义Mod，这一步是必要的吗？

**Comment by Cuizi7** [comment]
不是必要的，在本地安装亦可。能被 import 就行
