### ISSUE TITLE
安装第三方mode

### ISSUE THREAD

**Issue by Lord1992** [ricequant/rqalpha#441]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
![image](https://user-images.githubusercontent.com/37130834/61844100-d581e080-aed0-11e9-8c1e-6fb2aac6aff0.png)
![image](https://user-images.githubusercontent.com/37130834/61844109-dc105800-aed0-11e9-9fc5-97fd8f23325b.png)
这样算成功了吗？

**Comment by Lord1992** [comment]
![image](https://user-images.githubusercontent.com/37130834/61844602-95bbf880-aed2-11e9-907d-ac718917958b.png)
启用mode时好像也有点问题

**Comment by Cuizi7** [comment]
不成功。打开 python 控制台试试 import rqalpha_mod_onetokenkdata 能否成功。

**Comment by Lord1992** [comment]
mod hello 安装成功后，如何使用，文档写的不太清楚

**Comment by Cuizi7** [comment]
mod enable 后 start_up 和 tear_down 方法会在启动时被调用，可以在其中实现想要的功能。
