### ISSUE TITLE
第三方mode使用

### ISSUE THREAD

**Issue by Lord1992** [ricequant/rqalpha#442]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
def start_up(self, env, mod_config):
env, mod_config怎么确定？

**Comment by Cuizi7** [comment]
env 和 mod_config 是框架传入的参数。分别是 Environment 对象和 mod 的配置字典。
