### ISSUE TITLE
替换第三方数据源

### ISSUE THREAD

**Issue by Lord1992** [ricequant/rqalpha#443]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
![image](https://user-images.githubusercontent.com/37130834/62102901-36445b00-b2cd-11e9-9465-26357389a93f.png)
我把程序改完运行后，为啥默认数据没有被替换为第三方数据？

**Comment by Cuizi7** [comment]
可以通过单步调试等方式检查所有 mod 都启动之后 data_source 是否真的被替换成了自定义的 DataSourc。可能的原因是 mod 没有启动或者优先级设置的不正确导致 data_source 被其他 mod 覆盖。
