### ISSUE TITLE
关于双边持仓的保证金计算

### ISSUE THREAD

**Issue by mysl** [ricequant/rqalpha#447]
Hi,
目前保证金的计算是按照两边保证金之和来算的。但是对于期货合约，各交易所都是按照单边最大保证金来算,  这与CTP account查询返回字段CurrMargin的值一致(和快期/彭博上显示的也一致)。是不是应该在FuturePositionProxy里面override一下margin的实现？

@property
    def margin(self):
        """
        [float] 保证金

        保证金 = 持仓量 * 最新价 * 合约乘数 * 保证金率

        股票保证金 = 市值 = 持仓量 * 最新价

        """
        return self._long.margin + self._short.margin

**Comment by Cuizi7** [comment]
暂无计划加入单向大边的逻辑。
