### ISSUE TITLE
rqalpha update_bundle取不到数据

### ISSUE THREAD

**Issue by zhanghuibin** [ricequant/rqalpha#45]
rqalpha update_bundle 命令报错：
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
系统：macOS 10.12.3

**Comment by zhanghuibin** [comment]
$ rqalpha version
('Current Version: ', (0, 3, 3))

**Comment by wh1100717** [comment]
@zhanghuibin 你这个看上去像是网络异常...  ping 一下 7xjci3.com1.z0.glb.clouddn.com 看看能不能ping通？

**Comment by zhanghuibin** [comment]
ping了，结果如下：
129 packets transmitted, 103 packets received, 20.2% packet loss
round-trip min/avg/max/stddev = 5.043/12.288/163.122/18.127 ms
和丢包率有关系吗？
rqalpha update_bundle命令试了多次，有时候出现某个try提示符就没反应了。
例如：try http://7xjci3.com1.z0.glb.clouddn.com/bundles_v2/rqbundle_20161228.tar.bz2 ...

**Comment by wh1100717** [comment]
这个就是你那里的网络问题了...
