### ISSUE TITLE
 pip 19.3.1(至2019-10最新版本)下，安装mod出错

### ISSUE THREAD

**Issue by amos365** [ricequant/rqalpha#450]
安装第三方mod出错

pip version:  19.3.1
python version: 3.7
1. 
rqalpha/`__main__.py`, line 239, in install
    options, mod_list = InstallCommand().parse_args(params)
InstallCommand初始化 missing 2 required positional arguments: 'name' and 'summary'
随便改成options, mod_list = InstallCommand('test1', 'test2').parse_args(params)就可以通过了。
可能line 304, options, mod_list = UninstallCommand().parse_args(params)也需要两个参数，这个没试

2. 
`__main__.py`, line 256, in install
    installed_result = pip_main(params)
TypeError: 'module' object is not callable
pip文件夹_internal下main是一个py文件，可以改成：installed_result = pip_main.main(params)
line 320, uninstalled_result = pip_main(params)可以改成： uninstalled_result = pip_main.main(params)
就可以通过了

**Comment by amos365** [comment]
安装mod：直接cd至文件夹执行python setup.py install, 
然后在.rqalpha文件夹下创建一个mod_config.yml
好像也可以

**Comment by AngusWG** [comment]
已修复 感谢您的反馈

**Comment by AngusWG** [comment]
已在mater分支修复

**Comment by Ricequant-Faye** [comment]
感谢您的反馈，我们想赠送您一个月的RQData试用权限，方便的话请加一下我们的官方微信号码RicequantCS与我们联系  @amos365
