### ISSUE TITLE
除权问题

### ISSUE THREAD

**Issue by jskssp** [ricequant/rqalpha#451]
1. RQAlpha的版本——3.4.1、3.4.2

2. Python的版本——3.7

3. Windows 10 64位

4. 问题：用例子集中的golden_Cross运行，股票用“海康威视”，其它一样，除权类型用默认（即”pre“），时间周期2017-6-1～2019-9-1，除权没有生效，显示在图上是曲线突然下降，
调试后发现，handle_bar中股价（dict_bar和history_bars的数据）对除权前的股价没有做除权处理，这个怎么处理？

**Comment by Cuizi7** [comment]
框架使用未复权数据做回测，发生粉红拆分时会像账户中补现金/股票。曲线突然下降的问题麻烦附上可复现的回测代码及配置。

**Comment by jskssp** [comment]
**### Golden Cross文件代码**
from rqalpha.api import *

import talib


# 在这个方法中编写任何的初始化逻辑。context对象将会在你的算法策略的任何方法之间做传递。
def init(context):
    context.s1 = "002001.XSHE"

    # 设置这个策略当中会用到的参数，在策略中可以随时调用，这个策略使用长短均线，我们在这里设定长线和短线的区间，在调试寻找最佳区间的时候只需要在这里进行数值改动
    context.SHORTPERIOD = 20
    context.LONGPERIOD = 120


# 你选择的证券的数据更新将会触发此段逻辑，例如日或分钟历史数据切片或者是实时数据切片更新
def handle_bar(context, bar_dict):
    # 开始编写你的主要的算法逻辑
    # bar_dict[order_book_id] 可以拿到某个证券的bar信息
    # context.portfolio 可以拿到现在的投资组合状态信息

    # 使用order_shares(id_or_ins, amount)方法进行落单

    # TODO: 开始编写你的算法吧！

    # 因为策略需要用到均线，所以需要读取历史数据
    prices = history_bars(context.s1, context.LONGPERIOD+1, '1d', 'close')

    # 使用talib计算长短两根均线，均线以array的格式表达
    short_avg = talib.SMA(prices, context.SHORTPERIOD)
    long_avg = talib.SMA(prices, context.LONGPERIOD)

    plot("short avg", short_avg[-1])
    plot("long avg", long_avg[-1])

    # 计算现在portfolio中股票的仓位
    cur_position = context.portfolio.positions[context.s1].quantity
    # 计算现在portfolio中的现金可以购买多少股票
    shares = context.portfolio.cash / bar_dict[context.s1].close

    # 如果短均线从上往下跌破长均线，也就是在目前的bar短线平均值低于长线平均值，而上一个bar的短线平均值高于长线平均值
    if short_avg[-1] - long_avg[-1] < 0 and short_avg[-2] - long_avg[-2] > 0 and cur_position > 0:
        # 进行清仓
        order_target_value(context.s1, 0)

    # 如果短均线从下往上突破长均线，为入场信号
    if short_avg[-1] - long_avg[-1] > 0 and short_avg[-2] - long_avg[-2] < 0:
        # 满仓入股
        order_shares(context.s1, shares)


**### run_file_demo代码：**
# -*- coding: utf-8 -*-

from rqalpha import run_file

config = {
  "base": {
    'data_bundle_path': 'D:/python/code/quant/rqalpha/bundle',
    "start_date": "2017-06-01",
    "end_date": "2019-09-01",
    "benchmark": "000300.XSHG",
    "accounts": {
      "stock": 100000
    }
  },
  "extra": {
    "log_level": "info",
  },
  "mod": {
    "sys_analyser": {
      "enabled": True,
      "plot": True
    }
  }
}

strategy_file_path = "./golden_cross.py"

run_file(strategy_file_path, config)

**Comment by hzliu** [comment]
这是正常的，跳跃应该是发生在除权日，除权之后价格下降，history_bars返回的数据会做相应的复权处理，因此short_avg/long_avg会出现下跳
