### ISSUE TITLE
功能建议：position增加 建仓时间 字段

### ISSUE THREAD

**Issue by zhangshoug** [ricequant/rqalpha#455]
context对象中仓位信息，增加一个建仓时间的字段，这个用起来很方便，特别是实现买入后动态止损的策略.

**Comment by laye0619** [comment]
同样有此需求，我要计算持仓时间

**Comment by hzliu** [comment]
> 如果同一标的重复交易，反复买卖，建仓时间怎么更新呢？特定策略需要计算持仓时间的需求，更适合在策略层记录一个变量来实现吧

对的，应该在策略层面解决
