### ISSUE TITLE
功能意见-建议增加当前bar开盘价撮合机制和配置选项，以及当前bar开始时(开盘时9:30)运行函数的机制

### ISSUE THREAD

**Issue by liningbo** [ricequant/rqalpha#456]
**1. RQAlpha的版本**

3.4.2
**2. Python的版本**

3.5
**主要针对日线回测和模拟:**
schedule_daily 支持time_rule设置成minite=1或者minite=0, order的时候判断时间，order的时候，分钟的用分钟数据撮合，日频率的可以给用户一个配置项，是用当日开盘价还是收盘价撮合，或者简单粗暴的写死，12:00之前用开盘价撮合，12:00之后用当日收盘价撮合。

增加一个BAR_BEGIN的事件也可以，9:30执行某个回调函数，用当日开盘价撮合。

日线回测时，历史价格应该通过update-bundle下载下来了。

日线模拟时，可以9:30或者9:31从服务器获取一次价格来撮合成交。日线频率低，不会对服务器有啥压力。

散户资金量小，实盘基本都能以很接近开盘价成交，不会有太多的流动性问题，再加上滑点机制，回测和模拟交易的收益率不会虚高。

分钟回测也建议支持下分钟bar的开盘价撮合。

**Comment by Cuizi7** [comment]
已增加 open_auction 约定函数，在该函数下单可以实现开盘价成交。用法详见[文档](https://rqalpha.readthedocs.io/zh_CN/latest/api/base_api.html#open-auction)

**Comment by liningbo** [comment]
赞，解决了开盘买入策略的需求。
