### ISSUE TITLE
scheduler.run_daily中的time_rule参数无效

### ISSUE THREAD

**Issue by bamboowind** [ricequant/rqalpha#459]
RQAlpha 3.4.2
Python 3.7.3
OS: Linux Ubuntu 18.04
尝试在sheduler.run_daily()里面加入time_rule参数来控制每次发动的时间，结果发现每次发动都是在收盘的时候。run_weekly()和run_monthly()同样如此。

调用函数：

```python
scheduler.run_daily(func,time_rule=market_open(minute=10))
```

在func的里面打印：
```python
print(context.now)
```

结果发现是15:00:00

**Comment by Cuizi7** [comment]
time_rule 是在对应时间点的 before_trading/handle_bar 之后执行的，日回测中指定 盘中任意时间都会在当日 handle_bar 之后执行。
见文档 http://rqalpha.io/zh_CN/latest/api/base_api.html#scheduler-run-daily

**Comment by bamboowind** [comment]
那么请问如果我想要在某个日期的给定时间内执行结果，该怎么实现呢？在handle_bar里面似乎没有办法定时？而scheduler里面又会到15：00

**Comment by quant2008** [comment]
> time_rule 是在对应时间点的 before_trading/handle_bar 之后执行的，日回测中指定盘中任意时间都会在当日 handle_bar 之后执行。 见文档 http://rqalpha.io/zh_CN/latest/api/base_api.html#scheduler-run-daily

分钟回测可以用吗？在线平台中，怎样指定分钟回测？
