### ISSUE TITLE
能否提供一个OpenAI Gym的接口

### ISSUE THREAD

**Issue by liuwen-w** [ricequant/rqalpha#460]
如题，方便基于Reinforcement Learning的模型开发

**Comment by Cuizi7** [comment]
需要rqalpha提供什么支持？

**Comment by liuwen-w** [comment]
https://github.com/openai/gym

The core gym interface is Env, which is the unified environment interface. There is no interface for agents; that part is left to you. The following are the Env methods you should know:

reset(self): Reset the environment's state. Returns observation.
step(self, action): Step the environment by one timestep. Returns observation, reward, done, info.
render(self, mode='human'): Render one frame of the environment. The default mode will do something human friendly, such as pop up a window.

**Comment by Cuizi7** [comment]
麻烦具体描述下希望 rqalpha 提供什么，issue 暂时关闭
