### ISSUE TITLE
SimulationMod  在模拟交易时也不应该启动，代码里只是在run_type实盘时return了

### ISSUE THREAD

**Issue by liningbo** [ricequant/rqalpha#461]
## 1. RQAlpha的版本
3, 4, 3, 'dev2'
## 2. Python的版本
3.5
## 3. 是Windows/Linux/MacOS or others?
windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
SimulationMod 只是针对回测，在模拟和实盘交易时都不应该启动，但是代码只是在实盘交易时返回了，我觉得env.config.base.run_type == RUN_TYPE.LIVE_TRADING或者env.config.base.run_type == RUN_TYPE.PAPER_TRADING 时都应该return.
现在master的代码如下:
class SimulationMod(AbstractMod):
    def __init__(self):
        pass

    def start_up(self, env, mod_config):

        if env.config.base.run_type == RUN_TYPE.LIVE_TRADING:
            return

        mod_config.matching_type = self.parse_matching_type(mod_config.matching_type)

**Comment by Cuizi7** [comment]
SimulationMod 包含模拟柜台以及撮合引擎等，模拟交易也需要。
