### ISSUE TITLE
funcat替换 DataBackend 为 RQAlpha 的 DataProxy出错

### ISSUE THREAD

**Issue by ksgt00857912** [ricequant/rqalpha#464]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
4.0.0dev1

## 2. Python的版本
3.8.0

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))

## 5. 您出现的错误堆栈日志信息
self.data_proxy = DataProxy(BaseDataSource(os.path.expanduser(bundle_path)))
TypeError: __init__() missing 1 required positional argument: 'custom_future_info'

**Comment by Cuizi7** [comment]
麻烦到 funcat 项目开 issue
