### ISSUE TITLE
按rqalpha 3.4.x 文档运行参数调优示例文件，handle_bar和init中代码无运行，除添加print以外与文档示例文件无区别

### ISSUE THREAD

**Issue by xupeijie2012** [ricequant/rqalpha#465]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
 3.4.4
## 2. Python的版本
3.6.8
## 3. 是Windows/Linux/MacOS or others?
windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
（一）、按参数调优文档中的示例，配置执行文件：

```
from rqalpha.api import *
import talib


def init(context):
    print("22222223333322")
    context.s1 = "000002.XSHE"

    context.SHORTPERIOD = 4
    context.LONGPERIOD = 25


def handle_bar(context, bar_dict):
    print("2222222222222222222")
    prices = history_bars(context.s1, context.LONGPERIOD+1, '1d', 'close')

    short_avg = talib.SMA(prices, context.SHORTPERIOD)
    long_avg = talib.SMA(prices, context.LONGPERIOD)

    cur_position = context.portfolio.positions[context.s1].quantity
    shares = context.portfolio.cash / bar_dict[context.s1].close

    if short_avg[-1] - long_avg[-1] < 0 and short_avg[-2] - long_avg[-2] > 0 and cur_position > 0:
        order_target_value(context.s1, 0)
        print(context.SHORTPERIOD)

    if short_avg[-1] - long_avg[-1] > 0 and short_avg[-2] - long_avg[-2] < 0:
        order_shares(context.s1, shares)
print("111111111111111")
```

（二）、按参数调优配置的参数配置文件

```
import concurrent.futures
import multiprocessing
from rqalpha import run
tasks = []
for short_period in range(6, 7, 1):
    for long_period in range(30, 31, 1):
        config = {
            "extra": {
                "context_vars": {
                    "SHORTPERIOD": short_period,
                    "LONGPERIOD": long_period,
                },
                "log_level": "error",
            },
            "base": {
                "matching_type": "current_bar",
                "start_date": "2015-01-01",
                "end_date": "2016-01-01",

                "frequency": "1d",
                "strategy_file": "neeeeee.py",
                "accounts": {
                    "stock": 100000
                }
            },
            "mod": {
                "sys_progress": {
                    "enabled": True,
                    "show": True,
                },
                "sys_analyser": {
                    "enabled": True,
                    "output_file": "resultsout-{short_period}-{long_period}.pkl".format(
                        short_period=short_period,
                        long_period=long_period,
                    )
                },
            },
        }

        tasks.append(config)


    def run_bt(config):
        run(config)


    if __name__ == '__main__':
        with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
            for task in tasks:
                print(executor)
                print(task)
                print(run_bt)

                executor.submit(run_bt, task)
```

（三）、执行参数配置文件，得到的运行结果：

C:\Users\Administrator\PycharmProjects\untitled1\venv\Scripts\python.exe "C:/Users/Administrator/PycharmProjects/untitled1/yuyu - 副本.py"
<concurrent.futures.process.ProcessPoolExecutor object at 0x00000222F1EE0470>
{'extra': {'context_vars': {'SHORTPERIOD': 6, 'LONGPERIOD': 30}, 'log_level': 'error'}, 'base': {'matching_type': 'current_bar', 'start_date': '2015-01-01', 'end_date': '2016-01-01', 'frequency': '1d', 'strategy_file': 'neeeeee.py', 'accounts': {'stock': 100000}}, 'mod': {'sys_progress': {'enabled': True, 'show': True}, 'sys_analyser': {'enabled': True, 'output_file': 'resultsout-6-30.pkl'}}}
<function run_bt at 0x00000222F1ED6BF8>
111111111111111

Process finished with exit code 0

## 5. 您出现的错误堆栈日志信息

无错误提示，代码直接运行结束，在handle_bar和init中的print无运行，pkl文件无创建

**Comment by xupeijie2012** [comment]
C:\Users\Administrator>pip list
Package                       Version
----------------------------- ----------
atomicwrites                  1.3.0
attrs                         19.3.0
backcall                      0.1.0
backports.functools-lru-cache 1.6.1
bcolz                         1.2.1
cached-property               1.5.1
certifi                       2019.11.28
chardet                       3.0.4
Click                         7.0
colorama                      0.4.3
cycler                        0.10.0
Cython                        0.29.14
decorator                     4.4.1
dill                          0.2.5
funcat                        0.3.2
idna                          2.8
importlib-metadata            1.4.0
ipython                       7.11.1
ipython-genutils              0.2.0
jedi                          0.15.2
jsonpickle                    0.9.4
kiwisolver                    1.1.0
line-profiler                 3.0.2
Logbook                       1.5.3
lxml                          4.4.2
matplotlib                    3.1.2
more-itertools                8.1.0
multiprocess                  0.70.9
numpy                         1.18.1
packaging                     20.0
pandas                        0.25.3
parso                         0.5.2
pickleshare                   0.7.5
pip                           20.0.1
pluggy                        0.13.1
prompt-toolkit                3.0.2
py                            1.8.1
Pygments                      2.5.2
pyparsing                     2.4.6
pyreadline                    2.1
pytest                        5.3.4
python-dateutil               2.8.1
pytz                          2019.3
PyYAML                        5.3
requests                      2.22.0
rqalpha                       3.4.4
rqrisk                        0.0.12
setuptools                    40.6.2
simplejson                    3.17.0
six                           1.14.0
TA-Lib                        0.4.17
tabulate                      0.8.6
traitlets                     4.3.3
tushare                       1.2.48
urllib3                       1.25.7
wcwidth                       0.1.8
XlsxWriter                    1.2.7
zipp                          1.0.0

**Comment by xupeijie2012** [comment]
C:\Users\Administrator>pip list
Package                       Version
----------------------------- ----------
atomicwrites                  1.3.0
attrs                         19.3.0
backcall                      0.1.0
backports.functools-lru-cache 1.6.1
bcolz                         1.2.1
cached-property               1.5.1
certifi                       2019.11.28
chardet                       3.0.4
Click                         7.0
colorama                      0.4.3
cycler                        0.10.0
Cython                        0.29.14
decorator                     4.4.1
dill                          0.2.5
funcat                        0.3.2
idna                          2.8
importlib-metadata            1.4.0
ipython                       7.11.1
ipython-genutils              0.2.0
jedi                          0.15.2
jsonpickle                    0.9.4
kiwisolver                    1.1.0
line-profiler                 3.0.2
Logbook                       1.5.3
lxml                          4.4.2
matplotlib                    3.1.2
more-itertools                8.1.0
multiprocess                  0.70.9
numpy                         1.18.1
packaging                     20.0
pandas                        0.25.3
parso                         0.5.2
pickleshare                   0.7.5
pip                           20.0.1
pluggy                        0.13.1
prompt-toolkit                3.0.2
py                            1.8.1
Pygments                      2.5.2
pyparsing                     2.4.6
pyreadline                    2.1
pytest                        5.3.4
python-dateutil               2.8.1
pytz                          2019.3
PyYAML                        5.3
requests                      2.22.0
rqalpha                       3.4.4
rqrisk                        0.0.12
setuptools                    40.6.2
simplejson                    3.17.0
six                           1.14.0
TA-Lib                        0.4.17
tabulate                      0.8.6
traitlets                     4.3.3
tushare                       1.2.48
urllib3                       1.25.7
wcwidth                       0.1.8
XlsxWriter                    1.2.7
zipp                          1.0.0

**Comment by xupeijie2012** [comment]
open

**Comment by Cuizi7** [comment]
参考文档，将 init，handle_bar 等函数传入 run_func 执行策略
https://rqalpha.readthedocs.io/zh_CN/latest/intro/run_algorithm.html#run-func
