### ISSUE TITLE
回测有一些股票仓位出现frozen是什么原因

### ISSUE THREAD

**Issue by IvonDing** [ricequant/rqalpha#466]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.1.1
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
回测中发现一些股票一直卖不掉，debug发现是由于这些股票的position全部是frozen的，即positions._frozen=股票仓位。好像是我在信号模式下卖出了跌停的股票，该股票的仓位就被记为frozen了，但为何该股票止之后一直在持仓中。

**Comment by Cuizi7** [comment]
股票冻结仓位是因为有未成交的平仓单。
