### ISSUE TITLE
There is a bug in rqalpha/model/instrument.py

### ISSUE THREAD

**Issue by wheniseeyou** [ricequant/rqalpha#468]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.7
## 3. 是Windows/Linux/MacOS or others?
Mac OS
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
When run the examples named run_fun_demo.py in rqalpha/model/instrument.py line 32-35 the date format is already datetime not str, so it can not use split;

**Comment by Cuizi7** [comment]
麻烦尝试最新版本的 rqalpha，并提供可复现问题的策略代码
