### ISSUE TITLE
config设置report_save_path后运行异常

### ISSUE THREAD

**Issue by liugang7** [ricequant/rqalpha#471]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.4.4
## 2. Python的版本
3.7.6
## 3. 是Windows/Linux/MacOS or others?
Win10 64bit
IDE： VS code
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

# run_file_demo
import os
from rqalpha import run
import pandas as pd

current_dir = os.path.dirname(os.path.realpath(__file__))
pkl_file = os.path.join(current_dir,r"rqout\out1.pkl")
report_dir = os.path.join(current_dir,"rqout5")

config = {
  "base": {
    # "data_bundle_path":r"C:\Users\liugw\rq\.rqalpha\bundle",
    "start_date": "2016-06-01",
    "end_date": "2016-12-01",
    "benchmark": "000300.XSHG",
    "strategy_file": r"C:\Users\liugw\rq\rqalpha\examples\buy_and_hold.py",
    "accounts": {
        "stock": 100000
    }
  },
  "extra": {
      "log_level": "info",
  },
  "mod": {
    "sys_analyser": {
      "enabled": True,
      "plot": True,
      "output_file":pkl_file,
      "report_save_path":report_dir
    }
  }
}

run(config)
print('Start generating report...')
print('The end.')

## 5. 您出现的错误堆栈日志信息
会异常退出，不会打印后面两行，即不会打印“Start generating report...”和"The end".

**Comment by Cuizi7** [comment]
麻烦给出具体的异常信息和报错堆栈。
