### ISSUE TITLE
feature/v4 强制使用rqdatac模块

### ISSUE THREAD

**Issue by xujun05** [ricequant/rqalpha#472]
## 1. RQAlpha的版本
feature/v4
## 2. Python的版本
3.8.1
## 3. 是Windows/Linux/MacOS or others?
Windows Server
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
feature/v4全部采用hdf5格式的文件，放弃了bcolz文件，同时需要导入rqdatac包，是否可以给一个公共的账号，提供日线部分的免费数据，谢谢

**Comment by Cuizi7** [comment]
v4 版本发布前会提供

**Comment by Cuizi7** [comment]
4.0.0 版本已提供 rqalpha download-bundle 命令，该命令不依赖 rqdatac
