### ISSUE TITLE
[BUG]000418.XSHE在buyandhold.py策略中出现200倍年化收益率

### ISSUE THREAD

**Issue by xujun05** [ricequant/rqalpha#473]
## 1. RQAlpha的版本
feature/v4
## 2. Python的版本
3.8.1
## 3. 是Windows/Linux/MacOS or others?
Windows Server
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
buyandhold.py如果采用传参
context.s1 = "000418.XSHE"
出现200倍的收益率，数据出现错误

**Comment by Cuizi7** [comment]
策略获得两百倍年化收益率不能说明有什么错误。
如有错误麻烦给出更具体的定位，如 “000418.XSHE 某日的收盘价有误”。
