### ISSUE TITLE
[BUG]Instrument字段board_type未能涵盖正确的市场与权限信息

### ISSUE THREAD

**Issue by xujun05** [ricequant/rqalpha#474]
## 1. RQAlpha的版本
feature/v4
## 2. Python的版本
3.8.1
## 3. 是Windows/Linux/MacOS or others?
Windows Server
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
Instrument字段board_type仅支持主板与创业板，目前科创板的权限与交易权限并不与主板一致，lotsize设计为100也是有问题的。
同时中小板等问题，定义未能实际一致

**Comment by Cuizi7** [comment]
目前不支持科创板。
