### ISSUE TITLE
Scheduler运行报错

### ISSUE THREAD

**Issue by wileechou** [ricequant/rqalpha#477]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
rqalpha3.4
## 2. Python的版本
3.7.6
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
scheduler.run_weekly(log_cash,tradingday=2)
log_cash只是日志输出当前的现金信息
# 5. 您出现的错误堆栈日志信息
![image](https://user-images.githubusercontent.com/37919763/77152442-f4be2580-6ad2-11ea-8105-7ffff6d56815.png)

**Comment by wileechou** [comment]
具体应当是isinstance()这个函数返回了false，但当我用command+左键进入时，进入python_stubs下的.py文件，并且函数只有一个pass

**Comment by wileechou** [comment]
![image](https://user-images.githubusercontent.com/37919763/77152652-541c3580-6ad3-11ea-844a-a4e407adcfd9.png)

**Comment by wileechou** [comment]
![image](https://user-images.githubusercontent.com/37919763/77152702-6ac28c80-6ad3-11ea-92c3-dce23981bcf2.png)

**Comment by Cuizi7** [comment]
isinstance  不是 python 实现的，ide 跳转看不到具体实现。
如果是 rqalpha 的 bug 麻烦具体表述且附上可复现的策略代码。
