### ISSUE TITLE
持久化文件没有trade和portfolio的历史记录

### ISSUE THREAD

**Issue by han14466** [ricequant/rqalpha#479]
## 1. RQAlpha的版本
3.4.4

## 2. Python的版本
3.7

## 3. 是Windows/Linux/MacOS or others?
windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
    "run_type": "p",
run_func(init=init, after_trading=after_trading, before_trading=before_trading, handle_bar=handle_bar, config=config)

## 5. 您出现的错误堆栈日志信息
模拟交易时没有持久化trade和portfolio的历史记录。

如果想展示交易和权益的历史变化趋势，需要持久化trade和portfolio的历史记录。目前看代码没有开放这部分能力。
请问是否可以在DiskPersistProvider中当portfolio == key的时候多append一个文件。trade目前发现没有实现set_state和get_state方法，这个是不是要自己实现一下，然后注册到persist_helper.register中呢？

**Comment by Cuizi7** [comment]
持久化是用于持续运行的策略保存状态以便从中断中恢复运行的，不是用做数据展示的。
trade 和 portfolio 的历史不是运行所必需的状态。

**Comment by Cuizi7** [comment]
满足展示需要建议另外实现 mod 收集所需的数据。
