### ISSUE TITLE
是否可以在result.pkl中记录自定义数据?

### ISSUE THREAD

**Issue by merz9b** [ricequant/rqalpha#48]
1. 现在是否有类似zipline的record函数，在before_trading,handle_bar中调用记录相关指标？

[zipline.api.record](http://www.zipline.io/appendix.html?highlight=record#zipline.api.record)
```
zipline.api.record(self, *args, **kwargs)
Track and record values each day.

Parameters:	
**kwargs

The names and values to record.

Notes

These values will appear in the performance packets and the performance dataframe passed to analyze and returned from run_algorithm().
```

2. logger.info好像有一些bug,在Spyder中回测时会重复打印.

**Comment by cedricporter** [comment]
目前 plot("name", value) 会输出到 pkl 文件里面，而且会绘制出来
