### ISSUE TITLE
[bug]api/api_stock.py 下单逻辑错误

### ISSUE THREAD

**Issue by xujun05** [ricequant/rqalpha#486]
外界传入参数amount=0,含义为清仓。
feature4.1 分支在函数def _order_shares(ins, amount, style, auto_switch_order_value)中正确地定义未POSITION_CLOSE
但是在函数的实现_submit_order(ins, amount, side, position_effect, style, auto_switch_order_value)
直接对amount==0做判断，直接返回"Order Creation Failed: 0 order quantity"。

主要是因为对于amount=0这个参数理解不一致，造成上下调用错误。

# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
feature4.1
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha/rqalpha/mod/rqalpha_mod_sys_accounts/api/api_stock.py

**Comment by hzliu** [comment]
调用哪个api的时候？

**Comment by Cuizi7** [comment]
order_shares 和 submit_order 参数 amount 都表示下单量，而不是目标仓位。文档中基础 API 部分有这两个 api 的介绍。
