### ISSUE TITLE
手续费

### ISSUE THREAD

**Issue by wade2018** [ricequant/rqalpha#487]
佣金比率在哪配置啊

**Comment by mar-heaven** [comment]
rqalpha.core.strategy_context 下边有个 类 **RunInfo**，它有一个  _commission_multiplier_ 属性可以调节手续费
参考文档：
https://rqalpha.readthedocs.io/zh_CN/latest/api/base_api.html#module-rqalpha.core.strategy_context

**Comment by wade2018** [comment]
不行。以文档第一个策略-买入&持有为例
打印：res['sys_analyser']['trades']，可以看到做了一笔交易，费率是0.08%，我现在要修改这个费率，找了半天文档都没找到在哪。。。

**Comment by wade2018** [comment]
"mod": {
    "sys_analyser": {
      "enabled": True,
      "plot": True
    },
    "sys_transaction_cost":{
        "commission_multiplier": 5
    }
  }
