### ISSUE TITLE
down stock's data error!!

### ISSUE THREAD

**Issue by henshan2002** [ricequant/rqalpha#49]
Ubuntu16.04 64bit  +Anaconda 4.3.8 
Rqalpha Installation success，but run " rqalpha update_bundle" result in an error!

`ImportError: /home/jianxue/anaconda3/lib/python3.6/site-packages/bcolz/carray_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm
`

**Comment by hzliu** [comment]
看起来是bcolz安装的有问题

**Comment by wh1100717** [comment]
@henshan2002 尝试卸载bcolz并重新安装 看看能不能解决问题？

**Comment by henshan2002** [comment]
重新安装bcolz 依然无法解决
