### ISSUE TITLE
order_target_percent和order_target_portfolio卖出股票有bug

### ISSUE THREAD

**Issue by han14466** [ricequant/rqalpha#490]
## 1. RQAlpha的版本
3.4.4
## 2. Python的版本
3.7
## 3. 是Windows/Linux/MacOS or others?
Windows/Linux
## 5. 您出现的错误堆栈日志信息

https://www.ricequant.com/community/topic/43268/bug-order_target_percent 这个bug麻烦关注下
比如你有4000股，你使用order_target_percent，可能只卖1股，剩下3999股
这个不是平仓，是可以一股一股的卖。我的没有散股，是整股，被卖散了

其实你们在卖单的时候知道所以的仓位，你们可以除100得到的mod算结果，如果平仓就可以卖散股，因为整个股票的portfilio是可以拿到的。麻烦关注下这个bug

因为你们的新函数order_target_portfolio 也有这个bug

**Comment by Cuizi7** [comment]
已修复
