### ISSUE TITLE
滑点水平float值的含义是什么，能否提供一个设置的例子

### ISSUE THREAD

**Issue by zkx741481546** [ricequant/rqalpha#491]
文档中写了context.run_info_slippage表示滑点水平，但是这个值在回测框架中的具体含义如何理解？通常应如何设置

**Comment by Cuizi7** [comment]
滑点的含义可以参考[百度百科](https://baike.baidu.com/item/滑点)，rqalpha 中也是类似的含义，通过调整成交价格来模拟真实市场上的滑点。
