### ISSUE TITLE
get_nth_previous_trading_date函数

### ISSUE THREAD

**Issue by ccliuyang** [ricequant/rqalpha#493]
# 1. RQAlpha的版本
rqalpha4.0.0 windows python3.7.4
# 2. 源码问题
在rqalpha/apis/api_rqdatac.py中有调用get_nth_previous_trading_date函数，这个函是什么意思？和get_previous_trading_date有什么区别？并且在其他的地方也未见此函数的实现

**Comment by Cuizi7** [comment]
是个 bug，已在 develop 分支解决

**Comment by ccliuyang** [comment]
好的，看了下代码已经解决~~~
