### ISSUE TITLE
同样的代码用rqalpha跑，跟在ricequant.com上跑的结果不一样?

### ISSUE THREAD

**Issue by smilingpoplar** [ricequant/rqalpha#5]

**Comment by cedricporter** [comment]
请问可以提供下具体代码吗？

**Comment by smilingpoplar** [comment]
@cedricporter 比如跑：
`rqalpha run -f examples/multi_rsi.py -s 2006-08-01 -e 2016-08-08 -o result.pkl --plot`

**Comment by cedricporter** [comment]
`rqalpha run -f examples/multi_rsi.py -s 2006-08-01 -e 2016-08-08 -o result.pkl --plot` 这个是一样的，不一样的话，可能是你本地的data bundle有点老，可以`rqalpha update_bundle`更新下。

![qq20160811-0](https://cloud.githubusercontent.com/assets/1559563/17578154/28419a60-5fb8-11e6-9401-36e19b0be33d.png)


二八轮动是因为购买了指数。在 [ricequant.com](https://www.ricequant.com/) 的 lotsize 是1，rqalpha的 lotsize 是 100，因为钱不够开不了仓。后续会将 rqalpha 购买指数时的 lotsize 修改为 1。

**Comment by smilingpoplar** [comment]
@cedricporter 嗯，运行`multi_rsi.py`是一样了。

`lotsize`是啥？我可以在哪儿改？

**Comment by cedricporter** [comment]
指数的 lotsize 刚刚修改好了，您可以更新下 `pip install -U rqalpha`

**Comment by smilingpoplar** [comment]
@cedricporter 好了，👍
