### ISSUE TITLE
在全英文系统中的中文显示问题

### ISSUE THREAD

**Issue by yanghui1228** [ricequant/rqalpha#50]
在全英文系统中的中文显示问题，plot 结果显示中文乱码
![screen shot 2017-02-26 at 20 44 34](https://cloud.githubusercontent.com/assets/20747759/23339776/74b8269a-fc64-11e6-982e-c1419bf01399.png)

**Comment by HereticSK** [comment]
应该是`matplotlib`中文显示的问题吧，跟系统无关 https://segmentfault.com/a/1190000005144275

**Comment by yanghui1228** [comment]
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/font_manager.py:1297: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))

**Comment by wh1100717** [comment]
@yanghui1228 我们已经尽量兼容不同系统的中文字体设置来保证画出来的图字体显示正确，但是在纯英文系统中确实会出现中文乱码的问题，感谢反馈。

这个问题已经收集，会在下一个版本中解决~~

**Comment by cedricporter** [comment]
现在 develop 分支里面的，如果是没有可用的中文字体，会自动  Fallback 成英文的了

**Comment by wh1100717** [comment]
@yanghui1228 v0.3.10 已经Fix 在没有中文字体的情况下显示乱码的问题，现在回Fallback 为英文内容。
