### ISSUE TITLE
LogCapture需要返回自身对象

### ISSUE THREAD

**Issue by han14466** [ricequant/rqalpha#501]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
4.0.0

## 2. Python的版本
3.7

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

persist=true

## 5. 您出现的错误堆栈日志信息
[2018-06-01 00:00:00.000000] ERROR: user_system_log: 策略运行产生异常
Traceback (most recent call last):
  File "E:\quant\rqalpha_344\rqalpha\rqalpha\main.py", line 201, in run
    log_capture.replay()
AttributeError: 'NoneType' object has no attribute 'replay'
[2020-05-08 16:52:14.959146] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "E:\quant\rqalpha_344\rqalpha\rqalpha\main.py", line 201, in run
    log_capture.replay()
AttributeError: 'NoneType' object has no attribute 'replay'

class LogCapture:
    def __init__(self, logger):
        self._logger = logger
        self._capture_handler = CaptureHandler()
        self._handlers = None

    def __enter__(self):
        self._handlers = self._logger.handlers
        self._logger.handlers = [self._capture_handler]
        **return self**
这里需要return self回去，不然
log_capture.replay() 有空指针

**Comment by Cuizi7** [comment]
fixed in version 4.1.0
