### ISSUE TITLE
run_func函数和pd.Excelwriter函数冲突

### ISSUE THREAD

**Issue by hhetui** [ricequant/rqalpha#512]
RQAlpha 版本 3.4.0
Python 3.7.3
windows

问题：
writer = pd.ExcelWriter(up_file+'\\result\\single\\single.xlsx')
writer.save()
run_func()
是没有错误的
但是顺序如果变成
run_func()
writer = pd.ExcelWriter(up_file+'\\result\\single\\single.xlsx')
writer.save()
那么程序就会崩溃
保存的文件也会被损坏变成0kb

根本无法报出错误信息和日志，直接python核重启

**Comment by hhetui** [comment]
![image](https://user-images.githubusercontent.com/43748281/83256330-db2d0e80-a1e4-11ea-9d1d-0fb8c0854f60.png)

**Comment by Cuizi7** [comment]
麻烦测试下最新版本（4.1.4）是否还存在该问题
