### ISSUE TITLE
rqalpha 4.1.3中的logger.py和3.4版本不兼容

### ISSUE THREAD

**Issue by bluelightning99** [ricequant/rqalpha#522]
Python 3.7/rqalpha 4.1.3/Windows 10
rqalpha 4.1.3中的logger.py 只能在rqalpha中使用了。在没有进入rqalpha之前使用，就会报告异常。这会让基于rqalpha二次开发的工具，不能使用rqalpha的logger做统一的日志管理，希望能够修改回到3.4的logger模式，在调用rqalpha的回测功能前，也能使用rqalpha的logger来记录日志

**Comment by Cuizi7** [comment]
user_log 依赖策略上下文来获取“当前“时间，只能在策略中使用逻辑上似乎没毛病。
在策略外可以用 system_log 。
