### ISSUE TITLE
用于回测加密货币ohlcv数据源问题

### ISSUE THREAD

**Issue by agz1990** [ricequant/rqalpha#524]
看到自定义cvs数据源示范但是没有具体说明格式。如果基础开盘，收盘价数据都是自己采集到数据库的，请问要组装成标准H5数据放到数据源文件夹里面要如何做。 我想要支持BTC/USDT, ETH/USDT等多种交易对子

**Comment by Cuizi7** [comment]
可以参考 rqalpha.data.base_data_source.storages 中读取文件的逻辑以了解 rqalpha 内置 bundle 数据的格式。亦可以重新实现 DataSourceInterface。
