### ISSUE TITLE
为什么电脑每次多启动几次RQ，系统机会报memoryerror的错误？

### ISSUE THREAD

**Issue by lzhw520110** [ricequant/rqalpha#53]
如题，使用RQ只要超过三次，再次启动RQ系统就会报memoryerror的错误，需要重启Spyder才行，是不是每次启动RQ系统读取数据会消耗很多内存？请问怎么破？

**Comment by wh1100717** [comment]
@lzhw520110 你试试通过pycharm 或者别的启动RQAlpha 会产生这个问题吗？ 如果不能的话，那有可能是 Spyder 存在内存泄漏的问题。

https://github.com/spyder-ide/spyder/issues?utf8=%E2%9C%93&q=memory

**Comment by wh1100717** [comment]
No Resp && Close this issue
