### ISSUE TITLE
position类下的属性closable算法问题

### ISSUE THREAD

**Issue by quanterli** [ricequant/rqalpha#543]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 5. 您出现的错误堆栈日志信息
 @property
    def closable(self):
        # type: () -> int
        """
        可平仓位
        """
        
        order_quantity = sum(o for o in self._open_orders if o.position_effect in (
            POSITION_EFFECT.CLOSE, POSITION_EFFECT.CLOSE_TODAY, POSITION_EFFECT.EXERCISE
        ))
       
        return self.quantity - order_quantity

sum(o for o in self._open_orders if o.position_effect in (
            POSITION_EFFECT.CLOSE, POSITION_EFFECT.CLOSE_TODAY, POSITION_EFFECT.EXERCISE
        ))
order应该没法直接相加吧。还是我理解错误。

**Comment by Cuizi7** [comment]
fixed
