### ISSUE TITLE
每天开盘后，收盘前执行出现错误

### ISSUE THREAD

**Issue by geuzkp** [ricequant/rqalpha#57]
每天开盘后，收盘前执行出现错误 ，rq版本('Current Version: ', (0, 3, 12))
UnboundLocalError: local variable 'signature' referenced before assignment

**Comment by wh1100717** [comment]
@hzliu 貌似像是regression?  @geuzkp 多谢反馈 明天我们check一下~

**Comment by myz8110** [comment]
同样的代码,scheduler.run_monthly用了会报错,放在handle_bar里就能运行是怎么回事??
也是出现UnboundLocalError: local variable 'signature' referenced before assignment
