### ISSUE TITLE
买入“指数”却没有任何错误提示出现

### ISSUE THREAD

**Issue by zhang-ray** [ricequant/rqalpha#585]
通过策略找到一个`股票` 代码，竟然可以成功买入(没有其他错误提示)。  后来发现这支`股票`是 `深证100` (399330.XSHE) , 不知道算不算bug？

## 1. RQAlpha的版本
Current Version:  4.2.4

## 2. Python的版本
Python 3.9.0

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
```
            order_shares('399330.XSHE', shares)
```

## 5. 您出现的错误堆栈日志信息
N/A

**Comment by Cuizi7** [comment]
不是 bug，rqalpha 支持直接买入指数。

**Comment by zhang-ray** [comment]
那买入 `沪深300` 的意义是啥？

**Comment by zhang-ray** [comment]
想问一下：
1. 不知道买入指数（比如 沪深300、上证综指）设计之初有没有什么意义呢？ 
2. 如果可以买入指数的话，请问有没有什么接口可以来判断code是否为股票或者指数？

多谢

**Comment by hzliu** [comment]
对于大类配置研究是很有用的。
instrument的type字段指明了该合约的类型

**Comment by zhang-ray** [comment]
> 
> 
> 对于大类配置研究是很有用的。
> instrument的type字段指明了该合约的类型

OK, 多谢！
