### ISSUE TITLE
order set_state中order_status字段错误，在get_state中为status字段

### ISSUE THREAD

**Issue by orxg** [ricequant/rqalpha#588]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
4.2.5
## 2. Python的版本
3.8.5
## 3. 是Windows/Linux/MacOS or others?
Windows10
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
order set_state中'order_status'字段错误，在get_state中为status字段,在使用incremental进行模拟的时候会报错

**Comment by orxg** [comment]
把order_status改成status就可以正常运行了

**Comment by Cuizi7** [comment]
多谢反馈，已在develop分支修复。
