### ISSUE TITLE
可以对指数进行回测吗

### ISSUE THREAD

**Issue by JavarisLyn** [ricequant/rqalpha#589]
## 1. RQAlpha的版本
4.2.5

## 2. Python的版本
3.8.0

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
把accounts里改成"index": 1000000，就会报错 NameError: name 'scheduler' is not defined

**Comment by Cuizi7** [comment]
可以对指数进行回测，指数回测需在 accounts 中设置 STOCK 账户的初始资金。
