### ISSUE TITLE
Ubuntu16.04 画不了图 Python3.6

### ISSUE THREAD

**Issue by yutiansut** [ricequant/rqalpha#59]
```
 rqalpha run -f ./examples/buy_and_hold.py -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000 --benchmark 000300.XSHG --plot
2016-06-01 INFO init
[2017-03-10 12:32:01.739841] WARN: system_log: Missing Chinese fonts. Fallback to English.
```

**Comment by wh1100717** [comment]
@yutiansut 这个不是报错  是提示没有找到中文字体，所以默认显示英文内容。并没有从你提供的信息中看到任何错误，按理来说，图形应该是显示了的。

**Comment by yutiansut** [comment]
是的 没有中文字体 但是py3.6真的不出图，py2.7.12就能出图  然后我又去win10上试了下 py3.6还是不出图  matplotlib都装了 还是没用 不知道为啥

**Comment by wh1100717** [comment]
@yutiansut 多谢反馈 我们确认后会在近期修复~~

**Comment by lijiecong** [comment]
rqalpha支持3.6了？ 我文档里看到只支持3.4.
我用conda创建虚拟环境3.4，很多依赖的包都要手动安装，比如requests，matplotlib等。
这个能做成自动依赖吗？不然手动安装比较麻烦。

**Comment by wh1100717** [comment]
@lijiecong rqalpha 尽量做到支持 2.7 3.4 3.5 3.6 不过貌似matplotlib 在3.6下有一些问题，现在还在解决。

另外，依赖包可以通过 `pip install rqalpha` 自动安装的。 本来就是自动依赖的啊

**Comment by lijiecong** [comment]
@wh1100717  我是用pip安装的rqalpha， 但在conda创建的虚拟环境3.4中运行 pip安装的。照理应该都会安装所有依赖。我anaconda版本是4.3.1 64bits，  ubuntu16.04

**Comment by cedricporter** [comment]
创建一个 ~/.matplotlib/matplotlibrc ，填入下面代码，就可以在 3.6 进行画图了
```
backend      : GtkAgg
```
![qq20170324-151144](https://cloud.githubusercontent.com/assets/1559563/24284098/5e59c850-10a4-11e7-9fd9-36a6c6cbe6ef.png)

**Comment by wh1100717** [comment]
在安装FAQ相关文档中增加了这种情况下如何解决的描述。
