### ISSUE TITLE
Error: No such command 'download-bundle'.

### ISSUE THREAD

**Issue by shift37** [ricequant/rqalpha#594]
最新版本rqalpha

(rqalpha) C:\Users\admin>rqalpha download-bundle
Usage: rqalpha [OPTIONS] COMMAND [ARGS]...

Error: No such command 'download-bundle'.

**Comment by mar-heaven** [comment]
4.3.1 版本是可以的，可能是click版本的问题？命令行输入 rqalpha 看一下返回
![image](https://user-images.githubusercontent.com/26325127/106443510-851d1300-64b7-11eb-947e-950b55200e75.png)
有的click版本是下划线

**Comment by shift37** [comment]
![image](https://user-images.githubusercontent.com/3881509/108689499-1ec66600-7534-11eb-9747-c702838160b4.png)

rqalpha 4.6.0版本，是download-bundle函数去掉了吗？

**Comment by mar-heaven** [comment]
> ![image](https://user-images.githubusercontent.com/3881509/108689499-1ec66600-7534-11eb-9747-c702838160b4.png)
> 
> rqalpha 4.6.0版本，是download-bundle函数去掉了吗？

现在最新的是4.3.2
