### ISSUE TITLE
rqalpha update-bundle failed  without rqdatac

### ISSUE THREAD

**Issue by walkacross** [ricequant/rqalpha#596]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
RQALPHA 4.3.1
## 2. Python的版本
python3.8

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha update-bundle 无法运行

在没有安装rqdatac的情况下， 只能download -bundle 不能update

**Comment by mar-heaven** [comment]
因为update 是需要rqdatac的api来进行数据获取的，所以需要先下载rqdatac
