### ISSUE TITLE
Rqalpha属于哪个产品。有没有提供网址可以一览？

### ISSUE THREAD

**Issue by kaybinwong** [ricequant/rqalpha#597]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by mar-heaven** [comment]
就是这个仓库，还有对应的doc。https://www.ricequant.com/welcome/ 公司的官网也有基于rqalpha开发的量化平台
