### ISSUE TITLE
止损单、止盈单

### ISSUE THREAD

**Issue by ElevenL** [ricequant/rqalpha#6]
1、请问如何下止损单和止盈单？
2、如果我设置最大持股天数，到达时间了，以开盘价或者收盘价卖出，是否可以实现？
谢谢解答！

**Comment by cedricporter** [comment]
1. 目前仅支持MarketOrder和LimitOrder
2. 如果要以开盘价成交，需要修改下代码。或者可以使用[ricequant](www.ricequant.com)使用分钟回测，就可以按开盘价了。
