### ISSUE TITLE
Are there English translations for this platform?

### ISSUE THREAD

**Issue by BasharAG** [ricequant/rqalpha#61]
I read some of the translation, and the platform sounds wonderful. Are there any translation efforts underway?

**Comment by wh1100717** [comment]
@BasharAG 

RQAlpha is a algorithmic trading system including data source access portal, event handler, customizing API and trading service gateway.

However, we focus on Chinese Finance Market currently, Global Market support may be our next step.

RQAlpha using [babel](http://babel.pocoo.org/en/latest/) for i18n and u can run RQAlpha with `--locale en` to get the English version information.

And.... we are working on English Documentation >_<

**Comment by timkpaine** [comment]
@wh1100717 any update on english documentation?

**Comment by timkpaine** [comment]
I just see on README - 🚫 English Doc

**Comment by rthickling** [comment]
+1 English docs/translation!

There is a very large international trading crowd who would love to use RQAlpha who are English literate even if not English speaking.

**Comment by Cuizi7** [comment]
@rthickling thank you for your attention, we are very honored that RQAlpha can create value for international traders. However, as a small company, we don’t have enough resources for maintaining the english document, we are still only focusing on chinese market.
