### ISSUE TITLE
模拟交易时，同步持仓时发现只能同步持仓数量，不能同步其他信息

### ISSUE THREAD

**Issue by liwanqiang** [ricequant/rqalpha#627]
我是这样调用的：
self.env.set_portfolio(Portfolio({'STOCK': cash}, all_positions))， 在查看Portfolio源码时发现：

 for order_book_id, quantity in init_positions:
            account_type = self.get_account_type(order_book_id)
            if account_type in account_args:
                account_args[account_type]["init_positions"][order_book_id] = quantity

这样就只能有持仓量，如果我还想同步成本价就不行了。

**Comment by Cuizi7** [comment]
init_positions 仅支持传入初始持仓数量，如果您希望恢复全部持仓信息的话可以使用 RQAlpha 的持久化相关功能，通过 Portfolio.set_state 恢复完整的 portfolio 状态。
