### ISSUE TITLE
有没有在python中update的方法??

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#63]
如题.非得在这里下载rqalpha的更新吗??

**Comment by wh1100717** [comment]
sorry 不太明白你说的是什么意思？
正常使用RQAlpha 直接 `pip install rqalpha` 就可以了。 如果是升级的话 `pip install -U rqalpha` 就可以了。

**Comment by myz8110** [comment]
自学新手,明白了.
""正常使用RQAlpha 直接 pip install rqalpha 就可以了。 如果是升级的话 pip install -U rqalpha 就可以了。这句其实可以假如官方文档"豪华午餐"了.

**Comment by wh1100717** [comment]
这个其实是Python 和pip 相关的用法。 RQAlpha 是一个标准的Python库 其用法和其他是一致的。
