### ISSUE TITLE
发现一枚严重的bug

### ISSUE THREAD

**Issue by peyoo** [ricequant/rqalpha#632]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
4.3.3 

## 2. Python的版本
3.7

## 3. 是Windows/Linux/MacOS or others?
MacOS

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
在before_trading 或 handle_bar中执行下面两行代码，会发现两次结果是不一样的
    print(rq.apis.history_bars('300179.XSHE', 10, '1d', 'close'))
    print(rq.apis.history_bars('300179.XSHE', 10, '1d', 'close'))

## 5. 您出现的错误堆栈日志信息
错误原因很简单，函数 _all_day_bars_of 缓存了数据，在adjust_bars 复权修改了数据，重复的复权导致每次结果都不一样。
应该修改为复权需要改变数据时，copy数据。很奇怪，这么严重的错误怎么还存在，还是我理解有误。

**Comment by Cuizi7** [comment]
感谢反馈，bug 确实存在，该 bug 在 4.3.1 版本的改动中被引入，于 45d41cdaedd6be4fcbefe4297225f5f140cde6e7 被修复，您更新下 rqalpha 版本即可。
