### ISSUE TITLE
如何换源成tushare等其他数据源？

### ISSUE THREAD

**Issue by yinxiuqu** [ricequant/rqalpha#636]
官方文档有一个过期的50行更换tushare数据源的办法，但是那个tushare还是过去的老版本的函数，现在已经是Pro版本了。是否有更换成tushare或者其他数据源的办法呢？最好是有现成的mod可以使用。如果不能更换数据源， 那这个rqalpha和米筐官方的本地回测框架又有什么区别了？

**Comment by Cuizi7** [comment]
文档中的范例是一个demo，目的是向开发者展示 DataSource 的概念以及如何通过实现 DataSource 的方法接入数据源，并不是现成的可使用的代码，作为演示，针对的是新版本还是老版本的 tushare 关系不大。
