### ISSUE TITLE
关于 history_bars 收盘价与券商软件中不一致的情况

### ISSUE THREAD

**Issue by cosnis** [ricequant/rqalpha#64]
我在 handle_bar 使用以下代码尝试获取历史收盘时发现
```
        prices = history_bars(stock, 2, '1d', ['datetime', 'close'])
        print stock, prices
```

输出的 20160414 收盘价是 9.0333
000001.XSHE [(20160414000000,  9.0333) (20160415000000,  9.0667)]

但是券商和雪球中不复权收盘价都是 10.84

但是时间维度上较近期的数据又是准确的

输出的 20170314 收盘价 9.44
000001.XSHE [(20170314000000,  9.44) (20170315000000,  9.48)]

同券商和雪球

**Comment by cosnis** [comment]
补充截图:
![1](https://cloud.githubusercontent.com/assets/120555/24073096/aec1a028-0c2c-11e7-8d6b-b4f1dbf508fd.jpg)

**Comment by cedricporter** [comment]
我们仅根据拆分对历史交易数据做了前复权，并未加入股息分红因素，因为单独计算股息分红的影响可以让您的策略收益计算更加准确。

**Comment by cosnis** [comment]
我选择看的是不复权数据, 可以在截图中看到~

**Comment by cedricporter** [comment]
如果我们在 bundle 中存储不复权数据，然后在回测过程中，站在当时动态进行前复权，这样确实会更加的准确。这个也有 plan 。

**Comment by cosnis** [comment]
666

**Comment by hzliu** [comment]
分支 feature/orig_price 有兴趣可以看看

@cosnis

**Comment by wh1100717** [comment]
2.2.x 版本已经更新为 原始数据 + 复权因子的方式
