### ISSUE TITLE
如何让get_price, order_target_percent在回测中使用本地历史数据

### ISSUE THREAD

**Issue by paulhybryant** [ricequant/rqalpha#657]
请问如何能够让get_price(), order_target_percent()这样的API在读取标的价格信息的时候，从一个本地的数据源读取，而不一定要通过rqdatac？

**Comment by Cuizi7** [comment]
order_target_percent 默认是从 DataSource 获取行情的，默认的 DataSource 是从本地 bundle 读取数据的。
get_price 是对 rqdatac api 的封装。希望从本地读取数据的话可以用 history_bars 代替。
