### ISSUE TITLE
发现一枚bug: config.extra.context_vars not working if vars used in init()

### ISSUE THREAD

**Issue by paulhybryant** [ricequant/rqalpha#663]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 5. 您出现的错误堆栈日志信息

main.py, around line 190

context.extra.context_vars are read and set after user_strategy.init() is called.
If vars in context_vars is used in init(), it will fail.

**Comment by mar-heaven** [comment]
has fixed in 4.6.0
