### ISSUE TITLE
在incremental mod开启，按照时间分段跑，即使在策略文件中的init函数中重新定义的相同的变量如contex.s1，用print打印该变量发现永远是第一次定义的值

### ISSUE THREAD

**Issue by xubinlaile** [ricequant/rqalpha#688]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by xubinlaile** [comment]
而且在不同的时间段开始时，init函数中的print语句在日志也显示不出来

**Comment by Cuizi7** [comment]
init 只会在回测初始化时执行一次，希望每天执行的逻辑建议放在 before_trading 中。
