### ISSUE TITLE
wiki ：使用PyCharm进行单步调试。在window中如何进行debug设置

### ISSUE THREAD

**Issue by wudenggang0** [ricequant/rqalpha#7]
wiki ：使用PyCharm进行单步调试。
在window中如何进行第二步debug设置（下载zip格式）
![pycharm debug](https://cloud.githubusercontent.com/assets/3587832/17559904/820bc6f8-5f52-11e6-8719-f3596777c494.png)

**Comment by cedricporter** [comment]
`python -m rqalpha run -f ...` 等价于 `rqalpha run -f ...`。

即你可以在 Script 填上 python.exe 的路径，然后 Script Params: 改成 `-m rqalpha run -f ...` 这样试一下

**Comment by wudenggang0** [comment]
按照你的设定方法，同样报错。script的地方应该是设定rqalpha的位置（script入口）。
![pycharm debug](https://cloud.githubusercontent.com/assets/3587832/17590150/20bc6dd0-600b-11e6-8603-f49269c22d69.png)
![pycharm debug](https://cloud.githubusercontent.com/assets/3587832/17590114/f59ea118-600a-11e6-9ee9-0fee5b70269b.png)

**Comment by cedricporter** [comment]
这样的话你找一下源码里面有个 __main__.py ，你在Script填上这个文件就好。我这里没有Windows环境，不好验证。

**Comment by wudenggang0** [comment]
使用start.py方法可以Run成功，但是哪看结果呢？
![pycharm debug](https://cloud.githubusercontent.com/assets/3587832/17811198/0346f640-6654-11e6-97ec-6e5dbf848cae.png)
![pycharm debug 1](https://cloud.githubusercontent.com/assets/3587832/17811197/03402630-6654-11e6-9874-1227e143b3e9.png)

**Comment by cedricporter** [comment]
如果需要hack源码并且调试自己的源码。

需要在 源码目录 `pip install -e .` 这样来安装 rqalpha 。

**Comment by wh1100717** [comment]
在 Python 3.5 3.6 下 对应的 Scripts 目录里面应该是包含 `rqalpha-script.py` 文件的。 应该是可以作为入口文件的。 可以尝试一下

**Comment by myz8110** [comment]
@wh1100717 我刚下载了最新版的PyCharm的community版本,画风和rqalpha文档的描述的差异巨大,且我Python版本为3.6,rqalpha版本为最新版2.2.3,但找不到 对应的 Scripts 目录里面的 rqalpha-script.py文件

**Comment by myz8110** [comment]
btw,我是windows7

**Comment by cfz87862529** [comment]
你好，我的是windows环境，在最新的rqalpha版本2.2.4下未发现rqalpha-script.py文件。

**Comment by wh1100717** [comment]
@cfz87862529 那就找一下对应的入口文件  http://rqalpha.io/zh_CN/latest/intro/under_ide.html#rqalphaconda

**Comment by binosun** [comment]
@cfz87862529 这样配置试试
![image](https://user-images.githubusercontent.com/17984207/27478663-2838ef08-5843-11e7-972d-66b19d18429d.png)

**Comment by wangmeng2017** [comment]
![image 004](https://user-images.githubusercontent.com/25503884/30581804-04ac581c-9d54-11e7-94bc-6819e390bc47.png)
rqalpha.exe存在，但是在如图的界面下看不到，手工输入的话“OK”按钮是灰色的无法保存。难道是我哪里设置错了吗？

**Comment by yuandi0823** [comment]
@cedricporter   rq3.0.6  py2.7 pycharm debug
<img width="555" alt="1510212128 1" src="https://user-images.githubusercontent.com/1833393/32593199-efb1ea2c-c561-11e7-8d5b-9e7211044290.png">
**error**
D:\Work\VM\Anaconda2\envs\A2ENV\python.exe "D:\Work\IDE\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 58546 --file D:/Work/XProject/PyProject/pyqt/t1/start.py run -f ./t1/h4.py -d D:/Work/DB/rqalpha/bundle/ -s 2016-06-01 -e 2016-12-01 --account stock 100000 --benchmark 000300.XSHG --plot
pydev debugger: process 12488 is connecting

Connected to pydev debugger (build 172.4343.24)
Error: no such option: --multiproc

Process finished with exit code 2

**Comment by lixuefeng613** [comment]
![image](https://user-images.githubusercontent.com/12976473/35212804-53ed85b4-ff96-11e7-8c42-40ba52f3ca71.png)
新版本pycharm改了，我选择了模块名字，
下面的参数再填写，就可以dedebug了
![image](https://user-images.githubusercontent.com/12976473/35212888-a838603a-ff96-11e7-8cc0-fff808330686.png)

`run -f buy_and_hold.py -d ./bundle/ -s 2018-01-18 -e 2018-01-21 --account stock 100000 --benchmark 000300.XSHG`

**Comment by hzliu** [comment]
:)
thanks

**Comment by a5601564** [comment]
config = {
    "base": {
        "data_bundle_path": "C:\\Users\\Administrator\\.rqalpha\\bundle",
        "start_date": "2016-06-01",
        "end_date": "2016-12-01",
        "benchmark": "000300.XSHG",
        "accounts": {
            "stock": 100000
        }
    },
    "extra": {
        "log_level": "verbose",
    },
    "mod": {
        "sys_analyser": {
            "enabled": True,
            "plot": True
        }
    }
}



run_func(init=init,  handle_bar=handle_bar, config=config)


原来还可以这么玩的，就不用配置这些垃圾玩意了
