### ISSUE TITLE
rqalpha.order_value(xxx.XSHG, xxx)  金额不足会按最大限度下单

### ISSUE THREAD

**Issue by publi-qv** [ricequant/rqalpha#711]
1. RQAlpha的版本
 4.8.0
 2. Python的版本
 3.10
3. 是Windows/Linux/MacOS or others?
Windows
 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
 5. 
 例子：对 000001.XSHG 股票代码进行交易
           下单金额为10000
            当天开盘价为3.74
           通过接口 rqalpha.order_value ( 000001.XSHG , 10000 ) 计算出的持有股数为2700，实际计算10000/3.74=2673.79679144385，
       1手是100股，在金额足够以及交易股数是100股数的倍数，实际计算的持股数应为2600，请问是否需要设置其他参数来过滤这个
        错误还是有其他的解决方法？

6. 您出现的错误堆栈日志信息

**Comment by mar-heaven** [comment]
@publi-qv 默认用的收盘价
