### ISSUE TITLE
能否在1m回测下提供一个直接跳到下一个交易日的功能，以加快回测速度

### ISSUE THREAD

**Issue by huangdongqin** [ricequant/rqalpha#715]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
4.8.0
## 2. Python的版本
3.9
## 3. 是Windows/Linux/MacOS or others?
windows

**Comment by Cuizi7** [comment]
现在分钟回测是以日为单位加载行情数据的，即使跳过剩下的分钟线，加载的耗时并不能省，我感觉应该对回测速度的提升帮助不大。如果改动加载数据的逻辑的话，一是要有途径能够让策略告知框架将会使用多少分钟线，另外也需要重构 bundle 的组织方式，这个工作量太大，暂时没有计划做哈。
