### ISSUE TITLE
关于rqalpha/__init__.py第47行main.update_bundle(data_bundle_path, confirm)改动建议

### ISSUE THREAD

**Issue by liulizi** [ricequant/rqalpha#73]
我用的是windows系统，运行报错。
这一句原代码是：
main.update_bundle(data_bundle_path, confirm)
建议改为：
main.update_bundle(data_bundle_path, confirm=confirm)

**Comment by wh1100717** [comment]
对外暴露的API 是在 `__init__.py` 下面。

如果您想代码中直接使用 `update_bundle`  代码如下：
```python
def update_bundle(data_bundle_path=None, locale="zh_Hans_CN", confirm=True):
    from . import main
    main.update_bundle(data_bundle_path=data_bundle_path, locale=locale, confirm=confirm)
```

使用方式如下:

```python
from rqalpha import update_bundle

update_bundle(target_path)
```

**Comment by wh1100717** [comment]
不过现在最新版本 `update_bundle`  代码执行会报错，这个是一直问题，已经解决，下一个版本发布会解决。

**Comment by liulizi** [comment]
好的

**Comment by wh1100717** [comment]
RQAlpha 2.0.0b0 已经修复 update_bundle 出错的问题。

您可以使用 `pip install -U rqalpha==2.0.0b0` 来升级试用
