### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by kerwinxu** [ricequant/rqalpha#735]
我用pip安装的最新版。

    from rqalpha.api import industry         # 行业股票列表
ImportError: cannot import name 'industry' from 'rqalpha.api' (D:\anaconda3\lib\site-packages\rqalpha\api.py)

另外 from rqalpha.api import sector   这个也导入不了。

rqalpha version
Current Version:  4.11.2

**Comment by Cuizi7** [comment]
`from rqalpha.apis import get_industry`
