### ISSUE TITLE
RQAlpha Documentation Extension

### ISSUE THREAD

**Issue by wh1100717** [ricequant/rqalpha#74]
* Using RQAlpha
  * Introduction
  * Installation
  * Getting Started
  * Tutorial
  * API
  * Resources
    * Ricequant Video Tutorial
    * Strategy Demos
    * OutOfTheBox Virtual Machine Image
    * Other
  * FAQ
* Finding RQAlpha Mod
  * How to find a RQAlpha Mod
  * install/uninstall/enable/disable Mod
  * System Mod Introduction
  * Third-party Mod Reference
* Creating Your Own Mod
  * Getting Started
  * Mod Config
  * Sub/Pub Event
  * Get What you need from Environment
  * Cli Injection
  * Publishing Your Mod
  * Full API Documentation
* Contributing
  * How to open an issue
  * How to submit a pull request
  * Testing

额外创建一个 rqalpha-doc 项目， 引用rqalpha 作为sub repo， 专门用来存放和编写文档

**Comment by handsomu** [comment]
OK, Let's do this!

**Comment by wh1100717** [comment]
* Using RQAlpha
  * Introduction
  * Installation
  * Getting Started
  * Tutorial
  * API
  * Resources
    * Ricequant Video Tutorial
    * Strategy Demos
    * OutOfTheBox Virtual Machine Image
    * Other
  * FAQ
* Finding RQAlpha Mod
  * How to find a RQAlpha Mod
  * install/uninstall/enable/disable Mod
  * System Mod Introduction
* Creating Your Own Mod
  * Getting Started
  * Mod Config
  * Sub/Pub Event
  * Get What you need from Environment
  * Cli Injection
  * Publishing Your Mod
  * Full API Documentation
* Contributing
  * How to open an issue
  * How to submit a pull request
  * Testing
