### ISSUE TITLE
为什么不给 get_ex_cum_factor 添加 lru_cache 呢？

### ISSUE THREAD

**Issue by Daic115** [ricequant/rqalpha#741]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
'4.11.3'
## 2. Python的版本
'3.8.10'
## 3. 是Windows/Linux/MacOS or others?
Windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
使用 [示例RSI策略](https://rqalpha.readthedocs.io/zh_CN/latest/intro/examples.html#rsi)，12年数据进行回测：
```python
config = {
    "base": {
        "start_date": "2008-06-01",
        "end_date": "2021-12-01",
        "benchmark": "000300.XSHG",
        "data_bundle_path": "./rq_data/bundle",
        "accounts": {
            "stock": 100000
        }
    },
    "mod": {
        "sys_analyser": {
            "enabled": True,
            "plot": True
        },
        'incremental': {'enabled': False},
    }
}
from rqalpha import run_func
run_func(init=init, handle_bar=handle_bar, config=config)
```
通过pycharm内置的Profile进行性能统计，总用时 20.7s，发现 `get_ex_cum_factor` 用时占比非常高：
![image](https://user-images.githubusercontent.com/39031965/196892989-b25f989b-458f-4f78-b8a2-2b66aeb069cc.png)

在[data_source.py#L250](https://github.com/ricequant/rqalpha/blob/master/rqalpha/data/base_data_source/data_source.py#L250)添加 `@lru_cache(2048)` 后，总用时为 10.4 秒， 回测结果并未变化；

想请问下这种频繁io的地方为什么没有用cache呢？还是因为对其他类型的策略回测有影响？

**Comment by Cuizi7** [comment]
谢谢提醒，develop 分支已加。
