### ISSUE TITLE
建议在期货回测中增加一个选项，允许按照结算价计算每日 PnL

### ISSUE THREAD

**Issue by LawrentChen** [ricequant/rqalpha#745]
## 1. RQAlpha的版本
4.12.0

## 2. Python的版本
3.10

---
目前期货日频回测结果中：
- future_positions 中各个合约的 **last_price** 字段都是当日收盘价而非结算价；
- future_account 中对应的 **daily_pnl** 也都是根据合约收盘价逐日差分计算所得

建议再增加一个回测选项（可能在 mod_sys_accounts 里？），允许按照合约结算价计算，这样也才更贴近逐日盯市的期货实际结算规则。

_已向贵司 staff 反馈并得到回复说产品会调研排期了，就是忍不住想在 issue 这边留个名[奸笑]😝_

**Comment by Cuizi7** [comment]
已在开发中

**Comment by Cuizi7** [comment]
已在开发中

**Comment by LawrentChen** [comment]
谢谢！期待中😆

**Comment by Cuizi7** [comment]
已有该功能。
