### ISSUE TITLE
希望提供比例法调整的连续合约

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#750]
看米筐文档，内置的连续合约是加减调整，不是比例法调整。
希望提供比例法调整的连续合约。

**Comment by Cuizi7** [comment]
感谢关注。rqdata [有提供对应的数据](https://www.ricequant.com/doc/rqdata/python/futures-mod.html#futures-get-dominant-price-获取期货主力连续合约行情数据)，RQAlpha暂无计划支持交易对应的合约。
