### ISSUE TITLE
日线撮合机制问题

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#752]
根据文档，日线回测时，默认撮合价格是当日收盘价。
我用如下方式来下单：

scheduler.run_weekly(rebalance, tradingday=1)
def rebalance(context, bar_dict):
    在这里下单

根据文档，rebalance将在周一收盘时触发，此时全天交易已经结束，现实中已经不可能撮合订单了，这样的回测岂不是不符合实际？
不知我理解得对否？

**Comment by Cuizi7** [comment]
日回测是是把每个交易日抽象成一个时间点，handle_bar 和 scheduler 中的逻辑都在这一个时间点内发生。

**Comment by quant2008** [comment]
不是一个时点吧，如果你假设是开盘是触发handle_bar，那么就不能拿到当日的ohlc，但下单可在当日成交。如果你假设是在收盘时触发，就可以触发时拿到ohlc，但下单不能在当日成交。这个假设是很重要的，我感觉rqalpha是假设在收盘触发，但又允许触发时下单成交，这就矛盾了。

**Comment by Cuizi7** [comment]
日/分钟/tick回测是对实盘不同程度的抽象，颗粒度越粗离交易执行越远但运行效率越高；每个级别适用于不同场景，不能包揽是实盘前的所有模拟工作。

日回测适用于测试对持仓收益敏感、对交易收益不敏感的模型，如低换手的选股策略等。对于此类策略来说，使用日回测的意义在快速验证模型的选股能力。至于实盘交易中如何选择开平仓时间点、如何降低交易成本就是执行层面的研究课题了。如果认为close撮合与真实交易情况相差较远，亦可以选择 signal 模式，自定义一个在实盘中 tradable 的成交价格（如 twap/vwap）。

如果要验证交易型的策略，或者想要一并验证配置型策略的交易逻辑，则应该选择分钟或tick级别的逻辑。

如果是要验证高频交易，则 rqalpha 可能不适用，这种情况下应当给予更加细粒度的数据（如 lv2）执行模拟。

以上说明想要表达的就是日回测中纠结 handle_bar 是在开盘还是收盘没有意义，因为这是简化掉执行层面的模型研究。
