### ISSUE TITLE
现在plot不支持显示benchmark曲线了？

### ISSUE THREAD

**Issue by sloth2012** [ricequant/rqalpha#76]
![image](https://cloud.githubusercontent.com/assets/4048815/24490206/2bb26c22-1554-11e7-8dc4-09afa867da16.png)
目前我参考源码，在jupyter notebook中实践了下，最后plot出来的结果只有上图这种，没有像之前https://www.zhihu.com/question/54593434中
![image](https://cloud.githubusercontent.com/assets/4048815/24490292/8e14559c-1554-11e7-8ac4-a56247bfba8b.png)的另一条benchmark线，这个是现在屏蔽了吗？
补充 用的是2.0.2版本

**Comment by wh1100717** [comment]
plot 没有屏蔽什么东西...  你能一下你的配置信息 或者启动参数 以及示例策略吗？  好帮助我们查询哪里出了问题。

**Comment by sloth2012** [comment]
@wh1100717 源码的mod/rqalpha_mod_sys_analyser/plot.py中第51行，``` benchmark_portfolios = result_dict.get("benchmark_portfolios")```，这个我发现result_dict里面没有传递这个数据，所有的源码遍历搜寻，也没发现几处相关的代码。
之前问题的提问源码如下：
```python
from rqalpha import run
config = {
      "base": {
          "strategy_file": "/Users/lx/Programs/research/rqalpha/rqalpha/examples/buy_and_hold.py",
          "start_date": "2014-05-01",
          "end_date": "2014-12-01",
          "stock_starting_cash": 100000,
          "benchmark": "000300.XSHG",
      },
      "extra": {
          "log_level": "error",
      },
        "mod": {
            "sys_progress": {
                "enabled": False,
            },
            "sys_analyser": {
                "plot": True,
                "plot_save_file":"./plot"
            },
#       'tushare':{
#             "lib": 'rqalpha_mod_tushare',
#             "enabled": True,
#             "priority": 100,
#             }
    }
  }
result = run(config)
```

**Comment by wh1100717** [comment]
@sloth2012 确实如您所说~  这是个 2.0.0 重构产生的一个regression bug

**Comment by wh1100717** [comment]
@sloth2012 已经修复，会在下一个小版本 release 时同时可用。

**Comment by sloth2012** [comment]
@wh1100717 多谢哈、
