### ISSUE TITLE
期货日线回测，open_auction中下单，滑点不起作用

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#761]
期货日线回测，open_auction中下单，滑点不起作用，成交结果还是无滑点的。
虽然文档说以集合竞价开盘价成交，但现实是若在集合竞价结束的瞬间下单，会有滑点。
这种场景还是有的，如果米筐在这里加上滑点功能，会适用更多现实场景。

以上实际是开盘价撮合成交的场景，对这个场景的进一步改进是增加限价单功能。
即开盘发出的限价单，考虑当日全天的ohlc，进行撮合。这样就完美了。这种场景就不必弄分钟级回测了，会快很多。

**Comment by Cuizi7** [comment]
相关讨论见 #752
