### ISSUE TITLE
is_suspended()

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#77]
is_suspended()函数是不是不能用啊??
我在使用该函数时,报错"name is_suspended() is not defined"
def initialize(context):
    pass
def handle_bar(context, bar_dict):
    su=is_suspended('000001.XSHE')
    print(su)

**Comment by wh1100717** [comment]
@myz8110 你使用的RQAlpha的版本是？ 请使用最新版本(>=2.0.5) 试一下

**Comment by myz8110** [comment]
@wh1100717  我的版本是(0,3,14),最新版本会不会改动太厉害??

**Comment by wh1100717** [comment]
@myz8110 新版本改动还是很大的 https://github.com/ricequant/rqalpha/issues  http://rqalpha.readthedocs.io/zh_CN/latest/history.html

建议还是用新版本的RQAlpha
