### ISSUE TITLE
策略能否增加 用csv 文件进行回测

### ISSUE THREAD

**Issue by louis-xuy** [ricequant/rqalpha#779]
回测的时候用自己本地csv文件进行回测，

**Comment by Cuizi7** [comment]
如果指的是从csv中读取目标持仓或者交易信号的话这通过一个简单的策略就可以实现，不需要框架负责。

**Comment by louis-xuy** [comment]
是开高低收等数据，直接用csv 或者通过pandas 传给系统进行回测， 不用自带的数据源

**Comment by Cuizi7** [comment]
无支持计划。可参考文档自行对接数据。
