### ISSUE TITLE
分钟级回测期货合约，在哪个函数里进行动态合约池订阅？

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#783]
您好，我做分钟级回测，使用scheduler调度每天开盘后10分钟执行rebablance函数，执行策略逻辑，该逻辑要获取全市场的合约，并检查其最新分钟线的收盘价。

我应该在哪里订阅subscribe合约？我在rebalance里订阅没有用

如果在init里订阅，应该也不行，因为我每天订阅的合约不一样

**Comment by Cuizi7** [comment]
可以在before_trading中订阅。
