### ISSUE TITLE
问题：分钟级回测时，订单有没有可能在多个分钟线撮合成交

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#784]
假设在开盘后10分钟下单（买入100手），设置在next bar成交，设置成交量限制为0.1。实际下一分钟bar的总成交量的0.1倍不够100手，所以只能成交部分，那么订单剩余数量会继续在后面的分钟线上成交吗？

**Comment by Cuizi7** [comment]
限价单会挂着继续成交，市价单即成剩撤。
