### ISSUE TITLE
tick级回测时，限价单剩余数量会继续在后面的tick上成交吗？

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#786]
前面我问了分钟级回测时，订单有没有可能在多个分钟线撮合成交，https://github.com/ricequant/rqalpha/issues/784 

现在我想问tick级回测时，是不是也是一样，限价单剩余数量会继续在后面的tick上成交？
我的测试好像不会，它最多成交后一个tick的成交量。而我希望能够在当天后面的tick上继续成交，不知能不能做到？

**Comment by Cuizi7** [comment]
tick 回测中也是会在后续继续撮合的。如发现bug请附上可复现的代码。
