### ISSUE TITLE
发现handle_bar触发时进行交易使用的是当天的收盘价,这是否不够合理?

### ISSUE THREAD

**Issue by jaskell** [ricequant/rqalpha#8]
我通过最终的交易报告发现,每天交易使用的是当天的收盘价,这是否不够合理呢?
我想在每天的开盘时就进行所有的交易行为才更合理一些.
或者能否在代码中通过参数可以设置handle_bar的触发逻辑是使用当天开盘就进行交易,还是在当天收盘时才进行交易.

**Comment by handsomu** [comment]
目前股票的撮合逻辑是用的当天收盘价。说到底，在当前bar既做策略逻辑的生成，又用于成交，多少都会有点”使用未来数据“的问题。只不过股票有T+1的限制，所以使用当前bar进行成交没有那么大影响罢了。您所说使用当天开盘价进行撮合成交，在我看来其实与使用当天收盘价，或者平均成交价，区别不太大——都是当天的bar数据嘛。如果非要说调整的话，那可能也是用当天bar做策略逻辑生成，使用下一个bar的开盘价（或其他价格）做撮合成交。您觉得呢？

**Comment by shaoshoutianheyu** [comment]
我觉得可以按照zipline的思路 当个bar出信号  下个bar以开盘价成交，这样比较符合实际

**Comment by akulatatama** [comment]
@shaoshoutianheyu  我们最近的更新会提供用类似zipline的方法的另外一种撮合，以后会以这种撮合为主。发布了以后再close这个case。

**Comment by wh1100717** [comment]
@jaskell 其实每个人回测都有自己的业务场景，在自己的业务场景中合理，可能对于别人来说并不合理。

所以新版本的RQAlpha提供了两种撮合方式，以当前Bar的Close价格进行撮合，或者以下一个Bar的Open价格来撮合，您可以直接通过配置的方式来选择自己需要的撮合方式。具体参考 [参数配置](http://rqalpha.readthedocs.io/zh_CN/latest/api/config.html)

如果这两种撮合方式也不能满足您的需求，您也可以 通过 扩展 Mod 的方式 自己写一个撮合引擎扩展(AbstractMatcher) 来自定义撮合逻辑。
