### ISSUE TITLE
数据错误，停牌期间数据发生变化

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#805]
我使用如下命令观察贵州茅台后复权数据。
df = rq.get_price('600519.XSHG', start_date=20010825, end_date=20221228,adjust_type='post')
得到如下结果：

![image](https://github.com/ricequant/rqalpha/assets/116711018/8846e132-78f5-41b6-8737-fe094c91fe1c)

根据wind和通达信软件查看，发现贵州茅台2006.4.26 - 2006.5.24日停牌，在此期间数据应该保持不变，但上图中在5.19日收盘价相对前一天发生了巨大变化，这似乎明显错误。我查了wind数据，它们是保持不变的。
米筐由于这个变化，导致后面的后复权数据与wind明显不一致了。
这估计是比较大的错误，请查明原因，其他股票很可能也有此问题。

**Comment by Zhou-JiaJun** [comment]
因为在这期间有一笔分红，5月19号是除权除息日

**Comment by hzliu** [comment]
2006-05-19有一次拆分，数据无误。

**Comment by hzliu** [comment]
close
