### ISSUE TITLE
1分钟线期货回测出错

### ISSUE THREAD

**Issue by quant2008** [ricequant/rqalpha#816]
最近更新rqalpha后，进行1分钟频率（‘1m'）的回测，出如下错误
![image](https://github.com/ricequant/rqalpha/assets/116711018/c9d3bd15-bc7b-4807-88d6-bdc0b0f68578)
以前是正常的。

**Comment by quant2008** [comment]
解决了。用rqalpha_plus就行了

**Comment by hzliu** [comment]
不过 available_data_range 返回None貌似不太对
