### ISSUE TITLE
'StockAccount' object has no attribute 'portfolio'

### ISSUE THREAD

**Issue by xashes** [ricequant/rqalpha#82]
用限价单运行策略时提示"rqalpha_mod_sys_simulation/signal_broker.py"的第94行有这个错误，不知可否帮着看下是什么问题呢？
另外，34行好像有个typo, `mod_config.slippage`，打成`slppage`了。
77行，提示order没有style属性，我改成`order.type == ORDER_TYPE.LIMIT` (`from rqalpha.const import
 ORDER_TYPE`)不知是否可以。

**Comment by wh1100717** [comment]
@xashes 感谢您的反馈， `--signal` 模式还需要一些测试，下一个版本会修复你所提到的相关问题。

**Comment by xashes** [comment]
@wh1100717 好的，十分感谢

**Comment by wh1100717** [comment]
@xashes 

https://github.com/ricequant/rqalpha/commit/5271be9eba597635e516470ee04ce8065aca305b

https://github.com/ricequant/rqalpha/commit/c4081fd144a3215c9bd655eb640a7f8cda23b626

Commits 中更新了 signal_broker

已经发布的 2.0.9 版本中 `signal` 模式可用。
