### ISSUE TITLE
test api 不正确

### ISSUE THREAD

**Issue by hzliu** [ricequant/rqalpha#83]
def test_get_order():
        from rqalpha.api import order_shares, get_order
        def init(context):
            context.s1 = '000001.XSHE'
            context.amount = 100

        def handle_bar(context, bar_dict):
            order_id = order_shares(context.s1, context.amount, style=LimitOrder(9.5))
            order = get_order(order_id)
            assert order.order_book_id == context.s1
            assert order.quantity == context.amount
            assert order.unfilled_quantity + order.filled_quantity == order.quantity
    test_get_order_code_new = "".join(inspect.getsourcelines(test_get_order)[0])

最后得到的 test_get_order_code_new 仅定义了 test_get_order 函数(init 及 handle_bar 并没有定义)，这个代码传到 rqalpha 中跑完全是空转，没有达到测试目的。

@zjuguxi

**Comment by cedricporter** [comment]
我看到 test.py 里面有 `run(base_api_config, test_get_order_code_new)`

**Comment by hzliu** [comment]
为什么能回的这么快……

**Comment by cedricporter** [comment]
是我坑了谷老师   (;￢＿￢)

**Comment by hzliu** [comment]
还有 test_stock_api/test_future_api

@cedricporter
