### ISSUE TITLE
什么时候支持python3.12，3.12版本性能提升很大啊

### ISSUE THREAD

**Issue by ling1042133624** [ricequant/rqalpha#834]

**Comment by zldiablo** [comment]
能支持到3.11也行，3.11已经发布很久了

**Comment by Cuizi7** [comment]
> 能支持到3.11也行，3.11已经发布很久了

3.11支持的

**Comment by zldiablo** [comment]
> > 能支持到3.11也行，3.11已经发布很久了
> 
> 3.11支持的

我看setup.py里和pypi上都只支持到3.10，那是否要修改一下setup.py？

**Comment by Lin-Dongzhao** [comment]
已支持 python 3.12
