### ISSUE TITLE
mac无法安装mod

### ISSUE THREAD

**Issue by zp0605** [ricequant/rqalpha#839]
环境：
rqalpha:5.3.4
Python:3.8.2
MacOS：12.7
文档地址：https://www.bookstack.cn/read/rqalpha-3.3.x-zh/ea3ff641b646b145.md

安装测试mod(rqalpha-mod-hello)都报错：
rqalpha mod install -e .
Usage: rqalpha mod [OPTIONS] {list|enable|disable} [PARAMS]...

Error: Invalid value for '{list|enable|disable}': 'install' is not one of 'list', 'enable', 'disable'.

**Comment by Cuizi7** [comment]
安装mod的命令：pip install -e .
