### ISSUE TITLE
请问，在策略文件里面，是否还可以 import 其他自定义文件

### ISSUE THREAD

**Issue by yanghui1228** [ricequant/rqalpha#84]
目前看起来似乎不可以？

**Comment by xashes** [comment]
@yanghui1228 应该是可以的吧，我有import自己的module，可以运行。

**Comment by yanghui1228** [comment]
我想import自己的class，和策略文件放在一个package。
通过terminal运行的时候，package默认rqalpha site package目录，怎么也转不到自己的项目package。

yang.hui@icloud.com

On 9 Apr 2017, at 3:24 PM, xashes <notifications@github.com> wrote:

@yanghui1228 应该是可以的吧，我有import自己的module，可以运行。

**Comment by wh1100717** [comment]
目录结构如下：
![image](https://cloud.githubusercontent.com/assets/1681360/24843318/37bf05ce-1dd4-11e7-8c13-9ef8caf68cc7.png)

module1.py:

```python
def test():
  print("test123")
```

test.py:

```python
from rqalpha import run

config = {
  "base": {
    "strategy_file": "./algo1.py",
    "start_date": "2016-06-01",
    "end_date": "2016-07-01",
    "stock_starting_cash":100000,
    "benchmark": '000300.XSHG'
  },
  "extra":{
    "context_vars":{
      "short":5,
      "middle":10,
      "long":21
    }
  }
}

run(config)
```

algo1.py:

```python
from rqalpha.api import *
from module1 import test


def init(context):
    print("init")
    context.s1 = "000001.XSHE"
    update_universe(context.s1)
    # 是否已发送了order
    context.fired = False
    context.cnt = 1
    test()


def before_trading(context):
    print("Before Trading", context.cnt)
    context.cnt += 1


def handle_bar(context, bar_dict):
    context.cnt += 1
    if not context.fired:
        order_percent(context.s1, 1)
        context.fired = True
```

运行结果：

![image](https://cloud.githubusercontent.com/assets/1681360/24843360/91323c70-1dd4-11e7-9107-5979f6e56666.png)

**Comment by yanghui1228** [comment]
用python运行是可以的，但是用热情alpha启动不行

yang.hui@icloud.com

On 11 Apr 2017, at 11:20 AM, Eric Wang <notifications@github.com> wrote:

Closed #84.

**Comment by yanghui1228** [comment]
用python运行是可以的，但是用rqalpha启动就不行

yang.hui@icloud.com

On 11 Apr 2017, at 11:20 AM, Eric Wang <notifications@github.com> wrote:

Closed #84.

**Comment by wh1100717** [comment]
@yanghui1228 http://rqalpha.io/zh_CN/develop/development/data_source.html#import 扩展数据源的文档中包含了如何引入第三方模块的内容，看一下就知道怎么使用了。

**Comment by hzliu** [comment]
将策略用到的函数放到一个独立的包里面，策略本身只是一个单文件，这样应该是没问题的
