### ISSUE TITLE
我运行vnpy mod报错，具体信息如下：

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha#86]
OS: Ubuntu 16.04
Python 2.7.11
rqalpha-mod-vnpy: 0.9.11
rqalpha: 2.0.9

![screen shot 2017-04-11 at 14 43 27](https://cloud.githubusercontent.com/assets/20806018/24896728/d49d44e2-1ec8-11e7-8102-09cc56099669.png)

**Comment by wh1100717** [comment]
@FallacyWalker 将~/.rqalpha/mod_config.yml 删除 再试试？

**Comment by wh1100717** [comment]
这个报错是vnpy产生的错误，您已经在项目中开了issue了。

**Comment by Cuizi7** [comment]
已在0.9.13中修复
