### ISSUE TITLE
使用simple_macd测试出现现金为负异常

### ISSUE THREAD

**Issue by gucasbrg** [ricequant/rqalpha#9]
1、用examples/simple_macd.py 进行测试，
时间周期：2014-01-04\2015-01-04
资金默认：100000
回测周期：每日
从代码与复制到ricequant，出现现金为负情况：
![image](https://cloud.githubusercontent.com/assets/3182658/17649182/79bef716-6260-11e6-8892-81021c5329b6.png)
看算多少股时，context.portfolio.cash/bar_dict[context.s1].close类似此，买多少股的时候没有把交易费用加进去？

**Comment by cedricporter** [comment]
这个ricequant的首席技术官Kangol做出过回答：

>     买入前的简易风控检查不计算slippage和transaction cost，matcher那边成交后可能会超出一点，属于正常
>     券商也会碰到这个问题
>     市场单丢出去滑点后超出了现金量，券商就直接算你欠他一点钱，反正你有股票在他手里，欠一点也无所谓
>     这个我问过富途的人，官方回答
