### ISSUE TITLE
如何在样本内回测结果的基础上在样本外继续跟踪策略表现？

### ISSUE THREAD

**Issue by wanhanwan** [ricequant/rqalpha#90]
例如回测时的时间区间为2005/1/1至2016/12/31，我想在继续跟踪2017年以来的策略表现，但又不想从2005年开始重新跑一遍回测，我该如何做？

**Comment by wh1100717** [comment]
@wanhanwan 

可以通过 RQAlpha 的 persist_provider 来实现。

您可以参考 [DiskPersistProvider](https://github.com/ricequant/rqalpha/blob/master/rqalpha/utils/disk_persist_provider.py) 的实现。

您也可以参考 [能不能考虑提供策略参数持久化的支持？](https://github.com/ricequant/rqalpha/issues/52) 的讨论。

很抱歉，这块还没有比较详细的文档，而且对应的 API 和接口未来可能会重构。

我们也会尽快提供相关的文档，以及相关的 Mod 来支持回测/模拟/实盘 自定义持久化 相关的内容。

如果您不想使用我们提供的 Persist 相关内容，也可以通过 Mod 来独立实现您所需要的功能，大体思路如下:

* 注册 EVENT.POST_SETTLEMENT 事件
* 在响应函数中获取portfolio, 执行portfolio.get_state() 获取序列化好的数据，并进行存储
* 重新启动的时候初始化好Portfolio以后，将存储的数据读取，并执行portfolio.set_state(state) 来进行投资组合的恢复。

**Comment by wanhanwan** [comment]
但是我的策略包括一个portflio和一个benchmark_portfolio,在执行benchmark_portfolio.set_state()会报
NotImplementedError
在BenchmarkAccount中没有实现set_state()方法?


发件人:  Eric Wang
答复:  ricequant/rqalpha
日期:  2017年4月12日 星期三 下午1:41
至:  ricequant/rqalpha
抄送:  wanhanwan, Mention
主题:  Re: [ricequant/rqalpha] 如何在样本内回测结果的基础上在样本外继续跟踪策略表现？ (#90)


@wanhanwan

可以通过 RQAlpha 的 persist_provider 来实现。

您可以参考 DiskPersistProvider 的实现。

您也可以参考 能不能考虑提供策略参数持久化的支持？ 的讨论。

很抱歉，这块还没有比较详细的文档，而且对应的 API 和接口未来可能会重构。

我们也会尽快提供相关的文档，以及相关的 Mod 来支持回测/模拟/实盘 自定义持久化 相关的内容。

如果您不想使用我们提供的 Persist 相关内容，也可以通过 Mod 来独立实现您所需要的功能，大体思路如下:
注册 EVENT.POST_SETTLEMENT 事件
在响应函数中获取portfolio, 执行portfolio.get_state() 获取序列化好的数据，并进行存储
重新启动的时候初始化好Portfolio以后，将存储的数据读取，并执行portfolio.set_state(state) 来进行投资组合的恢复。
—You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ricequant/rqalpha","title":"ricequant/rqalpha","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ricequant/rqalpha"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wh1100717 in #90: @wanhanwan \r\n\r\n可以通过 RQAlpha 的 persist_provider 来实现。\r\n\r\n您可以参考 [DiskPersistProvider](https://github.com/ricequant/rqalpha/blob/master/rqalpha/utils/disk_persist_provider.py) 的实现。\r\n\r\n您也可以参考 [能不能考虑提供策略参数持久化的支持？](https://github.com/ricequant/rqalpha/issues/52) 的讨论。\r\n\r\n很抱歉，这块还没有比较详细的文档，而且对应的 API 和接口未来可能会重构。\r\n\r\n我们也会尽快提供相关的文档，以及相关的 Mod 来支持回测/模拟/实盘 自定义持久化 相关的内容。\r\n\r\n如果您不想使用我们提供的 Persist 相关内容，也可以通过 Mod 来独立实现您所需要的功能，大体思路如下:\r\n\r\n* 注册 EVENT.POST_SETTLEMENT 事件\r\n* 在响应函数中获取portfolio, 执行portfolio.get_state() 获取序列化好的数据，并进行存储\r\n* 重新启动的时候初始化好Portfolio以后，将存储的数据读取，并执行portfolio.set_state(state) 来进行投资组合的恢复。\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ricequant/rqalpha/issues/90#issuecomment-293479347"}}}

**Comment by wh1100717** [comment]
@wanhanwan 我看了一下 `BenchmarkAccount` 继承自 `StockAccount`  其已经实现了 `set_state` 和 
 `get_state` 方法，是否可以贴一下具体的报错堆栈信息？

**Comment by wanhanwan** [comment]
应该是在portfolio.py文件里 setstate方法中if-else缺少ACCOUNT_TYPE.BENCHMARK条件。

发件人:  Eric Wang
答复:  ricequant/rqalpha
日期:  2017年4月13日 星期四 上午11:24
至:  ricequant/rqalpha
抄送:  wanhanwan, Mention
主题:  Re: [ricequant/rqalpha] 如何在样本内回测结果的基础上在样本外继续跟踪策略表现？ (#90)


@wanhanwan 我看了一下 BenchmarkAccount 继承自 StockAccount  其已经实现了 set_state 和
get_state 方法，是否可以贴一下具体的报错堆栈信息？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ricequant/rqalpha","title":"ricequant/rqalpha","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ricequant/rqalpha"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wh1100717 in #90: @wanhanwan 我看了一下 `BenchmarkAccount` 继承自 `StockAccount`  其已经实现了 `set_state` 和 \r\n `get_state` 方法，是否可以贴一下具体的报错堆栈信息？"}],"action":{"name":"View Issue","url":"https://github.com/ricequant/rqalpha/issues/90#issuecomment-293768612"}}}

**Comment by wh1100717** [comment]
@wanhanwan 确实如此  非常感谢！！
