### ISSUE TITLE
rqalpha中文字体安装问题

### ISSUE THREAD

**Issue by johnsonchak** [ricequant/rqalpha#91]
系统环境：mac os 10.12.4 python:3.5
按照conda的虚拟环境，根据教程走流程下来安装中文字体显示如下
![image](https://cloud.githubusercontent.com/assets/20765015/24943315/af2e7ed6-1f88-11e7-8b50-f54b309de0ce.png)
但是在run策略的时候依然显示missing chinese fonts

**Comment by wh1100717** [comment]
@cedricporter 貌似新版本的 mac 木有测试过中文字体安装是否OK，等回来了有空看一下？

**Comment by johnsonchak** [comment]
只要fc-list : file，能找得到WenQuanYI这个字体就没有问题...

之前出现这个问题，但现在直接就好了，无解。

**Comment by olivier-ma** [comment]
我已经安装了文泉驿字体，不知道为什么还是提示没有中文字体（安装文泉驿之前我的mac上也已经有中文字体）。

```
fc-list | grep -i "Wen"
/usr/share/fonts/chinese/WenQuanYi Micro Hei.ttf: 文泉驿微米黑,文泉驛微米黑,WenQuanYi Micro Hei:style=Regular
```

**Comment by zsluedem** [comment]
这个bug我以前查很久，其实好像是matplotlib问题，你要在~/.matplotlib/matplotbrc中设置好才可以

**Comment by ColorFuzzy** [comment]
1. 安装字体 Microsoft YaHei, windows系统跳过

> Download Microsoft YaHei font for FREE

2. 获取matplotlib的配置文件路径, 添加/修改配置 => font.family: Microsoft YaHei

> import matplotlib
> matplotlib.matplotlib_fname()

3. 获取matplotlib的缓存位置, 除了配置文件, 其他的全部删除

> import matplotlib
> matplotlib.get_cachedir()

Mac验证通过, 主要是安装字体, 设置字体, 删除缓存.

**Comment by pythonwood** [comment]
没有 “WenQuanYI”字体， 但是有"WenQuanYi", 希望做下兼容。
$ fc-list | grep WenQuanYI
$ fc-list | grep -i WenQuanYI
/usr/share/fonts/truetype/wqy/wqy-microhei.ttc: 文泉驿微米黑,文泉驛微米黑,WenQuanYi Micro Hei:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_10ptb.pcf: WenQuanYi Bitmap Song:style=Bold
/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc: 文泉驿正黑,文泉驛正黑,WenQuanYi Zen Hei:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_12pt.pcf: WenQuanYi Bitmap Song:style=Regular
/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc: 文泉驿点阵正黑,文泉驛點陣正黑,WenQuanYi Zen Hei Sharp:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_10pt.pcf: WenQuanYi Bitmap Song:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_9pt.pcf: WenQuanYi Bitmap Song:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_11pt.pcf: WenQuanYi Bitmap Song:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_9ptb.pcf: WenQuanYi Bitmap Song:style=Bold
/usr/share/fonts/X11/misc/wenquanyi_11ptb.pcf: WenQuanYi Bitmap Song:style=Bold
/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc: 文泉驿等宽正黑,文泉驛等寬正黑,WenQuanYi Zen Hei Mono:style=Regular
/usr/share/fonts/truetype/wqy/wqy-microhei.ttc: 文泉驿等宽微米黑,文泉驛等寬微米黑,WenQuanYi Micro Hei Mono:style=Regular
/usr/share/fonts/X11/misc/wenquanyi_12ptb.pcf: WenQuanYi Bitmap Song:style=Bold
