### ISSUE TITLE
vnpymod恢复仓位时出现空仓key error

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha#92]
在每次启动vnpy的时候，系统都会自动查询当前仓位信息加载到RQA中。发现当出现空方向仓位的时候就直接报key error了。查看代码发现data_factory中cache_vnpy_position_before_init函数中的空仓字段写错。不应为sell_position，而应为sell_quantity

**Comment by Cuizi7** [comment]
这个要不还是发到 rqalpha-mod-vnpy 项目下？
