### ISSUE TITLE
能解释下handle_split参数的作用么？

### ISSUE THREAD

**Issue by yu123ert** [ricequant/rqalpha#95]
文档里面说，
N/A 	- - handle-split 	开启自动处理, 默认不开启
N/A 	- - not-handle-split 	不开启自动处理, 默认不开启

可是自动处理指什么，会有什么影响，没有找到相关文档，ricequant平台的文档好像也没有。ricequant说会自动进行除权除息处理，不知道是不是指这个，还是别的什么。

麻烦稍微做个说明，谢谢。

**Comment by cedricporter** [comment]
这个在回测中是不需要指定该参数，因为我们的回测数据是包含拆分的前复权数据。

但是如果是「PaperTrading」或者是「实盘」，此时用的是实时行情数据，就需要在运行过程中动态处理拆分。
