### ISSUE TITLE
我不是很懂这段描述,新的配置文件是什么格式的?或者说是以什么作为后缀的?

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#96]
于是我们的第一个 Mod 就写好了，现在我们需要修改配置，以让我们的 mod 生效，我们创建一个新的配置文件，在 mod 下面

mod:
  hello_world:
    lib: 'rqalpha.mod.hello_world'
    enabled: true
    priority: 100

**Comment by wh1100717** [comment]
@myz8110 http://rqalpha.io/zh_CN/latest/api/config.html#config-yml
