### ISSUE TITLE
本地回测与网站回测结果不同

### ISSUE THREAD

**Issue by curiousbull** [ricequant/rqalpha#98]
同样的用官方文档中的策略，本地回测结果和在官方网站跑的完全不同
而且可以很明显的看出来本地回测结果明显不对，譬如，我用官方文档中的MACD策略，
本地回测结果如图：
![01](https://cloud.githubusercontent.com/assets/19818644/25179763/d021810a-253d-11e7-81c0-244b2b53a755.png)
可以看到基准回测明显不对啊，收益率也太高了
同样策略在你们网站上跑起来的结果如下图
![02](https://cloud.githubusercontent.com/assets/19818644/25179818/14a6d74e-253e-11e7-90cb-cdbd20c63956.png)

**Comment by curiousbull** [comment]
策略源码如下：
import talib

def init(context):
    context.s1 = "000001.XSHE"
    update_universe(context.s1)
    context.SHORTPERIOD = 12
    context.LONGPERIOD = 26
    context.SMOOTHPERIOD = 9
    context.OBSERVATION = 100

def handle_bar(context, bar_dict):
    prices = history_bars(context.s1, context.OBSERVATION, '1d', 'close')

    macd, signal, hist = talib.MACD(prices, context.SHORTPERIOD, context.LONGPERIOD,
                                    context.SMOOTHPERIOD)

    plot("macd", macd[-1])
    plot("macd signal", signal[-1])

    if macd[-1] - signal[-1] < 0 and macd[-2] - signal[-2] > 0:
        curPosition = context.portfolio.positions[context.s1].quantity
        if curPosition > 0:
            order_target_value(context.s1, 0)

    if macd[-1] - signal[-1] > 0 and macd[-2] - signal[-2] < 0:
        order_target_percent(context.s1, 1)

**Comment by hzliu** [comment]
本地跑的基准设置的是？我跑了一下 develop 分支，和网站上基准收益是完全一样的

**Comment by curiousbull** [comment]
我用的是pip安装的，难道这有差别？


来自 魅族 PRO 6 Plus

-------- 原始邮件 --------
发件人：Hongzhang Liu <notifications@github.com>
时间：周四 4月20日 14:41
收件人：ricequant/rqalpha <rqalpha@noreply.github.com>
抄送：curiousbull <curiousbull@163.com>,Author <author@noreply.github.com>
主题：Re: [ricequant/rqalpha] 本地回测与网站回测结果不同 (#98)

**Comment by wh1100717** [comment]
@hzliu @handsomu 有结论吗？

**Comment by wh1100717** [comment]
no resp & close
