### ISSUE TITLE
期货加入get_dominant_future API

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha#99]
如题。
该API是根据每个交易日期货的持仓量进行下一交易日主力合约的判断。
我们加进来吧，期货挺需要的。

**Comment by johnsonick** [comment]
RQTypeError: get_dominant_future() got an unexpected keyword argument 'start_date'
这个错误是啥意思啊。doc里面不是说有start_date和end_date两个参数嘛

**Comment by handsomu** [comment]
start_date, end_date是研究时候使用的。线上回测时候没有这个参数，为获取当前交易日的主力合约代码。

**Comment by cedricporter** [comment]
目前 get_dominant_future 数据是通过 RQData 获取的，目前开源版本暂时没有数据源支持该 API。先 close 了。
